//// Captured Admin GraphQL mutation + input object schema types and
//// the lookup helpers used by the central required-field validator
//// in `proxy/mutation_helpers.gleam`.
////
//// The actual data lives in the generated sibling
//// `mutation_schema_data.gleam`, regenerated by
//// `scripts/sync-mutation-schema.sh` from
//// `config/admin-graphql-mutation-schema.json`. That JSON is itself
//// captured by `scripts/capture-mutation-input-schema.mts` against a
//// live Admin GraphQL endpoint with `includeDeprecated: true`, so
//// deprecated aliases (e.g. `WebhookSubscriptionInput.callbackUrl`,
//// `productCreate(input:)`) are preserved.
////
//// This module deliberately holds only the types and value-level
//// helpers — it must not import the generated `mutation_schema_data`
//// module, otherwise the data module's reverse import would form a
//// cycle. Callers wanting an indexed lookup table use
//// `proxy/mutation_schema_lookup.gleam`.
////
//// The validator that ultimately consumes this lives in
//// `proxy/mutation_helpers.gleam`. It walks AST argument literals and
//// resolved variable values against this schema, emitting the same
//// top-level GraphQL error envelopes real Shopify produces:
////   - `missingRequiredArguments` — a NON_NULL Mutation arg is absent
////     or has a null literal / unbound variable.
////   - `missingRequiredInputObjectAttribute` — a NON_NULL field on an
////     input object literal is absent.
////   - `argumentLiteralsIncompatible` — a literal `null` is supplied
////     for a NON_NULL arg or input field.
////
//// Business-rule validations (e.g. "URL must be present" on
//// `WebhookSubscriptionInput`, where neither `uri` nor `callbackUrl`
//// is structurally NON_NULL but Shopify still rejects an empty
//// payload via `userErrors`) are NOT covered here — they are
//// enforced by per-handler logic and verified via parity specs.

import gleam/option.{type Option}

/// One arg on a Mutation field. `default_value` carries the raw
/// printed default from introspection (e.g. `"false"`, `"STANDARD"`).
/// Args with a non-`None` default are *optional* in the GraphQL sense
/// even when the type is `NON_NULL` — the server fills the default
/// when the client omits the arg.
pub type SchemaArg {
  SchemaArg(
    name: String,
    is_deprecated: Bool,
    deprecation_reason: Option(String),
    default_value: Option(String),
    type_: SchemaType,
  )
}

/// One field on a captured input object. `default_value` follows the
/// same convention as `SchemaArg.default_value`: a non-`None` default
/// makes a `NON_NULL` field omittable.
pub type SchemaInputField {
  SchemaInputField(
    name: String,
    is_deprecated: Bool,
    deprecation_reason: Option(String),
    default_value: Option(String),
    type_: SchemaType,
  )
}

/// One Mutation field — name and the captured arg list.
pub type SchemaMutation {
  SchemaMutation(
    name: String,
    is_deprecated: Bool,
    deprecation_reason: Option(String),
    args: List(SchemaArg),
  )
}

/// One captured input object — name and the captured field list.
pub type SchemaInputObject {
  SchemaInputObject(name: String, input_fields: List(SchemaInputField))
}

/// Recursive GraphQL type wrapper, mirroring introspection's
/// `{kind, name, ofType}` chain. Captured to depth 5 in the JSON
/// fixture (well beyond the deepest signature Shopify currently emits).
pub type SchemaType {
  NonNullType(of: SchemaType)
  ListType(of: SchemaType)
  NamedType(name: String)
}

/// True when the outermost wrapper is `NON_NULL`.
pub fn is_non_null(t: SchemaType) -> Bool {
  case t {
    NonNullType(..) -> True
    _ -> False
  }
}

/// Strip a single `NON_NULL` wrapper if present.
pub fn unwrap_non_null(t: SchemaType) -> SchemaType {
  case t {
    NonNullType(of:) -> of
    _ -> t
  }
}

/// Walk a `SchemaType` to find the named (non-wrapper) leaf, returning
/// the leaf type name. Returns `None` for malformed entries that bottom
/// out in nothing.
pub fn named_leaf(t: SchemaType) -> Option(String) {
  case t {
    NonNullType(of:) -> named_leaf(of)
    ListType(of:) -> named_leaf(of)
    NamedType(name:) -> option.Some(name)
  }
}

/// Render a `SchemaType` into the GraphQL signature notation
/// (`"ID!"`, `"[String!]!"`, `"DraftOrderInput!"`, …) that real
/// Shopify uses in `missingRequiredArguments` /
/// `missingRequiredInputObjectAttribute` error messages.
pub fn render_signature(t: SchemaType) -> String {
  case t {
    NonNullType(of:) -> render_signature(of) <> "!"
    ListType(of:) -> "[" <> render_signature(of) <> "]"
    NamedType(name:) -> name
  }
}
