api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "conformance-discount"
type = "function"
uid = "a794665f-3d03-f1e0-fbf0-93fcbe3ccd278d0df884"
description = "t:description"

[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/cart_lines_discounts_generate_run.graphql"
export = "cart_lines_discounts_generate_run"

[[extensions.targeting]]
target = "cart.delivery-options.discounts.generate.run"
input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
export = "cart_delivery_options_discounts_generate_run"

[extensions.build]
command = "cargo build --target=wasm32-unknown-unknown --release"
path = "target/wasm32-unknown-unknown/release/conformance-discount.wasm"
watch = ["src/**/*.rs"]
