# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0db6d7e08e4ba05ce97440df36c7ed33"
name = "hermes-conformance-products"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_product_listings,read_inventory,write_inventory,read_locations,write_locations,read_files,write_files,read_publications,write_publications,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions,read_themes,read_orders,write_orders,read_draft_orders,write_draft_orders,read_order_edits,write_order_edits,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_fulfillments,write_fulfillments,read_customers,write_customers,read_customer_merge,write_customer_merge,read_legal_policies,write_legal_policies,read_locales,write_locales,read_markets,write_markets,read_translations,write_translations,read_discounts,write_discounts,read_content,write_content,read_shipping,write_shipping,read_returns,write_returns,read_payment_customizations,write_payment_customizations,read_payment_terms,write_payment_terms,read_shopify_payments_disputes,read_shopify_payments_payouts,read_store_credit_accounts,read_store_credit_account_transactions,write_store_credit_account_transactions,write_gift_cards,read_marketing_events,write_marketing_events,write_cash_tracking,read_validations,write_validations,read_cart_transforms,write_cart_transforms,write_delivery_customizations,write_purchase_options,write_gift_card_transactions,write_fulfillment_constraint_rules,write_customer_data_erasure"

[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home/api/auth", "http://127.0.0.1:13387/auth/callback"]
