//// Mirrors the slices of `src/state/store.ts` that have been ported to
//// Gleam plus the mutation log. Additional resources still land
//// slice-by-slice with their domain handlers.
////
//// The TS class mutates state in place. This Gleam port returns updated
//// `Store` records from every mutator so callers thread state through
//// their own pipeline (matching the pattern already established for
//// `SyntheticIdentityRegistry`).

import gleam/dict.{type Dict}
import gleam/option.{type Option}
import shopify_draft_proxy/graphql/root_field
import shopify_draft_proxy/state/types.{
  type AbandonedCheckoutRecord, type AbandonmentRecord,
  type AdminPlatformFlowSignatureRecord, type AdminPlatformFlowTriggerRecord,
  type AdminPlatformGenericNodeRecord, type AdminPlatformTaxonomyCategoryRecord,
  type AppInstallationRecord, type AppOneTimePurchaseRecord, type AppRecord,
  type AppSubscriptionLineItemRecord, type AppSubscriptionRecord,
  type AppUsageRecord, type B2BCompanyContactRecord,
  type B2BCompanyContactRoleRecord, type B2BCompanyLocationRecord,
  type B2BCompanyRecord, type BackupRegionRecord, type BulkOperationRecord,
  type CalculatedOrderRecord, type CapturedJsonValue, type CarrierServiceRecord,
  type CartTransformRecord, type CatalogRecord, type ChannelRecord,
  type CollectionRecord, type CustomerAccountPageRecord,
  type CustomerAddressRecord, type CustomerCatalogConnectionRecord,
  type CustomerCatalogPageInfoRecord, type CustomerDataErasureRequestRecord,
  type CustomerEventSummaryRecord, type CustomerMergeRequestRecord,
  type CustomerMetafieldRecord, type CustomerOrderSummaryRecord,
  type CustomerPaymentMethodRecord, type CustomerPaymentMethodUpdateUrlRecord,
  type CustomerRecord, type CustomerSegmentMembersQueryRecord,
  type DelegatedAccessTokenRecord, type DeliveryProfileRecord,
  type DiscountBulkOperationRecord, type DiscountRecord, type DraftOrderRecord,
  type DraftOrderVariantCatalogRecord, type FileRecord,
  type FulfillmentOrderRecord, type FulfillmentRecord,
  type FulfillmentServiceRecord, type GiftCardConfigurationRecord,
  type GiftCardRecord, type InventoryShipmentRecord,
  type InventoryTransferRecord, type LocaleRecord, type LocationRecord,
  type MarketLocalizationRecord, type MarketRecord,
  type MarketingChannelDefinitionRecord, type MarketingEngagementRecord,
  type MarketingRecord, type MetafieldDefinitionRecord,
  type MetaobjectDefinitionRecord, type MetaobjectRecord,
  type OnlineStoreContentRecord, type OnlineStoreIntegrationRecord,
  type OrderMandatePaymentRecord, type OrderRecord,
  type PaymentCustomizationRecord, type PaymentReminderSendRecord,
  type PaymentTermsRecord, type PriceListRecord, type ProductCollectionRecord,
  type ProductFeedRecord, type ProductMediaRecord, type ProductMetafieldRecord,
  type ProductOperationRecord, type ProductOptionRecord, type ProductRecord,
  type ProductResourceFeedbackRecord, type ProductVariantRecord,
  type PublicationRecord, type ReverseDeliveryRecord,
  type ReverseFulfillmentOrderRecord, type SavedSearchRecord, type SegmentRecord,
  type SellingPlanGroupRecord, type ShippingOrderRecord,
  type ShippingPackageRecord, type ShopLocaleRecord, type ShopRecord,
  type ShopResourceFeedbackRecord, type ShopifyFunctionRecord,
  type StoreCreditAccountRecord, type StoreCreditAccountTransactionRecord,
  type StorePropertyMutationPayloadRecord, type StorePropertyRecord,
  type StorePropertyValue, type TaxAppConfigurationRecord,
  type TranslationRecord, type ValidationRecord, type WebPresenceRecord,
  type WebhookSubscriptionRecord,
}

pub type BaseState {
  BaseState(
    products: Dict(String, ProductRecord),
    product_order: List(String),
    deleted_product_ids: Dict(String, Bool),
    product_count: Option(Int),
    product_variants: Dict(String, ProductVariantRecord),
    product_variant_order: List(String),
    product_variant_count: Option(Int),
    product_options: Dict(String, ProductOptionRecord),
    product_operations: Dict(String, ProductOperationRecord),
    selling_plan_groups: Dict(String, SellingPlanGroupRecord),
    selling_plan_group_order: List(String),
    deleted_selling_plan_group_ids: Dict(String, Bool),
    markets: Dict(String, MarketRecord),
    market_order: List(String),
    deleted_market_ids: Dict(String, Bool),
    catalogs: Dict(String, CatalogRecord),
    catalog_order: List(String),
    deleted_catalog_ids: Dict(String, Bool),
    price_lists: Dict(String, PriceListRecord),
    price_list_order: List(String),
    deleted_price_list_ids: Dict(String, Bool),
    web_presences: Dict(String, WebPresenceRecord),
    web_presence_order: List(String),
    deleted_web_presence_ids: Dict(String, Bool),
    market_localizations: Dict(String, MarketLocalizationRecord),
    markets_root_payloads: Dict(String, CapturedJsonValue),
    product_media: Dict(String, List(ProductMediaRecord)),
    files: Dict(String, FileRecord),
    file_order: List(String),
    deleted_file_ids: Dict(String, Bool),
    collections: Dict(String, CollectionRecord),
    collection_order: List(String),
    product_collections: Dict(String, ProductCollectionRecord),
    deleted_collection_ids: Dict(String, Bool),
    locations: Dict(String, LocationRecord),
    location_order: List(String),
    publications: Dict(String, PublicationRecord),
    publication_order: List(String),
    deleted_publication_ids: Dict(String, Bool),
    channels: Dict(String, ChannelRecord),
    channel_order: List(String),
    product_feeds: Dict(String, ProductFeedRecord),
    product_feed_order: List(String),
    deleted_product_feed_ids: Dict(String, Bool),
    product_resource_feedback: Dict(String, ProductResourceFeedbackRecord),
    shop_resource_feedback: Dict(String, ShopResourceFeedbackRecord),
    abandoned_checkouts: Dict(String, AbandonedCheckoutRecord),
    abandoned_checkout_order: List(String),
    abandonments: Dict(String, AbandonmentRecord),
    abandonment_order: List(String),
    draft_orders: Dict(String, DraftOrderRecord),
    draft_order_order: List(String),
    deleted_draft_order_ids: Dict(String, Bool),
    draft_order_variant_catalog: Dict(String, DraftOrderVariantCatalogRecord),
    orders: Dict(String, OrderRecord),
    order_order: List(String),
    deleted_order_ids: Dict(String, Bool),
    order_mandate_payments: Dict(String, OrderMandatePaymentRecord),
    inventory_transfers: Dict(String, InventoryTransferRecord),
    inventory_transfer_order: List(String),
    deleted_inventory_transfer_ids: Dict(String, Bool),
    inventory_shipments: Dict(String, InventoryShipmentRecord),
    inventory_shipment_order: List(String),
    deleted_inventory_shipment_ids: Dict(String, Bool),
    carrier_services: Dict(String, CarrierServiceRecord),
    carrier_service_order: List(String),
    deleted_carrier_service_ids: Dict(String, Bool),
    fulfillment_services: Dict(String, FulfillmentServiceRecord),
    fulfillment_service_order: List(String),
    deleted_fulfillment_service_ids: Dict(String, Bool),
    fulfillments: Dict(String, FulfillmentRecord),
    fulfillment_order: List(String),
    fulfillment_orders: Dict(String, FulfillmentOrderRecord),
    fulfillment_order_order: List(String),
    shipping_orders: Dict(String, ShippingOrderRecord),
    reverse_fulfillment_orders: Dict(String, ReverseFulfillmentOrderRecord),
    reverse_fulfillment_order_order: List(String),
    reverse_deliveries: Dict(String, ReverseDeliveryRecord),
    reverse_delivery_order: List(String),
    calculated_orders: Dict(String, CalculatedOrderRecord),
    delivery_profiles: Dict(String, DeliveryProfileRecord),
    delivery_profile_order: List(String),
    deleted_delivery_profile_ids: Dict(String, Bool),
    shipping_packages: Dict(String, ShippingPackageRecord),
    shipping_package_order: List(String),
    deleted_shipping_package_ids: Dict(String, Bool),
    backup_region: Option(BackupRegionRecord),
    admin_platform_generic_nodes: Dict(String, AdminPlatformGenericNodeRecord),
    admin_platform_taxonomy_categories: Dict(
      String,
      AdminPlatformTaxonomyCategoryRecord,
    ),
    admin_platform_taxonomy_category_order: List(String),
    admin_platform_flow_signatures: Dict(
      String,
      AdminPlatformFlowSignatureRecord,
    ),
    admin_platform_flow_signature_order: List(String),
    admin_platform_flow_triggers: Dict(String, AdminPlatformFlowTriggerRecord),
    admin_platform_flow_trigger_order: List(String),
    shop: Option(ShopRecord),
    b2b_companies: Dict(String, B2BCompanyRecord),
    b2b_company_order: List(String),
    deleted_b2b_company_ids: Dict(String, Bool),
    b2b_company_contacts: Dict(String, B2BCompanyContactRecord),
    b2b_company_contact_order: List(String),
    deleted_b2b_company_contact_ids: Dict(String, Bool),
    b2b_company_contact_roles: Dict(String, B2BCompanyContactRoleRecord),
    b2b_company_contact_role_order: List(String),
    deleted_b2b_company_contact_role_ids: Dict(String, Bool),
    b2b_company_locations: Dict(String, B2BCompanyLocationRecord),
    b2b_company_location_order: List(String),
    deleted_b2b_company_location_ids: Dict(String, Bool),
    store_property_locations: Dict(String, StorePropertyRecord),
    store_property_location_order: List(String),
    deleted_store_property_location_ids: Dict(String, Bool),
    business_entities: Dict(String, StorePropertyRecord),
    business_entity_order: List(String),
    publishables: Dict(String, StorePropertyRecord),
    publishable_order: List(String),
    store_property_mutation_payloads: Dict(
      String,
      StorePropertyMutationPayloadRecord,
    ),
    product_metafields: Dict(String, ProductMetafieldRecord),
    metafield_definitions: Dict(String, MetafieldDefinitionRecord),
    deleted_metafield_definition_ids: Dict(String, Bool),
    saved_searches: Dict(String, SavedSearchRecord),
    saved_search_order: List(String),
    deleted_saved_search_ids: Dict(String, Bool),
    webhook_subscriptions: Dict(String, WebhookSubscriptionRecord),
    webhook_subscription_order: List(String),
    deleted_webhook_subscription_ids: Dict(String, Bool),
    online_store_content: Dict(String, OnlineStoreContentRecord),
    online_store_content_order: List(String),
    deleted_online_store_content_ids: Dict(String, Bool),
    online_store_integrations: Dict(String, OnlineStoreIntegrationRecord),
    online_store_integration_order: List(String),
    deleted_online_store_integration_ids: Dict(String, Bool),
    apps: Dict(String, AppRecord),
    app_order: List(String),
    app_installations: Dict(String, AppInstallationRecord),
    app_installation_order: List(String),
    current_installation_id: Option(String),
    app_subscriptions: Dict(String, AppSubscriptionRecord),
    app_subscription_order: List(String),
    app_subscription_line_items: Dict(String, AppSubscriptionLineItemRecord),
    app_subscription_line_item_order: List(String),
    app_one_time_purchases: Dict(String, AppOneTimePurchaseRecord),
    app_one_time_purchase_order: List(String),
    app_usage_records: Dict(String, AppUsageRecord),
    app_usage_record_order: List(String),
    delegated_access_tokens: Dict(String, DelegatedAccessTokenRecord),
    delegated_access_token_order: List(String),
    shopify_functions: Dict(String, ShopifyFunctionRecord),
    shopify_function_order: List(String),
    bulk_operations: Dict(String, BulkOperationRecord),
    bulk_operation_order: List(String),
    metaobject_definitions: Dict(String, MetaobjectDefinitionRecord),
    metaobject_definition_order: List(String),
    deleted_metaobject_definition_ids: Dict(String, Bool),
    metaobjects: Dict(String, MetaobjectRecord),
    metaobject_order: List(String),
    deleted_metaobject_ids: Dict(String, Bool),
    marketing_activities: Dict(String, MarketingRecord),
    marketing_activity_order: List(String),
    marketing_events: Dict(String, MarketingRecord),
    marketing_event_order: List(String),
    marketing_channel_definitions: Dict(
      String,
      MarketingChannelDefinitionRecord,
    ),
    marketing_engagements: Dict(String, MarketingEngagementRecord),
    marketing_engagement_order: List(String),
    deleted_marketing_activity_ids: Dict(String, Bool),
    deleted_marketing_event_ids: Dict(String, Bool),
    deleted_marketing_engagement_ids: Dict(String, Bool),
    validations: Dict(String, ValidationRecord),
    validation_order: List(String),
    deleted_validation_ids: Dict(String, Bool),
    cart_transforms: Dict(String, CartTransformRecord),
    cart_transform_order: List(String),
    deleted_cart_transform_ids: Dict(String, Bool),
    tax_app_configuration: Option(TaxAppConfigurationRecord),
    discounts: Dict(String, DiscountRecord),
    discount_order: List(String),
    deleted_discount_ids: Dict(String, Bool),
    discount_bulk_operations: Dict(String, DiscountBulkOperationRecord),
    gift_cards: Dict(String, GiftCardRecord),
    gift_card_order: List(String),
    gift_card_configuration: Option(GiftCardConfigurationRecord),
    customers: Dict(String, CustomerRecord),
    customer_order: List(String),
    customer_catalog_connections: Dict(String, CustomerCatalogConnectionRecord),
    deleted_customer_ids: Dict(String, Bool),
    customer_addresses: Dict(String, CustomerAddressRecord),
    customer_address_order: List(String),
    deleted_customer_address_ids: Dict(String, Bool),
    customer_order_summaries: Dict(String, CustomerOrderSummaryRecord),
    customer_order_connection_page_infos: Dict(
      String,
      CustomerCatalogPageInfoRecord,
    ),
    customer_event_summaries: Dict(String, CustomerEventSummaryRecord),
    customer_event_connection_page_infos: Dict(
      String,
      CustomerCatalogPageInfoRecord,
    ),
    customer_last_orders: Dict(String, CustomerOrderSummaryRecord),
    customer_metafields: Dict(String, CustomerMetafieldRecord),
    customer_payment_methods: Dict(String, CustomerPaymentMethodRecord),
    customer_payment_method_update_urls: Dict(
      String,
      CustomerPaymentMethodUpdateUrlRecord,
    ),
    deleted_customer_payment_method_ids: Dict(String, Bool),
    payment_reminder_sends: Dict(String, PaymentReminderSendRecord),
    payment_customizations: Dict(String, PaymentCustomizationRecord),
    payment_customization_order: List(String),
    deleted_payment_customization_ids: Dict(String, Bool),
    payment_terms: Dict(String, PaymentTermsRecord),
    payment_terms_owner_ids: Dict(String, Bool),
    payment_terms_by_owner_id: Dict(String, String),
    deleted_payment_terms_ids: Dict(String, Bool),
    store_credit_accounts: Dict(String, StoreCreditAccountRecord),
    store_credit_account_transactions: Dict(
      String,
      StoreCreditAccountTransactionRecord,
    ),
    customer_account_pages: Dict(String, CustomerAccountPageRecord),
    customer_account_page_order: List(String),
    customer_data_erasure_requests: Dict(
      String,
      CustomerDataErasureRequestRecord,
    ),
    merged_customer_ids: Dict(String, String),
    customer_merge_requests: Dict(String, CustomerMergeRequestRecord),
    segments: Dict(String, SegmentRecord),
    segment_order: List(String),
    deleted_segment_ids: Dict(String, Bool),
    segment_root_payloads: Dict(String, StorePropertyValue),
    customer_segment_members_queries: Dict(
      String,
      CustomerSegmentMembersQueryRecord,
    ),
    customer_segment_members_query_order: List(String),
    available_locales: List(LocaleRecord),
    shop_locales: Dict(String, ShopLocaleRecord),
    translations: Dict(String, TranslationRecord),
  )
}

/// Mutations the proxy has staged but not yet committed upstream.
/// Mirrors the staged slices of `StateSnapshot`.
pub type StagedState {
  StagedState(
    products: Dict(String, ProductRecord),
    product_order: List(String),
    deleted_product_ids: Dict(String, Bool),
    product_count: Option(Int),
    product_variants: Dict(String, ProductVariantRecord),
    product_variant_order: List(String),
    product_variant_count: Option(Int),
    product_options: Dict(String, ProductOptionRecord),
    product_operations: Dict(String, ProductOperationRecord),
    selling_plan_groups: Dict(String, SellingPlanGroupRecord),
    selling_plan_group_order: List(String),
    deleted_selling_plan_group_ids: Dict(String, Bool),
    markets: Dict(String, MarketRecord),
    market_order: List(String),
    deleted_market_ids: Dict(String, Bool),
    catalogs: Dict(String, CatalogRecord),
    catalog_order: List(String),
    deleted_catalog_ids: Dict(String, Bool),
    price_lists: Dict(String, PriceListRecord),
    price_list_order: List(String),
    deleted_price_list_ids: Dict(String, Bool),
    web_presences: Dict(String, WebPresenceRecord),
    web_presence_order: List(String),
    deleted_web_presence_ids: Dict(String, Bool),
    market_localizations: Dict(String, MarketLocalizationRecord),
    markets_root_payloads: Dict(String, CapturedJsonValue),
    product_media: Dict(String, List(ProductMediaRecord)),
    files: Dict(String, FileRecord),
    file_order: List(String),
    deleted_file_ids: Dict(String, Bool),
    collections: Dict(String, CollectionRecord),
    collection_order: List(String),
    product_collections: Dict(String, ProductCollectionRecord),
    staged_product_collection_families: Dict(String, Bool),
    deleted_collection_ids: Dict(String, Bool),
    publications: Dict(String, PublicationRecord),
    publication_order: List(String),
    deleted_publication_ids: Dict(String, Bool),
    product_feeds: Dict(String, ProductFeedRecord),
    product_feed_order: List(String),
    deleted_product_feed_ids: Dict(String, Bool),
    product_resource_feedback: Dict(String, ProductResourceFeedbackRecord),
    shop_resource_feedback: Dict(String, ShopResourceFeedbackRecord),
    abandoned_checkouts: Dict(String, AbandonedCheckoutRecord),
    abandoned_checkout_order: List(String),
    abandonments: Dict(String, AbandonmentRecord),
    abandonment_order: List(String),
    draft_orders: Dict(String, DraftOrderRecord),
    draft_order_order: List(String),
    deleted_draft_order_ids: Dict(String, Bool),
    draft_order_variant_catalog: Dict(String, DraftOrderVariantCatalogRecord),
    orders: Dict(String, OrderRecord),
    order_order: List(String),
    deleted_order_ids: Dict(String, Bool),
    order_mandate_payments: Dict(String, OrderMandatePaymentRecord),
    inventory_transfers: Dict(String, InventoryTransferRecord),
    inventory_transfer_order: List(String),
    deleted_inventory_transfer_ids: Dict(String, Bool),
    inventory_shipments: Dict(String, InventoryShipmentRecord),
    inventory_shipment_order: List(String),
    deleted_inventory_shipment_ids: Dict(String, Bool),
    carrier_services: Dict(String, CarrierServiceRecord),
    carrier_service_order: List(String),
    deleted_carrier_service_ids: Dict(String, Bool),
    fulfillment_services: Dict(String, FulfillmentServiceRecord),
    fulfillment_service_order: List(String),
    deleted_fulfillment_service_ids: Dict(String, Bool),
    fulfillments: Dict(String, FulfillmentRecord),
    fulfillment_order: List(String),
    fulfillment_orders: Dict(String, FulfillmentOrderRecord),
    fulfillment_order_order: List(String),
    shipping_orders: Dict(String, ShippingOrderRecord),
    reverse_fulfillment_orders: Dict(String, ReverseFulfillmentOrderRecord),
    reverse_fulfillment_order_order: List(String),
    reverse_deliveries: Dict(String, ReverseDeliveryRecord),
    reverse_delivery_order: List(String),
    calculated_orders: Dict(String, CalculatedOrderRecord),
    delivery_profiles: Dict(String, DeliveryProfileRecord),
    delivery_profile_order: List(String),
    deleted_delivery_profile_ids: Dict(String, Bool),
    shipping_packages: Dict(String, ShippingPackageRecord),
    shipping_package_order: List(String),
    deleted_shipping_package_ids: Dict(String, Bool),
    backup_region: Option(BackupRegionRecord),
    admin_platform_generic_nodes: Dict(String, AdminPlatformGenericNodeRecord),
    admin_platform_taxonomy_categories: Dict(
      String,
      AdminPlatformTaxonomyCategoryRecord,
    ),
    admin_platform_taxonomy_category_order: List(String),
    admin_platform_flow_signatures: Dict(
      String,
      AdminPlatformFlowSignatureRecord,
    ),
    admin_platform_flow_signature_order: List(String),
    admin_platform_flow_triggers: Dict(String, AdminPlatformFlowTriggerRecord),
    admin_platform_flow_trigger_order: List(String),
    shop: Option(ShopRecord),
    b2b_companies: Dict(String, B2BCompanyRecord),
    b2b_company_order: List(String),
    deleted_b2b_company_ids: Dict(String, Bool),
    b2b_company_contacts: Dict(String, B2BCompanyContactRecord),
    b2b_company_contact_order: List(String),
    deleted_b2b_company_contact_ids: Dict(String, Bool),
    b2b_company_contact_roles: Dict(String, B2BCompanyContactRoleRecord),
    b2b_company_contact_role_order: List(String),
    deleted_b2b_company_contact_role_ids: Dict(String, Bool),
    b2b_company_locations: Dict(String, B2BCompanyLocationRecord),
    b2b_company_location_order: List(String),
    deleted_b2b_company_location_ids: Dict(String, Bool),
    store_property_locations: Dict(String, StorePropertyRecord),
    store_property_location_order: List(String),
    deleted_store_property_location_ids: Dict(String, Bool),
    business_entities: Dict(String, StorePropertyRecord),
    business_entity_order: List(String),
    publishables: Dict(String, StorePropertyRecord),
    publishable_order: List(String),
    store_property_mutation_payloads: Dict(
      String,
      StorePropertyMutationPayloadRecord,
    ),
    product_metafields: Dict(String, ProductMetafieldRecord),
    metafield_definitions: Dict(String, MetafieldDefinitionRecord),
    deleted_metafield_definition_ids: Dict(String, Bool),
    saved_searches: Dict(String, SavedSearchRecord),
    saved_search_order: List(String),
    deleted_saved_search_ids: Dict(String, Bool),
    webhook_subscriptions: Dict(String, WebhookSubscriptionRecord),
    webhook_subscription_order: List(String),
    deleted_webhook_subscription_ids: Dict(String, Bool),
    online_store_content: Dict(String, OnlineStoreContentRecord),
    online_store_content_order: List(String),
    deleted_online_store_content_ids: Dict(String, Bool),
    online_store_integrations: Dict(String, OnlineStoreIntegrationRecord),
    online_store_integration_order: List(String),
    deleted_online_store_integration_ids: Dict(String, Bool),
    apps: Dict(String, AppRecord),
    app_order: List(String),
    app_installations: Dict(String, AppInstallationRecord),
    app_installation_order: List(String),
    current_installation_id: Option(String),
    app_subscriptions: Dict(String, AppSubscriptionRecord),
    app_subscription_order: List(String),
    app_subscription_line_items: Dict(String, AppSubscriptionLineItemRecord),
    app_subscription_line_item_order: List(String),
    app_one_time_purchases: Dict(String, AppOneTimePurchaseRecord),
    app_one_time_purchase_order: List(String),
    app_usage_records: Dict(String, AppUsageRecord),
    app_usage_record_order: List(String),
    delegated_access_tokens: Dict(String, DelegatedAccessTokenRecord),
    delegated_access_token_order: List(String),
    shopify_functions: Dict(String, ShopifyFunctionRecord),
    shopify_function_order: List(String),
    bulk_operations: Dict(String, BulkOperationRecord),
    bulk_operation_order: List(String),
    staged_upload_contents: Dict(String, String),
    metaobject_definitions: Dict(String, MetaobjectDefinitionRecord),
    metaobject_definition_order: List(String),
    deleted_metaobject_definition_ids: Dict(String, Bool),
    metaobjects: Dict(String, MetaobjectRecord),
    metaobject_order: List(String),
    deleted_metaobject_ids: Dict(String, Bool),
    marketing_activities: Dict(String, MarketingRecord),
    marketing_activity_order: List(String),
    marketing_events: Dict(String, MarketingRecord),
    marketing_event_order: List(String),
    marketing_engagements: Dict(String, MarketingEngagementRecord),
    marketing_engagement_order: List(String),
    deleted_marketing_activity_ids: Dict(String, Bool),
    deleted_marketing_event_ids: Dict(String, Bool),
    deleted_marketing_engagement_ids: Dict(String, Bool),
    marketing_delete_all_external_in_flight: Bool,
    validations: Dict(String, ValidationRecord),
    validation_order: List(String),
    deleted_validation_ids: Dict(String, Bool),
    cart_transforms: Dict(String, CartTransformRecord),
    cart_transform_order: List(String),
    deleted_cart_transform_ids: Dict(String, Bool),
    tax_app_configuration: Option(TaxAppConfigurationRecord),
    discounts: Dict(String, DiscountRecord),
    discount_order: List(String),
    deleted_discount_ids: Dict(String, Bool),
    discount_bulk_operations: Dict(String, DiscountBulkOperationRecord),
    gift_cards: Dict(String, GiftCardRecord),
    gift_card_order: List(String),
    gift_card_configuration: Option(GiftCardConfigurationRecord),
    customers: Dict(String, CustomerRecord),
    customer_order: List(String),
    deleted_customer_ids: Dict(String, Bool),
    customer_addresses: Dict(String, CustomerAddressRecord),
    customer_address_order: List(String),
    deleted_customer_address_ids: Dict(String, Bool),
    customer_order_summaries: Dict(String, CustomerOrderSummaryRecord),
    customer_order_connection_page_infos: Dict(
      String,
      CustomerCatalogPageInfoRecord,
    ),
    customer_event_summaries: Dict(String, CustomerEventSummaryRecord),
    customer_event_connection_page_infos: Dict(
      String,
      CustomerCatalogPageInfoRecord,
    ),
    customer_last_orders: Dict(String, CustomerOrderSummaryRecord),
    customer_metafields: Dict(String, CustomerMetafieldRecord),
    customer_payment_methods: Dict(String, CustomerPaymentMethodRecord),
    customer_payment_method_update_urls: Dict(
      String,
      CustomerPaymentMethodUpdateUrlRecord,
    ),
    deleted_customer_payment_method_ids: Dict(String, Bool),
    payment_reminder_sends: Dict(String, PaymentReminderSendRecord),
    payment_customizations: Dict(String, PaymentCustomizationRecord),
    payment_customization_order: List(String),
    deleted_payment_customization_ids: Dict(String, Bool),
    payment_terms: Dict(String, PaymentTermsRecord),
    payment_terms_owner_ids: Dict(String, Bool),
    payment_terms_by_owner_id: Dict(String, String),
    deleted_payment_terms_ids: Dict(String, Bool),
    store_credit_accounts: Dict(String, StoreCreditAccountRecord),
    store_credit_account_transactions: Dict(
      String,
      StoreCreditAccountTransactionRecord,
    ),
    customer_account_pages: Dict(String, CustomerAccountPageRecord),
    customer_account_page_order: List(String),
    customer_data_erasure_requests: Dict(
      String,
      CustomerDataErasureRequestRecord,
    ),
    merged_customer_ids: Dict(String, String),
    customer_merge_requests: Dict(String, CustomerMergeRequestRecord),
    segments: Dict(String, SegmentRecord),
    segment_order: List(String),
    deleted_segment_ids: Dict(String, Bool),
    customer_segment_members_queries: Dict(
      String,
      CustomerSegmentMembersQueryRecord,
    ),
    customer_segment_members_query_order: List(String),
    shop_locales: Dict(String, ShopLocaleRecord),
    deleted_shop_locales: Dict(String, Bool),
    translations: Dict(String, TranslationRecord),
    deleted_translations: Dict(String, Bool),
  )
}

/// Operation type a mutation log entry was recorded for. Mirrors the
/// `'query' | 'mutation'` union in TS.
pub type OperationType {
  Query
  Mutation
}

/// Status the mutation log records each entry under. Mirrors
/// `'staged' | 'proxied' | 'committed' | 'failed'`.
pub type EntryStatus {
  Staged
  Proxied
  Committed
  Failed
}

/// Capability metadata recorded alongside each mutation log entry.
/// Mirrors `MutationLogInterpretedMetadata['capability']`.
pub type Capability {
  Capability(operation_name: Option(String), domain: String, execution: String)
}

/// Slim port of `MutationLogInterpretedMetadata`. Only the fields the
/// Gleam port currently writes are modelled. The optional pieces
/// (`registeredOperation`, `safety`, `bulkOperationImport`) are deferred
/// until their producers port.
pub type InterpretedMetadata {
  InterpretedMetadata(
    operation_type: OperationType,
    operation_name: Option(String),
    root_fields: List(String),
    primary_root_field: Option(String),
    capability: Capability,
  )
}

/// Slim port of `MutationLogEntry`. `requestBody` and the optional
/// fields are deferred to the next pass that produces them.
pub type MutationLogEntry {
  MutationLogEntry(
    id: String,
    received_at: String,
    operation_name: Option(String),
    path: String,
    query: String,
    variables: Dict(String, root_field.ResolvedValue),
    staged_resource_ids: List(String),
    status: EntryStatus,
    interpreted: InterpretedMetadata,
    notes: Option(String),
  )
}

/// Long-lived runtime store. The TS class also tracks lagged search
/// caches and a handful of cross-domain side tables; those will land
/// when their domains do.
pub type Store {
  Store(
    base_state: BaseState,
    staged_state: StagedState,
    mutation_log: List(MutationLogEntry),
  )
}
/// An empty `BaseState`. Equivalent to `cloneSnapshot(EMPTY_SNAPSHOT)`
/// projected onto the slices we ship.
