//// Public entrypoint for the in-memory state store. The data types stay
//// available from this module while entity-specific operation bodies live in
//// `state/store/*` submodules.

import shopify_draft_proxy/state/store/admin_platform
import shopify_draft_proxy/state/store/apps
import shopify_draft_proxy/state/store/b2b
import shopify_draft_proxy/state/store/bulk_operations
import shopify_draft_proxy/state/store/commerce
import shopify_draft_proxy/state/store/content
import shopify_draft_proxy/state/store/core
import shopify_draft_proxy/state/store/customers
import shopify_draft_proxy/state/store/discounts
import shopify_draft_proxy/state/store/fulfillments
import shopify_draft_proxy/state/store/functions
import shopify_draft_proxy/state/store/gift_cards
import shopify_draft_proxy/state/store/marketing
import shopify_draft_proxy/state/store/markets
import shopify_draft_proxy/state/store/metafields
import shopify_draft_proxy/state/store/metaobjects
import shopify_draft_proxy/state/store/orders
import shopify_draft_proxy/state/store/products
import shopify_draft_proxy/state/store/segments
import shopify_draft_proxy/state/store/shared
import shopify_draft_proxy/state/store/types as store_types

pub type BaseState =
  store_types.BaseState

pub type StagedState =
  store_types.StagedState

pub type OperationType =
  store_types.OperationType

pub type EntryStatus =
  store_types.EntryStatus

pub type Capability =
  store_types.Capability

pub type InterpretedMetadata =
  store_types.InterpretedMetadata

pub type MutationLogEntry =
  store_types.MutationLogEntry

pub type Store =
  store_types.Store

pub const empty_base_state = core.empty_base_state

pub const empty_staged_state = core.empty_staged_state

pub const new = core.new

pub const reset = core.reset

pub const upsert_base_abandoned_checkouts = orders.upsert_base_abandoned_checkouts

pub const upsert_base_abandonments = orders.upsert_base_abandonments

pub const upsert_base_draft_orders = orders.upsert_base_draft_orders

pub const upsert_base_draft_order_variant_catalog = orders.upsert_base_draft_order_variant_catalog

pub const upsert_base_orders = orders.upsert_base_orders

pub const stage_order = orders.stage_order

pub const stage_draft_order = orders.stage_draft_order

pub const delete_staged_draft_order = orders.delete_staged_draft_order

pub const delete_staged_order = orders.delete_staged_order

pub const get_abandoned_checkout_by_id = orders.get_abandoned_checkout_by_id

pub const get_draft_order_by_id = orders.get_draft_order_by_id

pub const get_order_by_id = orders.get_order_by_id

pub const list_effective_draft_orders = orders.list_effective_draft_orders

pub const list_effective_orders = orders.list_effective_orders

pub const get_order_mandate_payment = orders.get_order_mandate_payment

pub const upsert_staged_order_mandate_payment = orders.upsert_staged_order_mandate_payment

pub const get_draft_order_variant_catalog_by_id = orders.get_draft_order_variant_catalog_by_id

pub const get_abandonment_by_id = orders.get_abandonment_by_id

pub const get_abandonment_by_abandoned_checkout_id = orders.get_abandonment_by_abandoned_checkout_id

pub const list_effective_abandoned_checkouts = orders.list_effective_abandoned_checkouts

pub const list_effective_abandonments = orders.list_effective_abandonments

pub const unassociate_abandoned_checkouts_from_order = orders.unassociate_abandoned_checkouts_from_order

pub const stage_abandonment_delivery_activity = orders.stage_abandonment_delivery_activity

pub const upsert_base_products = products.upsert_base_products

pub const set_base_product_count = products.set_base_product_count

pub const set_staged_product_count = products.set_staged_product_count

pub const upsert_staged_product = products.upsert_staged_product

pub const delete_staged_product = products.delete_staged_product

pub const replace_base_media_for_product = products.replace_base_media_for_product

pub const replace_staged_media_for_product = products.replace_staged_media_for_product

pub const get_effective_media_by_product_id = products.get_effective_media_by_product_id

pub const remove_media_ids_from_product_variants = products.remove_media_ids_from_product_variants

pub const remove_media_ids_from_variants_for_products = products.remove_media_ids_from_variants_for_products

pub const upsert_base_files = products.upsert_base_files

pub const upsert_staged_files = products.upsert_staged_files

pub const delete_staged_files = products.delete_staged_files

pub const has_effective_file_by_id = products.has_effective_file_by_id

pub const get_effective_file_by_id = products.get_effective_file_by_id

pub const list_effective_files = products.list_effective_files

pub const list_effective_product_media = products.list_effective_product_media

pub const get_effective_product_by_id = products.get_effective_product_by_id

pub const get_effective_product_by_handle = products.get_effective_product_by_handle

pub const list_effective_products = products.list_effective_products

pub const get_effective_product_count = products.get_effective_product_count

pub const upsert_base_collections = commerce.upsert_base_collections

pub const upsert_staged_collections = commerce.upsert_staged_collections

pub const delete_staged_collection = commerce.delete_staged_collection

pub const upsert_base_locations = commerce.upsert_base_locations

pub const get_effective_location_by_id = commerce.get_effective_location_by_id

pub const list_effective_locations = commerce.list_effective_locations

pub const upsert_base_publications = commerce.upsert_base_publications

pub const upsert_base_channels = commerce.upsert_base_channels

pub const upsert_staged_publication = commerce.upsert_staged_publication

pub const delete_staged_publication = commerce.delete_staged_publication

pub const get_effective_publication_by_id = commerce.get_effective_publication_by_id

pub const list_effective_publications = commerce.list_effective_publications

pub const get_effective_channel_by_id = commerce.get_effective_channel_by_id

pub const list_effective_channels = commerce.list_effective_channels

pub const upsert_base_product_feeds = commerce.upsert_base_product_feeds

pub const upsert_staged_product_feed = commerce.upsert_staged_product_feed

pub const delete_staged_product_feed = commerce.delete_staged_product_feed

pub const get_effective_product_feed_by_id = commerce.get_effective_product_feed_by_id

pub const list_effective_product_feeds = commerce.list_effective_product_feeds

pub const upsert_base_product_resource_feedback = commerce.upsert_base_product_resource_feedback

pub const upsert_staged_product_resource_feedback = commerce.upsert_staged_product_resource_feedback

pub const get_effective_product_resource_feedback = commerce.get_effective_product_resource_feedback

pub const upsert_staged_shop_resource_feedback = commerce.upsert_staged_shop_resource_feedback

pub const upsert_base_inventory_transfers = fulfillments.upsert_base_inventory_transfers

pub const upsert_staged_inventory_transfer = fulfillments.upsert_staged_inventory_transfer

pub const delete_staged_inventory_transfer = fulfillments.delete_staged_inventory_transfer

pub const get_effective_inventory_transfer_by_id = fulfillments.get_effective_inventory_transfer_by_id

pub const list_effective_inventory_transfers = fulfillments.list_effective_inventory_transfers

pub const upsert_base_inventory_shipments = fulfillments.upsert_base_inventory_shipments

pub const upsert_staged_inventory_shipment = fulfillments.upsert_staged_inventory_shipment

pub const delete_staged_inventory_shipment = fulfillments.delete_staged_inventory_shipment

pub const get_effective_inventory_shipment_by_id = fulfillments.get_effective_inventory_shipment_by_id

pub const list_effective_inventory_shipments = fulfillments.list_effective_inventory_shipments

pub const upsert_base_carrier_services = fulfillments.upsert_base_carrier_services

pub const stage_create_carrier_service = fulfillments.stage_create_carrier_service

pub const stage_update_carrier_service = fulfillments.stage_update_carrier_service

pub const delete_staged_carrier_service = fulfillments.delete_staged_carrier_service

pub const get_effective_carrier_service_by_id = fulfillments.get_effective_carrier_service_by_id

pub const list_effective_carrier_services = fulfillments.list_effective_carrier_services

pub const upsert_base_fulfillment_services = fulfillments.upsert_base_fulfillment_services

pub const stage_create_fulfillment_service = fulfillments.stage_create_fulfillment_service

pub const stage_update_fulfillment_service = fulfillments.stage_update_fulfillment_service

pub const delete_staged_fulfillment_service = fulfillments.delete_staged_fulfillment_service

pub const get_effective_fulfillment_service_by_id = fulfillments.get_effective_fulfillment_service_by_id

pub const list_effective_fulfillment_services = fulfillments.list_effective_fulfillment_services

pub const upsert_base_fulfillments = fulfillments.upsert_base_fulfillments

pub const stage_upsert_fulfillment = fulfillments.stage_upsert_fulfillment

pub const upsert_base_fulfillment_orders = fulfillments.upsert_base_fulfillment_orders

pub const stage_upsert_fulfillment_order = fulfillments.stage_upsert_fulfillment_order

pub const upsert_base_shipping_orders = fulfillments.upsert_base_shipping_orders

pub const stage_upsert_shipping_order = fulfillments.stage_upsert_shipping_order

pub const upsert_base_reverse_fulfillment_orders = fulfillments.upsert_base_reverse_fulfillment_orders

pub const stage_upsert_reverse_fulfillment_order = fulfillments.stage_upsert_reverse_fulfillment_order

pub const get_effective_reverse_fulfillment_order_by_id = fulfillments.get_effective_reverse_fulfillment_order_by_id

pub const list_effective_reverse_fulfillment_orders = fulfillments.list_effective_reverse_fulfillment_orders

pub const upsert_base_reverse_deliveries = fulfillments.upsert_base_reverse_deliveries

pub const stage_upsert_reverse_delivery = fulfillments.stage_upsert_reverse_delivery

pub const get_effective_reverse_delivery_by_id = fulfillments.get_effective_reverse_delivery_by_id

pub const list_effective_reverse_deliveries = fulfillments.list_effective_reverse_deliveries

pub const upsert_base_calculated_orders = fulfillments.upsert_base_calculated_orders

pub const stage_upsert_calculated_order = fulfillments.stage_upsert_calculated_order

pub const get_effective_calculated_order_by_id = fulfillments.get_effective_calculated_order_by_id

pub const get_effective_fulfillment_by_id = fulfillments.get_effective_fulfillment_by_id

pub const get_effective_fulfillment_order_by_id = fulfillments.get_effective_fulfillment_order_by_id

pub const get_effective_shipping_order_by_id = fulfillments.get_effective_shipping_order_by_id

pub const list_effective_fulfillments = fulfillments.list_effective_fulfillments

pub const list_effective_fulfillment_orders = fulfillments.list_effective_fulfillment_orders

pub const upsert_base_delivery_profiles = fulfillments.upsert_base_delivery_profiles

pub const stage_create_delivery_profile = fulfillments.stage_create_delivery_profile

pub const stage_update_delivery_profile = fulfillments.stage_update_delivery_profile

pub const delete_staged_delivery_profile = fulfillments.delete_staged_delivery_profile

pub const get_effective_delivery_profile_by_id = fulfillments.get_effective_delivery_profile_by_id

pub const list_effective_delivery_profiles = fulfillments.list_effective_delivery_profiles

pub const has_staged_delivery_profiles = fulfillments.has_staged_delivery_profiles

pub const upsert_base_shipping_packages = fulfillments.upsert_base_shipping_packages

pub const stage_update_shipping_package = fulfillments.stage_update_shipping_package

pub const delete_staged_shipping_package = fulfillments.delete_staged_shipping_package

pub const get_effective_shipping_package_by_id = fulfillments.get_effective_shipping_package_by_id

pub const list_effective_shipping_packages = fulfillments.list_effective_shipping_packages

pub const replace_base_products_for_collection = products.replace_base_products_for_collection

pub const upsert_base_product_collections = products.upsert_base_product_collections

pub const upsert_staged_product_collections = products.upsert_staged_product_collections

pub const replace_staged_collections_for_product = products.replace_staged_collections_for_product

pub const get_effective_collection_by_id = products.get_effective_collection_by_id

pub const get_effective_collection_by_handle = products.get_effective_collection_by_handle

pub const list_effective_collections = products.list_effective_collections

pub const list_effective_products_for_collection = products.list_effective_products_for_collection

pub const list_effective_collections_for_product = products.list_effective_collections_for_product

pub const upsert_base_product_variants = products.upsert_base_product_variants

pub const set_base_product_variant_count = products.set_base_product_variant_count

pub const set_staged_product_variant_count = products.set_staged_product_variant_count

pub const upsert_staged_product_variant = products.upsert_staged_product_variant

pub const replace_staged_variants_for_product = products.replace_staged_variants_for_product

pub const get_base_variants_by_product_id = products.get_base_variants_by_product_id

pub const get_effective_variants_by_product_id = products.get_effective_variants_by_product_id

pub const get_effective_variant_by_id = products.get_effective_variant_by_id

pub const find_effective_variant_by_inventory_item_id = products.find_effective_variant_by_inventory_item_id

pub const find_effective_inventory_level_by_id = products.find_effective_inventory_level_by_id

pub const list_effective_product_variants = products.list_effective_product_variants

pub const get_effective_product_variant_count = products.get_effective_product_variant_count

pub const replace_base_options_for_product = products.replace_base_options_for_product

pub const replace_staged_options_for_product = products.replace_staged_options_for_product

pub const get_effective_options_by_product_id = products.get_effective_options_by_product_id

pub const get_effective_product_option_by_id = products.get_effective_product_option_by_id

pub const get_effective_product_option_value_by_id = products.get_effective_product_option_value_by_id

pub const stage_product_operation = products.stage_product_operation

pub const upsert_base_product_operations = products.upsert_base_product_operations

pub const get_effective_product_operation_by_id = products.get_effective_product_operation_by_id

pub const upsert_base_selling_plan_groups = products.upsert_base_selling_plan_groups

pub const upsert_staged_selling_plan_group = products.upsert_staged_selling_plan_group

pub const delete_staged_selling_plan_group = products.delete_staged_selling_plan_group

pub const get_effective_selling_plan_group_by_id = products.get_effective_selling_plan_group_by_id

pub const list_effective_selling_plan_groups = products.list_effective_selling_plan_groups

pub const upsert_base_markets = markets.upsert_base_markets

pub const get_effective_market_by_id = markets.get_effective_market_by_id

pub const list_effective_markets = markets.list_effective_markets

pub const upsert_staged_market_localizations = markets.upsert_staged_market_localizations

pub const delete_staged_market_localizations = markets.delete_staged_market_localizations

pub const list_effective_market_localizations = markets.list_effective_market_localizations

pub const remove_staged_market_localizations = markets.remove_staged_market_localizations

pub const upsert_staged_market = markets.upsert_staged_market

pub const delete_staged_market = markets.delete_staged_market

pub const upsert_base_catalogs = markets.upsert_base_catalogs

pub const get_effective_catalog_by_id = markets.get_effective_catalog_by_id

pub const list_effective_catalogs = markets.list_effective_catalogs

pub const upsert_staged_catalog = markets.upsert_staged_catalog

pub const delete_staged_catalog = markets.delete_staged_catalog

pub const upsert_base_price_lists = markets.upsert_base_price_lists

pub const get_effective_price_list_by_id = markets.get_effective_price_list_by_id

pub const list_effective_price_lists = markets.list_effective_price_lists

pub const upsert_staged_price_list = markets.upsert_staged_price_list

pub const delete_staged_price_list = markets.delete_staged_price_list

pub const clear_price_list_fixed_prices = markets.clear_price_list_fixed_prices

pub const upsert_base_web_presences = markets.upsert_base_web_presences

pub const get_effective_web_presence_by_id = markets.get_effective_web_presence_by_id

pub const list_effective_web_presences = markets.list_effective_web_presences

pub const upsert_staged_web_presence = markets.upsert_staged_web_presence

pub const delete_staged_web_presence = markets.delete_staged_web_presence

pub const upsert_base_markets_root_payload = markets.upsert_base_markets_root_payload

pub const get_effective_markets_root_payload = markets.get_effective_markets_root_payload

pub const list_effective_selling_plan_groups_for_product = products.list_effective_selling_plan_groups_for_product

pub const list_effective_selling_plan_groups_visible_for_product = products.list_effective_selling_plan_groups_visible_for_product

pub const list_effective_selling_plan_groups_for_product_variant = products.list_effective_selling_plan_groups_for_product_variant

pub const list_effective_selling_plan_groups_visible_for_product_variant = products.list_effective_selling_plan_groups_visible_for_product_variant

pub const upsert_base_backup_region = admin_platform.upsert_base_backup_region

pub const stage_backup_region = admin_platform.stage_backup_region

pub const get_effective_backup_region = admin_platform.get_effective_backup_region

pub const upsert_base_admin_platform_generic_nodes = admin_platform.upsert_base_admin_platform_generic_nodes

pub const upsert_staged_admin_platform_generic_nodes = admin_platform.upsert_staged_admin_platform_generic_nodes

pub const get_effective_admin_platform_generic_node_by_id = admin_platform.get_effective_admin_platform_generic_node_by_id

pub const upsert_base_admin_platform_taxonomy_categories = admin_platform.upsert_base_admin_platform_taxonomy_categories

pub const get_effective_admin_platform_taxonomy_category_by_id = admin_platform.get_effective_admin_platform_taxonomy_category_by_id

pub const list_effective_admin_platform_taxonomy_categories = admin_platform.list_effective_admin_platform_taxonomy_categories

pub const upsert_base_shop = admin_platform.upsert_base_shop

pub const stage_shop = admin_platform.stage_shop

pub const get_effective_shop = admin_platform.get_effective_shop

pub const shop_sells_subscriptions = admin_platform.shop_sells_subscriptions

pub const shop_discounts_by_market_enabled = admin_platform.shop_discounts_by_market_enabled

pub const payment_gateway_by_id = admin_platform.payment_gateway_by_id

pub const set_shop_payment_gateways = admin_platform.set_shop_payment_gateways

pub const set_shop_sells_subscriptions = admin_platform.set_shop_sells_subscriptions

pub const set_shop_discounts_by_market_enabled = admin_platform.set_shop_discounts_by_market_enabled

pub const upsert_base_b2b_company = b2b.upsert_base_b2b_company

pub const upsert_staged_b2b_company = b2b.upsert_staged_b2b_company

pub const delete_staged_b2b_company = b2b.delete_staged_b2b_company

pub const get_effective_b2b_company_by_id = b2b.get_effective_b2b_company_by_id

pub const list_effective_b2b_companies = b2b.list_effective_b2b_companies

pub const upsert_base_b2b_company_contact = b2b.upsert_base_b2b_company_contact

pub const upsert_staged_b2b_company_contact = b2b.upsert_staged_b2b_company_contact

pub const delete_staged_b2b_company_contact = b2b.delete_staged_b2b_company_contact

pub const get_effective_b2b_company_contact_by_id = b2b.get_effective_b2b_company_contact_by_id

pub const list_effective_b2b_company_contacts = b2b.list_effective_b2b_company_contacts

pub const upsert_base_b2b_company_contact_role = b2b.upsert_base_b2b_company_contact_role

pub const upsert_staged_b2b_company_contact_role = b2b.upsert_staged_b2b_company_contact_role

pub const delete_staged_b2b_company_contact_role = b2b.delete_staged_b2b_company_contact_role

pub const get_effective_b2b_company_contact_role_by_id = b2b.get_effective_b2b_company_contact_role_by_id

pub const upsert_base_b2b_company_location = b2b.upsert_base_b2b_company_location

pub const upsert_staged_b2b_company_location = b2b.upsert_staged_b2b_company_location

pub const delete_staged_b2b_company_location = b2b.delete_staged_b2b_company_location

pub const get_effective_b2b_company_location_by_id = b2b.get_effective_b2b_company_location_by_id

pub const list_effective_b2b_company_locations = b2b.list_effective_b2b_company_locations

pub const upsert_base_store_property_location = b2b.upsert_base_store_property_location

pub const upsert_staged_store_property_location = b2b.upsert_staged_store_property_location

pub const delete_staged_store_property_location = b2b.delete_staged_store_property_location

pub const get_effective_store_property_location_by_id = b2b.get_effective_store_property_location_by_id

pub const list_effective_store_property_locations = b2b.list_effective_store_property_locations

pub const upsert_base_business_entity = b2b.upsert_base_business_entity

pub const get_business_entity_by_id = b2b.get_business_entity_by_id

pub const list_effective_business_entities = b2b.list_effective_business_entities

pub const upsert_base_publishable = b2b.upsert_base_publishable

pub const upsert_staged_publishable = b2b.upsert_staged_publishable

pub const get_effective_publishable_by_id = b2b.get_effective_publishable_by_id

pub const upsert_base_store_property_mutation_payload = b2b.upsert_base_store_property_mutation_payload

pub const get_store_property_mutation_payload = b2b.get_store_property_mutation_payload

pub const replace_base_metafields_for_owner = metafields.replace_base_metafields_for_owner

pub const replace_staged_metafields_for_owner = metafields.replace_staged_metafields_for_owner

pub const upsert_base_metafield_definitions = metafields.upsert_base_metafield_definitions

pub const upsert_staged_metafield_definitions = metafields.upsert_staged_metafield_definitions

pub const stage_delete_metafield_definition = metafields.stage_delete_metafield_definition

pub const delete_product_metafields_for_definition = metafields.delete_product_metafields_for_definition

pub const get_effective_metafields_by_owner_id = metafields.get_effective_metafields_by_owner_id

pub const find_effective_metafield_by_id = metafields.find_effective_metafield_by_id

pub const list_effective_metafield_definitions = metafields.list_effective_metafield_definitions

pub const get_effective_metafield_definition_by_id = metafields.get_effective_metafield_definition_by_id

pub const find_effective_metafield_definition = metafields.find_effective_metafield_definition

pub const stage_admin_platform_flow_signature = admin_platform.stage_admin_platform_flow_signature

pub const stage_admin_platform_flow_trigger = admin_platform.stage_admin_platform_flow_trigger

pub const upsert_base_saved_searches = content.upsert_base_saved_searches

pub const upsert_staged_saved_search = content.upsert_staged_saved_search

pub const delete_staged_saved_search = content.delete_staged_saved_search

pub const get_effective_saved_search_by_id = content.get_effective_saved_search_by_id

pub const list_effective_saved_searches = content.list_effective_saved_searches

pub const upsert_base_webhook_subscriptions = content.upsert_base_webhook_subscriptions

pub const upsert_staged_webhook_subscription = content.upsert_staged_webhook_subscription

pub const delete_staged_webhook_subscription = content.delete_staged_webhook_subscription

pub const get_effective_webhook_subscription_by_id = content.get_effective_webhook_subscription_by_id

pub const list_effective_webhook_subscriptions = content.list_effective_webhook_subscriptions

pub const upsert_base_online_store_content = content.upsert_base_online_store_content

pub const upsert_staged_online_store_content = content.upsert_staged_online_store_content

pub const delete_staged_online_store_content = content.delete_staged_online_store_content

pub const get_effective_online_store_content_by_id = content.get_effective_online_store_content_by_id

pub const list_effective_online_store_content = content.list_effective_online_store_content

pub const upsert_base_online_store_integrations = content.upsert_base_online_store_integrations

pub const upsert_staged_online_store_integration = content.upsert_staged_online_store_integration

pub const delete_staged_online_store_integration = content.delete_staged_online_store_integration

pub const get_effective_online_store_integration_by_id = content.get_effective_online_store_integration_by_id

pub const list_effective_online_store_integrations = content.list_effective_online_store_integrations

pub const upsert_base_app = apps.upsert_base_app

pub const stage_app = apps.stage_app

pub const get_effective_app_by_id = apps.get_effective_app_by_id

pub const find_effective_app_by_handle = apps.find_effective_app_by_handle

pub const find_effective_app_by_api_key = apps.find_effective_app_by_api_key

pub const list_effective_apps = apps.list_effective_apps

pub const upsert_base_app_installation = apps.upsert_base_app_installation

pub const stage_app_installation = apps.stage_app_installation

pub const get_effective_app_installation_by_id = apps.get_effective_app_installation_by_id

pub const get_current_app_installation = apps.get_current_app_installation

pub const stage_app_subscription = apps.stage_app_subscription

pub const get_effective_app_subscription_by_id = apps.get_effective_app_subscription_by_id

pub const stage_app_subscription_line_item = apps.stage_app_subscription_line_item

pub const get_effective_app_subscription_line_item_by_id = apps.get_effective_app_subscription_line_item_by_id

pub const stage_app_one_time_purchase = apps.stage_app_one_time_purchase

pub const get_effective_app_one_time_purchase_by_id = apps.get_effective_app_one_time_purchase_by_id

pub const stage_app_usage_record = apps.stage_app_usage_record

pub const get_effective_app_usage_record_by_id = apps.get_effective_app_usage_record_by_id

pub const list_effective_app_usage_records_for_line_item = apps.list_effective_app_usage_records_for_line_item

pub const stage_delegated_access_token = apps.stage_delegated_access_token

pub const find_delegated_access_token_by_hash = apps.find_delegated_access_token_by_hash

pub const destroy_delegated_access_token = apps.destroy_delegated_access_token

pub const upsert_base_shopify_functions = functions.upsert_base_shopify_functions

pub const upsert_staged_shopify_function = functions.upsert_staged_shopify_function

pub const get_effective_shopify_function_by_id = functions.get_effective_shopify_function_by_id

pub const list_effective_shopify_functions = functions.list_effective_shopify_functions

pub const upsert_base_marketing_activities = marketing.upsert_base_marketing_activities

pub const upsert_base_marketing_events = marketing.upsert_base_marketing_events

pub const upsert_base_marketing_channel_definitions = marketing.upsert_base_marketing_channel_definitions

pub const stage_marketing_activity = marketing.stage_marketing_activity

pub const stage_marketing_event = marketing.stage_marketing_event

pub const stage_delete_marketing_event = marketing.stage_delete_marketing_event

pub const stage_delete_marketing_activity = marketing.stage_delete_marketing_activity

pub const stage_delete_all_external_marketing_activities = marketing.stage_delete_all_external_marketing_activities

pub const stage_delete_all_external_marketing_activities_for_app = marketing.stage_delete_all_external_marketing_activities_for_app

pub const get_effective_marketing_activity_record_by_id = marketing.get_effective_marketing_activity_record_by_id

pub const get_effective_marketing_activity_record_by_id_for_app = marketing.get_effective_marketing_activity_record_by_id_for_app

pub const get_effective_marketing_event_record_by_id = marketing.get_effective_marketing_event_record_by_id

pub const get_effective_marketing_event_record_by_id_for_app = marketing.get_effective_marketing_event_record_by_id_for_app

pub const get_effective_marketing_activity_by_remote_id = marketing.get_effective_marketing_activity_by_remote_id

pub const get_effective_marketing_activity_by_remote_id_for_app = marketing.get_effective_marketing_activity_by_remote_id_for_app

pub const list_effective_marketing_activities = marketing.list_effective_marketing_activities

pub const list_effective_marketing_activities_for_app = marketing.list_effective_marketing_activities_for_app

pub const list_effective_marketing_events = marketing.list_effective_marketing_events

pub const list_effective_marketing_events_for_app = marketing.list_effective_marketing_events_for_app

pub const has_staged_marketing_records = marketing.has_staged_marketing_records

pub const has_marketing_delete_all_external_in_flight = marketing.has_marketing_delete_all_external_in_flight

pub const has_marketing_delete_all_external_in_flight_for_app = marketing.has_marketing_delete_all_external_in_flight_for_app

pub const stage_marketing_engagement = marketing.stage_marketing_engagement

pub const stage_delete_marketing_engagement = marketing.stage_delete_marketing_engagement

pub const stage_delete_marketing_engagements_by_channel_handle = marketing.stage_delete_marketing_engagements_by_channel_handle

pub const stage_delete_marketing_engagements_by_channel_handle_for_app = marketing.stage_delete_marketing_engagements_by_channel_handle_for_app

pub const stage_delete_all_channel_marketing_engagements = marketing.stage_delete_all_channel_marketing_engagements

pub const stage_delete_all_channel_marketing_engagements_for_app = marketing.stage_delete_all_channel_marketing_engagements_for_app

pub const list_effective_marketing_engagements = marketing.list_effective_marketing_engagements

pub const list_effective_marketing_engagements_for_app = marketing.list_effective_marketing_engagements_for_app

pub const marketing_record_visible_to_api_client = marketing.record_visible_to_api_client

pub const has_known_marketing_channel_handle = marketing.has_known_marketing_channel_handle

pub const has_known_marketing_channel_handle_for_app = marketing.has_known_marketing_channel_handle_for_app

pub const upsert_base_bulk_operations = bulk_operations.upsert_base_bulk_operations

pub const stage_bulk_operation = bulk_operations.stage_bulk_operation

pub const stage_bulk_operation_result = bulk_operations.stage_bulk_operation_result

pub const get_effective_bulk_operation_by_id = bulk_operations.get_effective_bulk_operation_by_id

pub const get_staged_bulk_operation_by_id = bulk_operations.get_staged_bulk_operation_by_id

pub const list_effective_bulk_operations = bulk_operations.list_effective_bulk_operations

pub const get_effective_bulk_operation_result_jsonl = bulk_operations.get_effective_bulk_operation_result_jsonl

pub const cancel_staged_bulk_operation = bulk_operations.cancel_staged_bulk_operation

pub const has_bulk_operations = bulk_operations.has_bulk_operations

pub const has_staged_bulk_operations = bulk_operations.has_staged_bulk_operations

pub const stage_staged_upload_content = bulk_operations.stage_staged_upload_content

pub const get_staged_upload_content = bulk_operations.get_staged_upload_content

pub const upsert_base_metaobject_definitions = metaobjects.upsert_base_metaobject_definitions

pub const upsert_staged_metaobject_definition = metaobjects.upsert_staged_metaobject_definition

pub const delete_staged_metaobject_definition = metaobjects.delete_staged_metaobject_definition

pub const get_effective_metaobject_definition_by_id = metaobjects.get_effective_metaobject_definition_by_id

pub const find_effective_metaobject_definition_by_type = metaobjects.find_effective_metaobject_definition_by_type

pub const list_effective_metaobject_definitions = metaobjects.list_effective_metaobject_definitions

pub const upsert_base_metaobjects = metaobjects.upsert_base_metaobjects

pub const upsert_staged_metaobject = metaobjects.upsert_staged_metaobject

pub const delete_staged_metaobject = metaobjects.delete_staged_metaobject

pub const get_effective_metaobject_by_id = metaobjects.get_effective_metaobject_by_id

pub const find_effective_metaobject_by_handle = metaobjects.find_effective_metaobject_by_handle

pub const list_effective_metaobjects = metaobjects.list_effective_metaobjects

pub const list_effective_metaobjects_by_type = metaobjects.list_effective_metaobjects_by_type

pub const has_effective_metaobjects = metaobjects.has_effective_metaobjects

pub const upsert_staged_validation = functions.upsert_staged_validation

pub const delete_staged_validation = functions.delete_staged_validation

pub const get_effective_validation_by_id = functions.get_effective_validation_by_id

pub const list_effective_validations = functions.list_effective_validations

pub const upsert_staged_cart_transform = functions.upsert_staged_cart_transform

pub const delete_staged_cart_transform = functions.delete_staged_cart_transform

pub const get_effective_cart_transform_by_id = functions.get_effective_cart_transform_by_id

pub const list_effective_cart_transforms = functions.list_effective_cart_transforms

pub const set_staged_tax_app_configuration = functions.set_staged_tax_app_configuration

pub const get_effective_tax_app_configuration = functions.get_effective_tax_app_configuration

pub const upsert_base_discounts = discounts.upsert_base_discounts

pub const stage_discount = discounts.stage_discount

pub const delete_staged_discount = discounts.delete_staged_discount

pub const stage_discount_bulk_operation = discounts.stage_discount_bulk_operation

pub const get_effective_discount_by_id = discounts.get_effective_discount_by_id

pub const list_effective_discounts = discounts.list_effective_discounts

pub const find_effective_discount_by_code = discounts.find_effective_discount_by_code

pub const upsert_base_gift_cards = gift_cards.upsert_base_gift_cards

pub const upsert_base_gift_card_configuration = gift_cards.upsert_base_gift_card_configuration

pub const stage_create_gift_card = gift_cards.stage_create_gift_card

pub const stage_update_gift_card = gift_cards.stage_update_gift_card

pub const get_effective_gift_card_by_id = gift_cards.get_effective_gift_card_by_id

pub const list_effective_gift_cards = gift_cards.list_effective_gift_cards

pub const set_staged_gift_card_configuration = gift_cards.set_staged_gift_card_configuration

pub const get_effective_gift_card_configuration = gift_cards.get_effective_gift_card_configuration

pub const upsert_base_customers = customers.upsert_base_customers

pub const set_base_customer_catalog_connection = customers.set_base_customer_catalog_connection

pub const get_base_customer_catalog_connection = customers.get_base_customer_catalog_connection

pub const stage_create_customer = customers.stage_create_customer

pub const stage_update_customer = customers.stage_update_customer

pub const stage_delete_customer = customers.stage_delete_customer

pub const get_effective_customer_by_id = customers.get_effective_customer_by_id

pub const list_effective_customers = customers.list_effective_customers

pub const upsert_base_customer_addresses = customers.upsert_base_customer_addresses

pub const stage_upsert_customer_address = customers.stage_upsert_customer_address

pub const stage_delete_customer_address = customers.stage_delete_customer_address

pub const get_effective_customer_address_by_id = customers.get_effective_customer_address_by_id

pub const list_effective_customer_addresses = customers.list_effective_customer_addresses

pub const upsert_base_customer_order_summaries = customers.upsert_base_customer_order_summaries

pub const stage_customer_order_summary = customers.stage_customer_order_summary

pub const get_effective_customer_order_summary_by_id = customers.get_effective_customer_order_summary_by_id

pub const list_effective_customer_order_summaries = customers.list_effective_customer_order_summaries

pub const set_base_customer_order_connection_page_info = customers.set_base_customer_order_connection_page_info

pub const get_effective_customer_order_connection_page_info = customers.get_effective_customer_order_connection_page_info

pub const upsert_base_customer_event_summaries = customers.upsert_base_customer_event_summaries

pub const list_effective_customer_event_summaries = customers.list_effective_customer_event_summaries

pub const set_base_customer_event_connection_page_info = customers.set_base_customer_event_connection_page_info

pub const get_effective_customer_event_connection_page_info = customers.get_effective_customer_event_connection_page_info

pub const upsert_base_customer_last_orders = customers.upsert_base_customer_last_orders

pub const get_effective_customer_last_order = customers.get_effective_customer_last_order

pub const stage_customer_metafields = customers.stage_customer_metafields

pub const get_effective_metafields_by_customer_id = customers.get_effective_metafields_by_customer_id

pub const stage_customer_payment_method = customers.stage_customer_payment_method

pub const upsert_base_customer_payment_methods = customers.upsert_base_customer_payment_methods

pub const stage_customer_payment_method_update_url = customers.stage_customer_payment_method_update_url

pub const stage_payment_reminder_send = customers.stage_payment_reminder_send

pub const get_effective_customer_payment_method_by_id = customers.get_effective_customer_payment_method_by_id

pub const list_effective_customer_payment_methods = customers.list_effective_customer_payment_methods

pub const upsert_base_payment_customizations = customers.upsert_base_payment_customizations

pub const upsert_staged_payment_customization = customers.upsert_staged_payment_customization

pub const delete_staged_payment_customization = customers.delete_staged_payment_customization

pub const get_effective_payment_customization_by_id = customers.get_effective_payment_customization_by_id

pub const list_effective_payment_customizations = customers.list_effective_payment_customizations

pub const has_payment_customizations = customers.has_payment_customizations

pub const register_payment_terms_owner = customers.register_payment_terms_owner

pub const upsert_staged_payment_terms = customers.upsert_staged_payment_terms

pub const upsert_base_payment_terms = customers.upsert_base_payment_terms

pub const delete_staged_payment_terms = customers.delete_staged_payment_terms

pub const payment_terms_owner_exists = customers.payment_terms_owner_exists

pub const get_effective_payment_terms_by_id = customers.get_effective_payment_terms_by_id

pub const get_effective_payment_terms_by_owner_id = customers.get_effective_payment_terms_by_owner_id

pub const get_effective_payment_schedule_by_id = customers.get_effective_payment_schedule_by_id

pub const stage_store_credit_account = customers.stage_store_credit_account

pub const stage_store_credit_account_transaction = customers.stage_store_credit_account_transaction

pub const get_effective_store_credit_account_by_id = customers.get_effective_store_credit_account_by_id

pub const get_effective_store_credit_account_by_owner_id = customers.get_effective_store_credit_account_by_owner_id

pub const get_effective_store_credit_account_by_owner_id_and_currency = customers.get_effective_store_credit_account_by_owner_id_and_currency

pub const list_effective_store_credit_accounts_for_customer = customers.list_effective_store_credit_accounts_for_customer

pub const list_effective_store_credit_account_transactions = customers.list_effective_store_credit_account_transactions

pub const upsert_base_customer_account_pages = customers.upsert_base_customer_account_pages

pub const get_effective_customer_account_page_by_id = customers.get_effective_customer_account_page_by_id

pub const list_effective_customer_account_pages = customers.list_effective_customer_account_pages

pub const stage_customer_data_erasure_request = customers.stage_customer_data_erasure_request

pub const get_customer_data_erasure_request = customers.get_customer_data_erasure_request

pub const stage_merge_customers = customers.stage_merge_customers

pub const get_customer_merge_request = customers.get_customer_merge_request

pub const upsert_base_segments = segments.upsert_base_segments

pub const upsert_staged_segment = segments.upsert_staged_segment

pub const delete_staged_segment = segments.delete_staged_segment

pub const get_effective_segment_by_id = segments.get_effective_segment_by_id

pub const list_effective_segments = segments.list_effective_segments

pub const set_base_segment_root_payload = segments.set_base_segment_root_payload

pub const get_base_segment_root_payload = segments.get_base_segment_root_payload

pub const stage_customer_segment_members_query = segments.stage_customer_segment_members_query

pub const get_effective_customer_segment_members_query_by_id = segments.get_effective_customer_segment_members_query_by_id

pub const replace_base_available_locales = markets.replace_base_available_locales

pub const list_effective_available_locales = markets.list_effective_available_locales

pub const upsert_base_shop_locales = markets.upsert_base_shop_locales

pub const stage_shop_locale = markets.stage_shop_locale

pub const disable_shop_locale = markets.disable_shop_locale

pub const get_effective_shop_locale = markets.get_effective_shop_locale

pub const list_effective_shop_locales = markets.list_effective_shop_locales

pub const translation_storage_key = markets.translation_storage_key

pub const stage_translation = markets.stage_translation

pub const upsert_base_translation = markets.upsert_base_translation

pub const remove_translation = markets.remove_translation

pub const remove_translations_for_locale = markets.remove_translations_for_locale

pub const list_effective_translations = markets.list_effective_translations

pub const has_localization_state = markets.has_localization_state

pub const record_mutation_log_entry = shared.record_mutation_log_entry

pub const get_log = shared.get_log

pub const update_log_entry = shared.update_log_entry
