/* oxlint-disable no-console -- CLI scripts intentionally write status output to stdio. */
import 'dotenv/config';

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { createAdminGraphqlClient, type ConformanceGraphqlResult } from './conformance-graphql-client.js';
import { readConformanceScriptConfig } from './conformance-script-config.js';
import { buildAdminAuthHeaders, getValidConformanceAccessToken } from './shopify-conformance-auth.mjs';

type CapturedRequest = {
  label: string;
  query: string;
  variables: Record<string, unknown>;
  response: ConformanceGraphqlResult;
};

const { storeDomain, adminOrigin, apiVersion } = readConformanceScriptConfig({
  defaultApiVersion: '2025-01',
  exitOnMissing: true,
});
const adminAccessToken = await getValidConformanceAccessToken({ adminOrigin, apiVersion });
const outputDir = path.join('fixtures', 'conformance', storeDomain, apiVersion, 'gift-cards');
const outputPath = path.join(outputDir, 'gift-card-create-validation.json');

const { runGraphqlRequest } = createAdminGraphqlClient({
  adminOrigin,
  apiVersion,
  headers: buildAdminAuthHeaders(adminAccessToken),
});

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readPath(value: unknown, pathParts: string[]): unknown {
  return pathParts.reduce<unknown>((cursor, part) => {
    if (!isObject(cursor)) {
      return undefined;
    }
    return cursor[part];
  }, value);
}

function readStringPath(value: unknown, pathParts: string[]): string | null {
  const found = readPath(value, pathParts);
  return typeof found === 'string' ? found : null;
}

function readCreatedGiftCardId(capture: CapturedRequest, alias: string): string | null {
  return readStringPath(capture.response.payload, ['data', alias, 'giftCard', 'id']);
}

async function capture(
  label: string,
  query: string,
  variables: Record<string, unknown> = {},
): Promise<CapturedRequest> {
  const response = await runGraphqlRequest(query, variables);
  return { label, query, variables, response };
}

async function deactivateGiftCard(label: string, id: string): Promise<CapturedRequest> {
  return capture(
    label,
    `#graphql
      mutation GiftCardCreateValidationCleanup($id: ID!) {
        giftCardDeactivate(id: $id) {
          giftCard {
            id
            enabled
            deactivatedAt
          }
          userErrors {
            field
            code
            message
          }
        }
      }
    `,
    { id },
  );
}

const validationMutation = `#graphql
  mutation GiftCardCreateValidation(
    $validCode: String!
    $tooLongCode: String!
    $missingCustomerId: ID!
  ) {
    zeroInitialValue: giftCardCreate(input: { initialValue: "0" }) {
      giftCard {
        id
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    shortCode: giftCardCreate(input: { initialValue: "10", code: "abc" }) {
      giftCard {
        id
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    longCode: giftCardCreate(input: { initialValue: "10", code: $tooLongCode }) {
      giftCard {
        id
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    invalidCode: giftCardCreate(input: { initialValue: "10", code: "bad!code" }) {
      giftCard {
        id
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    missingCustomer: giftCardCreate(
      input: { initialValue: "10", customerId: $missingCustomerId }
    ) {
      giftCard {
        id
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    success: giftCardCreate(input: { initialValue: "10", code: $validCode }) {
      giftCard {
        id
        lastCharacters
        maskedCode
        createdAt
        updatedAt
        initialValue {
          amount
          currencyCode
        }
        balance {
          amount
          currencyCode
        }
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    duplicate: giftCardCreate(input: { initialValue: "10", code: $validCode }) {
      giftCard {
        id
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
    autoGenerated: giftCardCreate(input: { initialValue: "10" }) {
      giftCard {
        id
        lastCharacters
        maskedCode
        createdAt
        updatedAt
        initialValue {
          amount
          currencyCode
        }
        balance {
          amount
          currencyCode
        }
      }
      giftCardCode
      userErrors {
        field
        code
        message
      }
    }
  }
`;

const runSuffix = Date.now().toString(36).slice(-8);
const proxyVariables = {
  validCode: `parityok${runSuffix}`,
  tooLongCode: 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  missingCustomerId: 'gid://shopify/Customer/999999999999',
};

const cleanup: CapturedRequest[] = [];
const validation = await capture('createValidation', validationMutation, proxyVariables);
for (const alias of ['success', 'autoGenerated']) {
  const id = readCreatedGiftCardId(validation, alias);
  if (id !== null) {
    cleanup.push(await deactivateGiftCard(`cleanupDeactivate:${alias}`, id));
  }
}

await mkdir(outputDir, { recursive: true });
await writeFile(
  outputPath,
  `${JSON.stringify(
    {
      capturedAt: new Date().toISOString(),
      storeDomain,
      apiVersion,
      notes: [
        'HAR-692 captures giftCardCreate validation userErrors for initial value, code length/format/uniqueness, and missing customer handling.',
        'The duplicate-code branch is captured by issuing the same run-unique valid code twice in one GraphQL mutation, avoiding permanent collisions from prior disposable gift-card captures.',
        'Successful gift cards created for validation evidence are deactivated during cleanup; Shopify gift-card code uniqueness remains shop-scoped, so the recorded valid code is intentionally run-unique.',
      ],
      proxyVariables: {
        createValidation: proxyVariables,
      },
      operations: {
        createValidation: validation,
      },
      cleanup,
      upstreamCalls: [],
    },
    null,
    2,
  )}\n`,
  'utf8',
);

console.log(`wrote ${outputPath}`);
