/* oxlint-disable no-console -- Capture scripts intentionally write status output to stdio. */
import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

type JsonRecord = Record<string, unknown>;
type GraphqlBody = {
  query: string;
  variables?: JsonRecord;
  operationName?: string;
};
type RecordedCall = {
  operationName: string;
  variables: JsonRecord;
  query: string;
  response: {
    status: number;
    body: JsonRecord;
  };
};
type ProxyResponse = {
  status: number;
  body: unknown;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const apiVersion = '2026-04';
const fixturePath = path.join(
  repoRoot,
  'fixtures',
  'conformance',
  'local-runtime',
  apiVersion,
  'orders',
  'return-lifecycle-local-staging.json',
);

function ensureGleamJsBuild(): void {
  const result = spawnSync('corepack', ['pnpm', 'gleam:build:js'], {
    cwd: repoRoot,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });

  if (result.status !== 0) {
    throw new Error(`Gleam JS build failed with status ${String(result.status)}`);
  }
}

async function readRequest(name: string): Promise<string> {
  return readFile(path.join(repoRoot, 'config', 'parity-requests', 'orders', name), 'utf8');
}

function readObject(value: unknown, context: string): JsonRecord {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${context} was not an object: ${JSON.stringify(value)}`);
  }

  return value as JsonRecord;
}

function readPath(value: unknown, segments: string[]): unknown {
  let current = value;
  for (const segment of segments) {
    if (!current || typeof current !== 'object' || Array.isArray(current)) {
      return undefined;
    }
    current = (current as JsonRecord)[segment];
  }

  return current;
}

function readRequiredString(value: unknown, segments: string[]): string {
  const found = readPath(value, segments);
  if (typeof found !== 'string' || found.length === 0) {
    throw new Error(`Missing required string at ${segments.join('.')}: ${JSON.stringify(value)}`);
  }

  return found;
}

function sameJson(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function extractOperationName(query: string): string {
  return query.match(/\b(?:query|mutation|subscription)\s+([A-Za-z_][A-Za-z0-9_]*)/)?.[1] ?? '';
}

function makeOrderHydrationCall(seedOrder: JsonRecord): RecordedCall {
  return {
    operationName: 'OrdersOrderHydrate',
    variables: { id: seedOrder['id'] },
    query:
      'generated by scripts/capture-return-decline-request-local-runtime.ts from the checked-in seedOrder for return lifecycle Pattern 2 order hydration',
    response: {
      status: 200,
      body: {
        data: {
          order: seedOrder,
        },
      },
    },
  };
}

function assertResponseOk(response: ProxyResponse, context: string): JsonRecord {
  if (response.status !== 200) {
    throw new Error(`${context} returned HTTP ${response.status}: ${JSON.stringify(response.body)}`);
  }

  const body = readObject(response.body, `${context} response body`);
  if ('errors' in body) {
    throw new Error(`${context} returned top-level GraphQL errors: ${JSON.stringify(body['errors'])}`);
  }

  return body;
}

async function runProxyRequest(
  proxy: { processGraphQLRequest: (input: GraphqlBody) => Promise<ProxyResponse> },
  query: string,
  variables: JsonRecord,
  context: string,
): Promise<JsonRecord> {
  return assertResponseOk(await proxy.processGraphQLRequest({ query, variables }), context);
}

ensureGleamJsBuild();

const fixture = readObject(JSON.parse(await readFile(fixturePath, 'utf8')), 'return lifecycle fixture');
const seedOrder = readObject(fixture['seedOrder'], 'fixture.seedOrder');
const upstreamCalls = [makeOrderHydrationCall(seedOrder)];

const [{ createDraftProxy }, { Ok, Error: GleamError, toList }, { HttpOutcome, CommitTransportError }] =
  await Promise.all([
    import('../js/src/index.js'),
    import(pathToFileURL(path.join(repoRoot, 'build', 'dev', 'javascript', 'prelude.mjs')).href),
    import(
      pathToFileURL(
        path.join(
          repoRoot,
          'build',
          'dev',
          'javascript',
          'shopify_draft_proxy',
          'shopify_draft_proxy',
          'proxy',
          'commit.mjs',
        ),
      ).href
    ),
  ]);

const proxy = createDraftProxy({
  readMode: 'live-hybrid',
  port: 0,
  shopifyAdminOrigin: 'https://local-runtime.invalid',
});

proxy.installSyncTransport((request: JsonRecord) => {
  try {
    const body = JSON.parse(String(request['body'] ?? '{}')) as GraphqlBody;
    const operationName = body.operationName ?? extractOperationName(body.query);
    const variables = body.variables ?? {};
    const call = upstreamCalls.find(
      (candidate) => candidate.operationName === operationName && sameJson(candidate.variables, variables),
    );

    if (!call) {
      return new GleamError(
        new CommitTransportError(`cassette miss: operation=${operationName} variables=${JSON.stringify(variables)}`),
      );
    }

    return new Ok(new HttpOutcome(call.response.status, JSON.stringify(call.response.body), toList([])));
  } catch (error) {
    return new GleamError(new CommitTransportError((error as Error).message));
  }
});

const returnRequestQuery = await readRequest('return-request-reverse-local-staging.graphql');
const returnDeclineQuery = await readRequest('return-decline-request-local-staging.graphql');
const declineRequest = readObject(fixture['declineRequest'], 'fixture.declineRequest');
const declineVariables = readObject(declineRequest['variables'], 'fixture.declineRequest.variables');
const declineInput = readObject(declineRequest['declineInput'], 'fixture.declineRequest.declineInput');

const primary = await runProxyRequest(proxy, returnRequestQuery, declineVariables, 'returnRequest setup');
const returnId = readRequiredString(primary, ['data', 'returnRequest', 'return', 'id']);

const invalidDeclineReason = await runProxyRequest(
  proxy,
  returnDeclineQuery,
  {
    input: {
      id: returnId,
      declineReason: 'BANANAS',
    },
  },
  'invalid decline reason',
);
const invalidDeclineNotifyEmail = await runProxyRequest(
  proxy,
  returnDeclineQuery,
  {
    input: {
      id: returnId,
      declineReason: 'OTHER',
      notifyCustomer: true,
      tmp_notify_customer: {
        email_address: 'not-an-email',
      },
    },
  },
  'invalid decline notify email',
);
const validDecline = await runProxyRequest(
  proxy,
  returnDeclineQuery,
  {
    input: {
      id: returnId,
      ...declineInput,
    },
  },
  'valid decline request',
);

const expected = readObject(fixture['expected'], 'fixture.expected');
expected['invalidDeclineReason'] = invalidDeclineReason;
expected['invalidDeclineNotifyEmail'] = invalidDeclineNotifyEmail;
expected['declineRequest'] = validDecline;
fixture['capturedAt'] = new Date().toISOString();
fixture['source'] = 'local-runtime-capture-script';
fixture['notes'] =
  'Executable local-runtime parity fixture for the supported order-backed return lifecycle. Live no-side-effect schema evidence remains in fixtures/conformance/harry-test-heelo.myshopify.com/<api-version>/orders/return-reverse-logistics-introspection.json; return decline validation public-schema evidence is recorded by scripts/capture-return-decline-request-validation-conformance.ts. This fixture supplies the fulfilled order graph needed to replay local return lifecycle and validation branches without runtime Shopify writes.';
fixture['upstreamCalls'] = upstreamCalls;

await mkdir(path.dirname(fixturePath), { recursive: true });
await writeFile(fixturePath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
console.log(`Wrote ${path.relative(repoRoot, fixturePath)}`);
