/* oxlint-disable no-console -- Capture scripts intentionally write status output to stdio. */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createServer, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createDraftProxy } from '../js/src/index.js';

type JsonRecord = Record<string, unknown>;
type GraphqlBody = {
  query: string;
  variables?: JsonRecord;
  operationName?: string;
};
type RecordedCall = {
  operationName: string;
  variables: JsonRecord;
  query: string;
  response: {
    status: number;
    body: JsonRecord;
  };
};
type ProxyResponse = {
  status: number;
  body: unknown;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const apiVersion = '2026-04';
const fixturePath = path.join(
  repoRoot,
  'fixtures',
  'conformance',
  'local-runtime',
  apiVersion,
  'orders',
  'return-lifecycle-local-staging.json',
);

async function readRequest(name: string): Promise<string> {
  return readFile(path.join(repoRoot, 'config', 'parity-requests', 'orders', name), 'utf8');
}

function readObject(value: unknown, context: string): JsonRecord {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${context} was not an object: ${JSON.stringify(value)}`);
  }

  return value as JsonRecord;
}

function readPath(value: unknown, segments: string[]): unknown {
  let current = value;
  for (const segment of segments) {
    if (!current || typeof current !== 'object' || Array.isArray(current)) {
      return undefined;
    }
    current = (current as JsonRecord)[segment];
  }

  return current;
}

function readRequiredString(value: unknown, segments: string[]): string {
  const found = readPath(value, segments);
  if (typeof found !== 'string' || found.length === 0) {
    throw new Error(`Missing required string at ${segments.join('.')}: ${JSON.stringify(value)}`);
  }

  return found;
}

function sameJson(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function extractOperationName(query: string): string {
  return query.match(/\b(?:query|mutation|subscription)\s+([A-Za-z_][A-Za-z0-9_]*)/)?.[1] ?? '';
}

async function startRecordedUpstreamServer(
  calls: RecordedCall[],
): Promise<{ origin: string; close: () => Promise<void> }> {
  const server: Server = createServer((request, response) => {
    let body = '';
    request.setEncoding('utf8');
    request.on('data', (chunk: string) => {
      body += chunk;
    });
    request.on('end', () => {
      try {
        const parsed = JSON.parse(body || '{}') as GraphqlBody;
        const operationName = parsed.operationName ?? extractOperationName(parsed.query);
        const variables = parsed.variables ?? {};
        const call = calls.find(
          (candidate) => candidate.operationName === operationName && sameJson(candidate.variables, variables),
        );
        if (!call) {
          response.writeHead(500, { 'content-type': 'application/json' });
          response.end(
            JSON.stringify({
              errors: [
                {
                  message: `cassette miss: operation=${operationName} variables=${JSON.stringify(variables)}`,
                },
              ],
            }),
          );
          return;
        }
        response.writeHead(call.response.status, { 'content-type': 'application/json' });
        response.end(JSON.stringify(call.response.body));
      } catch (error) {
        response.writeHead(500, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ errors: [{ message: (error as Error).message }] }));
      }
    });
  });

  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const address = server.address() as AddressInfo;
  return {
    origin: `http://127.0.0.1:${address.port}`,
    close: () =>
      new Promise<void>((resolve, reject) => {
        server.close((error) => (error ? reject(error) : resolve()));
      }),
  };
}

function makeOrderHydrationCall(seedOrder: JsonRecord): RecordedCall {
  return {
    operationName: 'OrdersOrderHydrate',
    variables: { id: seedOrder['id'] },
    query:
      'generated by scripts/capture-return-decline-request-local-runtime.ts from the checked-in seedOrder for return lifecycle Pattern 2 order hydration',
    response: {
      status: 200,
      body: {
        data: {
          order: seedOrder,
        },
      },
    },
  };
}

function assertResponseOk(response: ProxyResponse, context: string): JsonRecord {
  if (response.status !== 200) {
    throw new Error(`${context} returned HTTP ${response.status}: ${JSON.stringify(response.body)}`);
  }

  const body = readObject(response.body, `${context} response body`);
  if ('errors' in body) {
    throw new Error(`${context} returned top-level GraphQL errors: ${JSON.stringify(body['errors'])}`);
  }

  return body;
}

async function runProxyRequest(
  proxy: { processGraphQLRequest: (input: GraphqlBody, options?: { apiVersion?: string }) => Promise<ProxyResponse> },
  query: string,
  variables: JsonRecord,
  context: string,
): Promise<JsonRecord> {
  return assertResponseOk(await proxy.processGraphQLRequest({ query, variables }, { apiVersion }), context);
}

const fixture = readObject(JSON.parse(await readFile(fixturePath, 'utf8')), 'return lifecycle fixture');
const seedOrder = readObject(fixture['seedOrder'], 'fixture.seedOrder');
const upstreamCalls = [makeOrderHydrationCall(seedOrder)];
const upstreamServer = await startRecordedUpstreamServer(upstreamCalls);

const proxy = createDraftProxy({
  readMode: 'live-hybrid',
  port: 0,
  shopifyAdminOrigin: upstreamServer.origin,
});

const returnRequestQuery = await readRequest('return-request-reverse-local-staging.graphql');
const returnDeclineQuery = await readRequest('return-decline-request-local-staging.graphql');
const declineRequest = readObject(fixture['declineRequest'], 'fixture.declineRequest');
const declineVariables = readObject(declineRequest['variables'], 'fixture.declineRequest.variables');
const declineInput = readObject(declineRequest['declineInput'], 'fixture.declineRequest.declineInput');

const primary = await runProxyRequest(proxy, returnRequestQuery, declineVariables, 'returnRequest setup');
const returnId = readRequiredString(primary, ['data', 'returnRequest', 'return', 'id']);

const invalidDeclineReason = await runProxyRequest(
  proxy,
  returnDeclineQuery,
  {
    input: {
      id: returnId,
      declineReason: 'BANANAS',
    },
  },
  'invalid decline reason',
);
const invalidDeclineNotifyEmail = await runProxyRequest(
  proxy,
  returnDeclineQuery,
  {
    input: {
      id: returnId,
      declineReason: 'OTHER',
      notifyCustomer: true,
      tmp_notify_customer: {
        email_address: 'not-an-email',
      },
    },
  },
  'invalid decline notify email',
);
const validDecline = await runProxyRequest(
  proxy,
  returnDeclineQuery,
  {
    input: {
      id: returnId,
      ...declineInput,
    },
  },
  'valid decline request',
);

const expected = readObject(fixture['expected'], 'fixture.expected');
expected['invalidDeclineReason'] = invalidDeclineReason;
expected['invalidDeclineNotifyEmail'] = invalidDeclineNotifyEmail;
expected['declineRequest'] = validDecline;
fixture['capturedAt'] = new Date().toISOString();
fixture['source'] = 'local-runtime-capture-script';
fixture['notes'] =
  'Executable local-runtime parity fixture for the supported order-backed return lifecycle. Live no-side-effect schema evidence remains in fixtures/conformance/harry-test-heelo.myshopify.com/<api-version>/orders/return-reverse-logistics-introspection.json; return decline validation public-schema evidence is recorded by scripts/capture-return-decline-request-validation-conformance.ts. This fixture supplies the fulfilled order graph needed to replay local return lifecycle and validation branches without runtime Shopify writes.';
fixture['upstreamCalls'] = upstreamCalls;

await mkdir(path.dirname(fixturePath), { recursive: true });
await writeFile(fixturePath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
console.log(`Wrote ${path.relative(repoRoot, fixturePath)}`);
proxy.dispose();
await upstreamServer.close();
