import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

type JsonRecord = Record<string, unknown>;
type ProxyResponse = {
  status: number;
  body: unknown;
};
type DraftProxyInstance = {
  processGraphQLRequest: (
    body: { query: string; variables?: JsonRecord },
    options?: { apiVersion?: string; headers?: Record<string, string> },
  ) => Promise<ProxyResponse>;
  dispose: () => void;
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const apiVersion = '2026-04';
const appsFixtureDir = path.join(repoRoot, 'fixtures', 'conformance', 'local-runtime', apiVersion, 'apps');
const appsRequestDir = path.join(repoRoot, 'config', 'parity-requests', 'apps');

function readObject(value: unknown, context: string): JsonRecord {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${context} was not an object: ${JSON.stringify(value)}`);
  }
  return value as JsonRecord;
}

function readPath(value: unknown, pathSegments: string[], context: string): unknown {
  let current = value;
  for (const segment of pathSegments) {
    if (Array.isArray(current)) {
      const index = Number.parseInt(segment, 10);
      if (!Number.isInteger(index)) {
        throw new Error(`${context}.${segment} expected an array index`);
      }
      current = current[index];
    } else {
      current = readObject(current, `${context}.${segment}`)[segment];
    }
  }
  return current;
}

function readStringPath(value: unknown, pathSegments: string[], context: string): string {
  const current = readPath(value, pathSegments, context);
  if (typeof current !== 'string') {
    throw new Error(`${context}.${pathSegments.join('.')} was not a string: ${JSON.stringify(current)}`);
  }
  return current;
}

function assertOk(response: ProxyResponse, context: string): JsonRecord {
  if (response.status !== 200) {
    throw new Error(`${context} returned HTTP ${response.status}: ${JSON.stringify(response.body)}`);
  }
  return readObject(response.body, `${context} response body`);
}

async function readGraphql(fileName: string): Promise<string> {
  return await readFile(path.join(appsRequestDir, fileName), 'utf8');
}

async function readExistingFixture(fileName: string): Promise<JsonRecord> {
  return readObject(JSON.parse(await readFile(path.join(appsFixtureDir, fileName), 'utf8')) as unknown, fileName);
}

function localRuntimeNotes(scenario: string, notes: string[]): string[] {
  return notes
    .filter((note) => !note.startsWith('Regenerated by scripts/capture-apps-billing-local-runtime.ts'))
    .map((note) =>
      note
        .replace(
          'Runtime fixture enforced by the Gleam parity runner and apps mutation tests.',
          'Runtime fixture enforced by the Rust parity runner and Apps mutation tests.',
        )
        .replace(
          'Runtime fixture enforced by test/shopify_draft_proxy/proxy/apps_mutation_test.gleam and config/parity-specs/apps/app-purchase-one-time-create-validation.json.',
          'Runtime fixture enforced by tests/graphql_routes/admin_app_shipping.rs and config/parity-specs/apps/app-purchase-one-time-create-validation.json.',
        )
        .replace(
          'Admin GraphQL 2026-04 public schema introspection on 2026-05-07 exposes appSubscriptionLineItemUpdate id and cappedAmount args only; the internal requireApproval arg is covered by focused Gleam runtime tests instead of a fabricated live parity spec.',
          'Admin GraphQL 2026-04 public schema introspection on 2026-05-07 exposes appSubscriptionLineItemUpdate id and cappedAmount args only; this local-runtime fixture does not fabricate live coverage for the hidden requireApproval: false branch.',
        )
        .replace(
          'Runtime behavior is also covered by test/shopify_draft_proxy/proxy/apps_mutation_test.gleam.',
          'Runtime behavior is also covered by tests/graphql_routes/admin_app_shipping.rs.',
        ),
    )
    .concat([`Regenerated by scripts/capture-apps-billing-local-runtime.ts for ${scenario}.`]);
}

async function writeFixture(fileName: string, fixture: JsonRecord): Promise<void> {
  await mkdir(appsFixtureDir, { recursive: true });
  await writeFile(path.join(appsFixtureDir, fileName), `${JSON.stringify(fixture, null, 2)}\n`);
}

async function createProxy(): Promise<DraftProxyInstance> {
  const { createDraftProxy } = (await import('../js/src/index.js')) as {
    createDraftProxy: (options: { readMode: string; port: number; shopifyAdminOrigin: string }) => DraftProxyInstance;
  };
  return createDraftProxy({
    readMode: 'live-hybrid',
    port: 0,
    shopifyAdminOrigin: 'https://local-runtime.invalid',
  });
}

async function capturePurchaseValidation(): Promise<void> {
  const scenario = 'app-purchase-one-time-create-validation';
  const fileName = `${scenario}.json`;
  const existing = await readExistingFixture(fileName);
  const proxy = await createProxy();
  try {
    const blankName = await proxy.processGraphQLRequest(
      { query: await readGraphql('appPurchaseOneTimeCreate-validation-blank-name.graphql') },
      { apiVersion },
    );
    const zeroPrice = await proxy.processGraphQLRequest(
      { query: await readGraphql('appPurchaseOneTimeCreate-validation-zero-price.graphql') },
      { apiVersion },
    );
    const currencyMismatch = await proxy.processGraphQLRequest(
      { query: await readGraphql('appPurchaseOneTimeCreate-validation-currency-mismatch.graphql') },
      { apiVersion },
    );
    const missingReturnUrl = await proxy.processGraphQLRequest(
      { query: await readGraphql('appPurchaseOneTimeCreate-validation-missing-return-url.graphql') },
      { apiVersion },
    );
    const success = await proxy.processGraphQLRequest(
      { query: await readGraphql('appPurchaseOneTimeCreate-validation-success.graphql') },
      { apiVersion },
    );
    const statusTestFalse = await proxy.processGraphQLRequest(
      { query: await readGraphql('appPurchaseOneTimeCreate-status-test-false.graphql') },
      { apiVersion },
    );
    const notes = Array.isArray(existing['notes']) ? (existing['notes'] as string[]) : [];
    await writeFixture(fileName, {
      capturedAt: existing['capturedAt'],
      storeDomain: 'local-runtime',
      apiVersion,
      scenario,
      notes: localRuntimeNotes(scenario, notes),
      operationNames: ['appPurchaseOneTimeCreate'],
      evidence: {
        parity: {
          expected: {
            blankName: assertOk(blankName, 'blank name'),
            zeroPrice: assertOk(zeroPrice, 'zero price'),
            currencyMismatch: assertOk(currencyMismatch, 'currency mismatch'),
            missingReturnUrl: assertOk(missingReturnUrl, 'missing return URL'),
            success: assertOk(success, 'success'),
            statusTestFalse: assertOk(statusTestFalse, 'status test false'),
          },
        },
      },
      upstreamCalls: [],
    });
  } finally {
    proxy.dispose();
  }
}

async function captureUsageRecord(): Promise<void> {
  const scenario = 'app-usage-record-create-cap-and-idempotency';
  const fileName = `${scenario}.json`;
  const existing = await readExistingFixture(fileName);
  const proxy = await createProxy();
  try {
    const subscriptionCreate = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appSubscriptionCreate-local-lifecycle.graphql'),
          variables: {
            lineItems: [
              {
                plan: {
                  appUsagePricingDetails: {
                    cappedAmount: { amount: 5, currencyCode: 'USD' },
                    terms: 'usage terms',
                  },
                },
              },
            ],
          },
        },
        { apiVersion },
      ),
      'subscription create',
    );
    const lineItemId = readStringPath(
      subscriptionCreate,
      ['data', 'appSubscriptionCreate', 'appSubscription', 'lineItems', '0', 'id'],
      'subscriptionCreate',
    );
    const usageCreate = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appUsageRecordCreate-cap-success.graphql'),
          variables: { id: lineItemId },
        },
        { apiVersion },
      ),
      'usage create',
    );
    const overCap = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appUsageRecordCreate-cap-over-limit.graphql'),
          variables: { id: lineItemId },
        },
        { apiVersion },
      ),
      'over cap',
    );
    const longKey = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appUsageRecordCreate-long-idempotency-key.graphql'),
          variables: {
            id: lineItemId,
            key: 'x'.repeat(256),
          },
        },
        { apiVersion },
      ),
      'long idempotency key',
    );
    const duplicate = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appUsageRecordCreate-cap-success.graphql'),
          variables: { id: lineItemId },
        },
        { apiVersion },
      ),
      'duplicate usage create',
    );
    const billingRead = assertOk(
      await proxy.processGraphQLRequest(
        { query: await readGraphql('app-usage-record-create-cap-read.graphql') },
        { apiVersion },
      ),
      'billing read',
    );
    const notes = Array.isArray(existing['notes']) ? (existing['notes'] as string[]) : [];
    await writeFixture(fileName, {
      capturedAt: existing['capturedAt'],
      storeDomain: 'local-runtime',
      apiVersion,
      scenario,
      notes: localRuntimeNotes(scenario, notes),
      operationNames: ['appSubscriptionCreate', 'appUsageRecordCreate'],
      evidence: {
        parity: {
          expected: {
            subscriptionCreate,
            usageCreate,
            overCap,
            longKey,
            duplicate,
            billingRead,
          },
        },
      },
      upstreamCalls: [],
    });
  } finally {
    proxy.dispose();
  }
}

async function captureLineItemUpdate(): Promise<void> {
  const scenario = 'app-subscription-line-item-update-validation';
  const fileName = `${scenario}.json`;
  const existing = await readExistingFixture(fileName);
  const proxy = await createProxy();
  try {
    const subscriptionCreate = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appSubscriptionCreate-local-lifecycle.graphql'),
          variables: {
            lineItems: [
              {
                plan: {
                  appUsagePricingDetails: {
                    cappedAmount: { amount: 5, currencyCode: 'USD' },
                    terms: 'usage terms',
                  },
                },
              },
              {
                plan: {
                  appRecurringPricingDetails: {
                    price: { amount: 1, currencyCode: 'USD' },
                    interval: 'EVERY_30_DAYS',
                  },
                },
              },
            ],
          },
        },
        { apiVersion },
      ),
      'subscription create',
    );
    const usageLineItemId = readStringPath(
      subscriptionCreate,
      ['data', 'appSubscriptionCreate', 'appSubscription', 'lineItems', '0', 'id'],
      'subscriptionCreate',
    );
    const recurringLineItemId = readStringPath(
      subscriptionCreate,
      ['data', 'appSubscriptionCreate', 'appSubscription', 'lineItems', '1', 'id'],
      'subscriptionCreate',
    );
    const validation = assertOk(
      await proxy.processGraphQLRequest(
        {
          query: await readGraphql('appSubscriptionLineItemUpdate-validation.graphql'),
          variables: { usageLineItemId, recurringLineItemId },
        },
        { apiVersion },
      ),
      'line item update validation',
    );
    const notes = Array.isArray(existing['notes']) ? (existing['notes'] as string[]) : [];
    await writeFixture(fileName, {
      capturedAt: existing['capturedAt'],
      storeDomain: 'local-runtime',
      apiVersion,
      scenario,
      notes: localRuntimeNotes(scenario, notes),
      operationNames: ['appSubscriptionCreate', 'appSubscriptionLineItemUpdate'],
      upstreamCalls: [],
      evidence: {
        parity: {
          expected: {
            subscriptionCreate,
            validation,
          },
        },
      },
    });
  } finally {
    proxy.dispose();
  }
}

await capturePurchaseValidation();
await captureUsageRecord();
await captureLineItemUpdate();
