#!/usr/bin/env bash
#
# Regenerate `mutation_schema_data.gleam` from
# `config/admin-graphql-mutation-schema.json` (captured by
# `scripts/capture-mutation-input-schema.mts`). Produces a Gleam module
# that returns the captured schema as a literal value — no JSON parsing
# at runtime, no FFI, target-portable.
#
# Run this whenever the captured schema fixture is refreshed. Use
# `--check` in CI to fail when the generated Gleam mirror is stale.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(dirname "$here")"

src="$repo_root/config/admin-graphql-mutation-schema.json"
dest="$repo_root/src/shopify_draft_proxy/proxy/mutation_schema_data.gleam"
mode="${1:-write}"

if [[ ! -f "$src" ]]; then
  echo "source not found: $src" >&2
  exit 1
fi

if [[ "$mode" != "write" && "$mode" != "--check" ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

out="$dest"
tmp=""
if [[ "$mode" == "--check" ]]; then
  tmp="$(mktemp --suffix=.gleam)"
  out="$tmp"
  trap 'rm -f "$tmp"' EXIT
fi

python3 - "$src" "$out" <<'PYEOF'
import json
import sys
from pathlib import Path

src_path = Path(sys.argv[1])
dest_path = Path(sys.argv[2])

with src_path.open() as f:
    schema = json.load(f)


def gleam_string(s):
    if s is None:
        return '""'
    escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
    return f'"{escaped}"'


def gleam_option_string(value):
    if value is None:
        return "None"
    return f"Some({gleam_string(value)})"


def gleam_bool(value):
    return "True" if value else "False"


# Render the recursive type ref as a chain of variants:
# NON_NULL(LIST(NON_NULL(NamedType("ID")))) etc.
def render_type_ref(t):
    if t is None:
        return 'NamedType("")'
    kind = t.get("kind")
    if kind == "NON_NULL":
        return f"NonNullType({render_type_ref(t.get('ofType'))})"
    if kind == "LIST":
        return f"ListType({render_type_ref(t.get('ofType'))})"
    name = t.get("name") or ""
    return f"NamedType({gleam_string(name)})"


def render_arg(arg):
    return (
        "      SchemaArg(\n"
        f"        name: {gleam_string(arg['name'])},\n"
        f"        is_deprecated: {gleam_bool(arg['isDeprecated'])},\n"
        f"        deprecation_reason: {gleam_option_string(arg.get('deprecationReason'))},\n"
        f"        default_value: {gleam_option_string(arg.get('defaultValue'))},\n"
        f"        type_: {render_type_ref(arg['type'])},\n"
        "      )"
    )


def render_field(field):
    return (
        "      SchemaInputField(\n"
        f"        name: {gleam_string(field['name'])},\n"
        f"        is_deprecated: {gleam_bool(field['isDeprecated'])},\n"
        f"        deprecation_reason: {gleam_option_string(field.get('deprecationReason'))},\n"
        f"        default_value: {gleam_option_string(field.get('defaultValue'))},\n"
        f"        type_: {render_type_ref(field['type'])},\n"
        "      )"
    )


def render_mutation(m):
    args = m.get("args", [])
    if not args:
        args_block = "[]"
    else:
        args_block = "[\n" + ",\n".join(render_arg(a) for a in args) + ",\n    ]"
    return (
        "  SchemaMutation(\n"
        f"    name: {gleam_string(m['name'])},\n"
        f"    is_deprecated: {gleam_bool(m['isDeprecated'])},\n"
        f"    deprecation_reason: {gleam_option_string(m.get('deprecationReason'))},\n"
        f"    args: {args_block},\n"
        "  )"
    )


def render_input_object(io):
    fields = io.get("inputFields", [])
    if not fields:
        fields_block = "[]"
    else:
        fields_block = "[\n" + ",\n".join(render_field(f) for f in fields) + ",\n    ]"
    return (
        "  SchemaInputObject(\n"
        f"    name: {gleam_string(io['name'])},\n"
        f"    input_fields: {fields_block},\n"
        "  )"
    )


header = (
    "//// Generated by `scripts/sync-mutation-schema.sh` from\n"
    "//// `config/admin-graphql-mutation-schema.json`. Do not edit by hand —\n"
    "//// re-run the script after refreshing the JSON via\n"
    "//// `scripts/capture-mutation-input-schema.mts`. This file holds the\n"
    "//// captured Admin GraphQL mutation/input-object schema as a literal\n"
    "//// value so the proxy carries it on every target without runtime IO.\n"
    "////\n"
    f"//// Captured at: {schema['capturedAt']}\n"
    f"//// Source store: {schema['storeDomain']}\n"
    f"//// API version: {schema['apiVersion']}\n"
    "\n"
    "import gleam/option.{None, Some}\n"
    "import shopify_draft_proxy/proxy/mutation_schema.{\n"
    "  type SchemaInputObject, type SchemaMutation, ListType, NamedType,\n"
    "  NonNullType, SchemaArg, SchemaInputField, SchemaInputObject,\n"
    "  SchemaMutation,\n"
    "}\n"
    "\n"
    f'pub const captured_at: String = {gleam_string(schema["capturedAt"])}\n\n'
    f'pub const captured_api_version: String = {gleam_string(schema["apiVersion"])}\n\n'
    "/// Captured Mutation field shapes. Sorted by name in the source\n"
    "/// JSON; preserved here for stable diffs.\n"
    "pub fn mutations() -> List(SchemaMutation) {\n"
    "  [\n"
)

footer_mut = "\n  ]\n}\n\n"

middle = (
    "/// Captured input object shapes reachable from any Mutation\n"
    "/// argument. Sorted by name in the source JSON.\n"
    "pub fn input_objects() -> List(SchemaInputObject) {\n"
    "  [\n"
)

footer = "\n  ]\n}\n"

with dest_path.open("w") as f:
    f.write(header)
    f.write(",\n".join(render_mutation(m) for m in schema["mutations"]))
    f.write(footer_mut)
    f.write(middle)
    f.write(",\n".join(render_input_object(io) for io in schema["inputObjects"]))
    f.write(footer)

print(
    f"wrote {len(schema['mutations'])} mutations and "
    f"{len(schema['inputObjects'])} input objects to {dest_path}"
)
PYEOF

(cd "$repo_root" && gleam format "$out")

if [[ "$mode" == "--check" ]]; then
  if ! cmp -s "$tmp" "$dest"; then
    echo "Gleam mutation schema mirror is stale. Run scripts/sync-mutation-schema.sh" >&2
    diff -u "$dest" "$tmp" >&2 || true
    exit 1
  fi
  echo "$dest is up to date"
fi
