/* oxlint-disable no-console -- CLI scripts intentionally write status output to stdio. */
/**
 * Regenerate `bulk_query_schema_data.gleam` from the captured Admin GraphQL
 * output-field schema facts in `config/admin-graphql-bulk-query-schema.json`.
 */
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

type CapturedKind =
  | { type: 'connection'; nodeType: string }
  | { type: 'list'; elementType: string }
  | { type: 'object'; typeName: string };

type CapturedField = {
  parentType: string;
  name: string;
  kind: CapturedKind;
};

type CapturedSchema = {
  capturedAt: string;
  storeDomain: string;
  apiVersion: string;
  fields: CapturedField[];
};

const mode = process.argv[2] ?? 'write';
if (mode !== 'write' && mode !== '--check') {
  console.error('usage: corepack pnpm tsx scripts/sync-bulk-query-schema.mts [--check]');
  process.exit(2);
}

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = path.join(repoRoot, 'config', 'admin-graphql-bulk-query-schema.json');
const destPath = path.join(repoRoot, 'src', 'shopify_draft_proxy', 'proxy', 'bulk_query_schema_data.gleam');

function gleamString(value: string): string {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

function renderKind(kind: CapturedKind): string {
  switch (kind.type) {
    case 'connection':
      return `BulkSchemaConnection(${gleamString(kind.nodeType)})`;
    case 'list':
      return `BulkSchemaList(${gleamString(kind.elementType)})`;
    case 'object':
      return `BulkSchemaObject(${gleamString(kind.typeName)})`;
  }
}

function renderField(field: CapturedField): string {
  return [
    '    BulkSchemaField(',
    `      parent_type: ${gleamString(field.parentType)},`,
    `      name: ${gleamString(field.name)},`,
    `      kind: ${renderKind(field.kind)},`,
    '    )',
  ].join('\n');
}

function renderSchema(schema: CapturedSchema): string {
  const header = [
    '//// Generated by `scripts/sync-bulk-query-schema.mts` from',
    '//// `config/admin-graphql-bulk-query-schema.json`. Do not edit by hand;',
    '//// re-run the script after refreshing the JSON via',
    '//// `scripts/capture-bulk-query-schema.mts`. This file holds the',
    '//// captured Admin GraphQL output-field schema facts used by the',
    '//// bulkOperationRunQuery validator as literal values so the proxy carries',
    '//// them on every target without runtime IO.',
    '////',
    `//// Captured at: ${schema.capturedAt}`,
    `//// Source store: ${schema.storeDomain}`,
    `//// API version: ${schema.apiVersion}`,
    '',
    'import shopify_draft_proxy/proxy/bulk_query_schema.{',
    '  type BulkSchemaField, BulkSchemaConnection, BulkSchemaField,',
    '  BulkSchemaList, BulkSchemaObject,',
    '}',
    '',
    `pub const captured_at: String = ${gleamString(schema.capturedAt)}`,
    '',
    `pub const captured_api_version: String = ${gleamString(schema.apiVersion)}`,
    '',
    'pub fn fields() -> List(BulkSchemaField) {',
    '  [',
  ].join('\n');

  return `${header}\n${schema.fields.map(renderField).join(',\n')}\n  ]\n}\n`;
}

function runGleamFormat(targetPath: string): void {
  const result = spawnSync('gleam', ['format', targetPath], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: 'pipe',
  });
  if (result.status !== 0) {
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.status ?? 1);
  }
}

async function main(): Promise<void> {
  const schema = JSON.parse(await readFile(sourcePath, 'utf8')) as CapturedSchema;
  const output = renderSchema(schema);

  if (mode === '--check') {
    const tempDir = await mkdtemp(path.join(tmpdir(), 'bulk-query-schema-'));
    const tempPath = path.join(tempDir, 'bulk_query_schema_data.gleam');
    try {
      await writeFile(tempPath, output, 'utf8');
      runGleamFormat(tempPath);
      const [actual, expected] = await Promise.all([readFile(destPath, 'utf8'), readFile(tempPath, 'utf8')]);
      if (actual !== expected) {
        console.error(
          'Gleam bulk query schema mirror is stale. Run `corepack pnpm tsx scripts/sync-bulk-query-schema.mts`.',
        );
        process.exit(1);
      }
      console.log(`${destPath} is up to date`);
    } finally {
      await rm(tempDir, { recursive: true, force: true });
    }
    return;
  }

  await writeFile(destPath, output, 'utf8');
  runGleamFormat(destPath);
  console.log(`wrote ${schema.fields.length} bulk query schema fields to ${destPath}`);
}

await main();
