#!/usr/bin/env bash
#
# Regenerate `operation_registry_data.gleam` from the TS-side source of
# truth at `config/operation-registry.json`. Produces a Gleam module
# that returns the registry as a `List(RegistryEntry)` literal — no
# JSON parsing at runtime, no FFI, target-portable.
#
# Run this whenever `config/operation-registry.json` changes. Use
# `--check` in CI to fail when the generated Gleam mirror is stale.
# Once the TS proxy is fully retired, the JSON file goes away and this
# script with it.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(dirname "$here")"

src="$repo_root/config/operation-registry.json"
dest="$repo_root/src/shopify_draft_proxy/proxy/operation_registry_data.gleam"
mode="${1:-write}"

if [[ ! -f "$src" ]]; then
  echo "source not found: $src" >&2
  exit 1
fi

if [[ "$mode" != "write" && "$mode" != "--check" ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

out="$dest"
tmp=""
if [[ "$mode" == "--check" ]]; then
  tmp="$(mktemp --suffix=.gleam)"
  out="$tmp"
  trap 'rm -f "$tmp"' EXIT
fi

python3 - "$src" "$out" <<'PYEOF'
import json
import sys
from pathlib import Path

src_path = Path(sys.argv[1])
dest_path = Path(sys.argv[2])

DOMAIN_TO_VARIANT = {
    "products": "Products",
    "admin-platform": "AdminPlatform",
    "b2b": "B2b",
    "apps": "Apps",
    "media": "Media",
    "bulk-operations": "BulkOperations",
    "customers": "Customers",
    "orders": "Orders",
    "store-properties": "StoreProperties",
    "discounts": "Discounts",
    "events": "Events",
    "functions": "Functions",
    "payments": "Payments",
    "marketing": "Marketing",
    "online-store": "OnlineStore",
    "saved-searches": "SavedSearches",
    "privacy": "Privacy",
    "segments": "Segments",
    "shipping-fulfillments": "ShippingFulfillments",
    "gift-cards": "GiftCards",
    "webhooks": "Webhooks",
    "localization": "Localization",
    "markets": "Markets",
    "metafields": "Metafields",
    "metaobjects": "Metaobjects",
    "unknown": "Unknown",
}

EXECUTION_TO_VARIANT = {
    "overlay-read": "OverlayRead",
    "stage-locally": "StageLocally",
    "passthrough": "Passthrough",
}

TYPE_TO_VARIANT = {
    "query": "Query",
    "mutation": "Mutation",
}


def gleam_string(s):
    escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
    return f'"{escaped}"'


def gleam_string_list(items):
    if not items:
        return "[]"
    body = ", ".join(gleam_string(x) for x in items)
    return f"[{body}]"


def gleam_option(value):
    if value is None:
        return "None"
    return f"Some({gleam_string(value)})"


def render_entry(entry):
    name = gleam_string(entry["name"])
    type_variant = TYPE_TO_VARIANT[entry["type"]]
    domain_variant = DOMAIN_TO_VARIANT[entry["domain"]]
    execution_variant = EXECUTION_TO_VARIANT[entry["execution"]]
    implemented = "True" if entry["implemented"] else "False"
    match_names = gleam_string_list(entry.get("matchNames", []))
    runtime_tests = gleam_string_list(entry.get("runtimeTests", []))
    support_notes = gleam_option(entry.get("supportNotes"))
    return (
        "    RegistryEntry(\n"
        f"      name: {name},\n"
        f"      type_: {type_variant},\n"
        f"      domain: {domain_variant},\n"
        f"      execution: {execution_variant},\n"
        f"      implemented: {implemented},\n"
        f"      match_names: {match_names},\n"
        f"      runtime_tests: {runtime_tests},\n"
        f"      support_notes: {support_notes},\n"
        "    )"
    )


with src_path.open() as f:
    entries = json.load(f)

used_domains = sorted({DOMAIN_TO_VARIANT[e["domain"]] for e in entries})
used_executions = sorted({EXECUTION_TO_VARIANT[e["execution"]] for e in entries})
used_types = sorted({TYPE_TO_VARIANT[e["type"]] for e in entries})
used_options = set()
if any(e.get("supportNotes") is not None for e in entries):
    used_options.add("Some")
if any(e.get("supportNotes") is None for e in entries):
    used_options.add("None")

registry_imports = sorted(
    {"type RegistryEntry", "RegistryEntry"}
    | set(used_domains)
    | set(used_executions)
    | set(used_types)
)

import_lines = (
    "import shopify_draft_proxy/proxy/operation_registry.{\n"
    "  " + ", ".join(registry_imports) + ",\n"
    "}\n"
)
if used_options:
    import_lines += (
        "import gleam/option.{" + ", ".join(sorted(used_options)) + "}\n"
    )

header = (
    "//// Generated by `scripts/sync-operation-registry.sh` from\n"
    "//// `config/operation-registry.json`. Do not edit by hand — re-run\n"
    "//// the script after editing the JSON. This file holds the\n"
    "//// vendored operation registry as a `List(RegistryEntry)` literal\n"
    "//// so the proxy carries it on every target without runtime IO.\n"
    "\n"
    + import_lines
    + "\n"
    "/// Vendored operation registry. Source of truth for the TS proxy is\n"
    "/// `config/operation-registry.json`; this list is regenerated from\n"
    "/// it via `sync-operation-registry.sh`. Once the TS proxy is\n"
    "/// retired, this becomes the source of truth.\n"
    "pub fn default_registry() -> List(RegistryEntry) {\n"
    "  [\n"
)

footer = "\n  ]\n}\n"

with dest_path.open("w") as f:
    f.write(header)
    f.write(",\n".join(render_entry(entry) for entry in entries))
    f.write(footer)

print(f"wrote {len(entries)} entries to {dest_path}")
PYEOF

(cd "$repo_root" && gleam format "$out")

if [[ "$mode" == "--check" ]]; then
  if ! cmp -s "$tmp" "$dest"; then
    echo "Gleam operation registry mirror is stale. Run scripts/sync-operation-registry.sh" >&2
    diff -u "$dest" "$tmp" >&2 || true
    exit 1
  fi
  echo "$dest is up to date"
fi
