mutation GiftCardUpdateClearNullable($id: ID!) {
  noteClear: giftCardUpdate(id: $id, input: { note: null }) {
    giftCard {
      id
      note
      expiresOn
      templateSuffix
      updatedAt
    }
    userErrors {
      field
      message
    }
  }
  expiresClear: giftCardUpdate(id: $id, input: { expiresOn: null }) {
    giftCard {
      id
      note
      expiresOn
      templateSuffix
      updatedAt
    }
    userErrors {
      field
      message
    }
  }
  templateClear: giftCardUpdate(id: $id, input: { templateSuffix: null }) {
    giftCard {
      id
      note
      expiresOn
      templateSuffix
      updatedAt
    }
    userErrors {
      field
      message
    }
  }
}
