mutation GiftCardUpdateNoop($id: ID!, $note: String!, $expiresOn: Date!, $templateSuffix: String!) {
  noteNoop: giftCardUpdate(id: $id, input: { note: $note }) {
    giftCard {
      id
      note
      updatedAt
    }
    userErrors {
      field
      message
    }
  }
  expiresNoop: giftCardUpdate(id: $id, input: { expiresOn: $expiresOn }) {
    giftCard {
      id
      expiresOn
      updatedAt
    }
    userErrors {
      field
      message
    }
  }
  templateNoop: giftCardUpdate(id: $id, input: { templateSuffix: $templateSuffix }) {
    giftCard {
      id
      templateSuffix
      updatedAt
    }
    userErrors {
      field
      message
    }
  }
  emptyInput: giftCardUpdate(id: $id, input: {}) {
    giftCard {
      id
      note
    }
    userErrors {
      field
      message
    }
  }
}
