use crate::graphql::OperationType;
use crate::operation_registry::{CapabilityDomain, OperationRegistryEntry};

macro_rules! entry {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $implemented:literal,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            $implemented,
            &[$($runtime_test),*],
        )
    };
}

macro_rules! entry_aliased {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $implemented:literal,
        [$($match_name:literal),* $(,)?],
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry_aliased(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            $implemented,
            &[$($match_name),*],
            &[$($runtime_test),*],
        )
    };
}

#[rustfmt::skip]
pub(crate) fn default_registry_entries() -> Vec<OperationRegistryEntry> {
    vec![
        entry!("product", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productByIdentifier", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("products", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productsCount", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariants", Query, Products, false, []),
        entry!("productVariantsCount", Query, Products, false, []),
        entry!("productTags", Query, Products, false, []),
        entry!("productTypes", Query, Products, false, []),
        entry!("productVendors", Query, Products, false, []),
        entry!("productOperation", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productDuplicateJob", Query, Products, false, []),
        entry!("productResourceFeedback", Query, Products, false, []),
        entry!("productFeed", Query, Products, false, []),
        entry!("productFeeds", Query, Products, false, []),
        entry!("sellingPlanGroup", Query, Products, true, []),
        entry!("sellingPlanGroups", Query, Products, true, []),
        entry!("publicApiVersions", Query, AdminPlatform, false, []),
        entry!("node", Query, AdminPlatform, true, []),
        entry!("nodes", Query, AdminPlatform, true, []),
        entry!("job", Query, AdminPlatform, true, ["tests/graphql_routes.rs"]),
        entry!("taxonomy", Query, AdminPlatform, false, []),
        entry!("domain", Query, AdminPlatform, true, ["tests/graphql_routes.rs"]),
        entry!("backupRegion", Query, AdminPlatform, true, []),
        entry!("backupRegionUpdate", Mutation, AdminPlatform, true, []),
        entry!("staffMember", Query, AdminPlatform, false, []),
        entry!("staffMembers", Query, AdminPlatform, false, []),
        entry!("flowGenerateSignature", Mutation, AdminPlatform, true, []),
        entry!("flowTriggerReceive", Mutation, AdminPlatform, true, []),
        entry!("app", Query, Apps, false, []),
        entry!("appByHandle", Query, Apps, false, []),
        entry!("appByKey", Query, Apps, false, []),
        entry!("appInstallation", Query, Apps, false, []),
        entry!("appInstallations", Query, Apps, false, []),
        entry!("currentAppInstallation", Query, Apps, true, []),
        entry!("appPurchaseOneTimeCreate", Mutation, Apps, true, []),
        entry!("appSubscriptionCreate", Mutation, Apps, true, []),
        entry!("appSubscriptionCancel", Mutation, Apps, true, []),
        entry!("appSubscriptionLineItemUpdate", Mutation, Apps, true, []),
        entry!("appSubscriptionTrialExtend", Mutation, Apps, true, []),
        entry!("appUsageRecordCreate", Mutation, Apps, true, []),
        entry!("appRevokeAccessScopes", Mutation, Apps, true, []),
        entry!("appUninstall", Mutation, Apps, true, []),
        entry!("delegateAccessTokenCreate", Mutation, Apps, true, []),
        entry!("delegateAccessTokenDestroy", Mutation, Apps, true, []),
        entry!("productVariant", Query, Products, true, ["tests/graphql_routes/products_saved_searches.rs"]),
        entry!("productVariantByIdentifier", Query, Products, false, []),
        entry!("inventoryItem", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryItems", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipment", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryLevel", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryProperties", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransfer", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransfers", Query, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collection", Query, StoreProperties, true, []),
        entry!("collectionByIdentifier", Query, Products, false, []),
        entry!("collectionByHandle", Query, Products, false, []),
        entry!("collections", Query, Products, true, []),
        entry!("locations", Query, Products, false, []),
        entry!("shop", Query, StoreProperties, true, ["tests/graphql_routes.rs"]),
        entry!("location", Query, StoreProperties, true, []),
        entry!("locationByIdentifier", Query, StoreProperties, true, []),
        entry!("businessEntities", Query, StoreProperties, false, []),
        entry!("businessEntity", Query, StoreProperties, false, []),
        entry!("companies", Query, B2b, true, []),
        entry!("companiesCount", Query, B2b, false, []),
        entry!("company", Query, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyContact", Query, B2b, true, []),
        entry!("companyContactRole", Query, B2b, false, []),
        entry!("companyLocation", Query, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocations", Query, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companiesDelete", Mutation, B2b, true, []),
        entry!("companyAddressDelete", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyAssignCustomerAsContact", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyAssignMainContact", Mutation, B2b, true, []),
        entry!("companyContactAssignRole", Mutation, B2b, true, []),
        entry!("companyContactAssignRoles", Mutation, B2b, true, []),
        entry!("companyContactCreate", Mutation, B2b, true, []),
        entry!("companyContactDelete", Mutation, B2b, true, []),
        entry!("companyContactRemoveFromCompany", Mutation, B2b, true, []),
        entry!("companyContactRevokeRole", Mutation, B2b, true, []),
        entry!("companyContactRevokeRoles", Mutation, B2b, true, []),
        entry!("companyContactsDelete", Mutation, B2b, true, []),
        entry!("companyContactSendWelcomeEmail", Mutation, B2b, false, []),
        entry!("companyContactUpdate", Mutation, B2b, true, []),
        entry!("companyCreate", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyDelete", Mutation, B2b, true, []),
        entry!("companyLocationAssignAddress", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationAssignRoles", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationAssignStaffMembers", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationCreate", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationDelete", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationRemoveStaffMembers", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationRevokeRoles", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationsDelete", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationTaxSettingsUpdate", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationUpdate", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("companyRevokeMainContact", Mutation, B2b, true, []),
        entry!("companyUpdate", Mutation, B2b, true, ["tests/graphql_routes.rs"]),
        entry!("cashManagementLocationSummary", Query, StoreProperties, false, []),
        entry!("cashTrackingSession", Query, Payments, true, []),
        entry!("cashTrackingSessions", Query, Payments, true, []),
        entry!("customerPaymentMethod", Query, Payments, true, []),
        entry!("orderPaymentStatus", Query, Payments, false, []),
        entry!("paymentCustomization", Query, Payments, true, []),
        entry!("paymentCustomizations", Query, Payments, true, []),
        entry!("validation", Query, Functions, true, []),
        entry!("validations", Query, Functions, true, []),
        entry!("cartTransforms", Query, Functions, true, []),
        entry!("shopifyFunction", Query, Functions, true, []),
        entry!("shopifyFunctions", Query, Functions, true, []),
        entry!("paymentTermsTemplates", Query, Payments, true, ["tests/graphql_routes/orders.rs"]),
        entry!("financeAppAccessPolicy", Query, Payments, false, []),
        entry!("financeKycInformation", Query, Payments, false, []),
        entry!("pointOfSaleDevice", Query, Payments, true, []),
        entry!("dispute", Query, Payments, true, []),
        entry!("disputes", Query, Payments, true, []),
        entry!("disputeEvidence", Query, Payments, true, []),
        entry!("shopPayPaymentRequestReceipt", Query, Payments, true, []),
        entry!("shopPayPaymentRequestReceipts", Query, Payments, true, []),
        entry!("shopifyPaymentsAccount", Query, Payments, true, []),
        entry!("tenderTransactions", Query, Payments, false, []),
        entry!("channel", Query, Products, true, []),
        entry!("channels", Query, Products, true, []),
        entry!("publication", Query, Products, true, []),
        entry!("publications", Query, Products, false, []),
        entry!("publicationsCount", Query, Products, true, []),
        entry!("publishedProductsCount", Query, Products, true, []),
        entry!("storeCreditAccount", Query, Customers, true, []),
        entry!("customer", Query, Customers, true, []),
        entry!("customerAccountPage", Query, Customers, false, []),
        entry!("event", Query, Events, true, []),
        entry!("events", Query, Events, true, []),
        entry!("eventsCount", Query, Events, true, []),
        entry!("customers", Query, Customers, true, []),
        entry!("customerAccountPages", Query, Customers, false, []),
        entry!("customersCount", Query, Customers, true, []),
        entry!("customerByIdentifier", Query, Customers, true, []),
        entry!("customerMergePreview", Query, Customers, false, []),
        entry!("customerMergeJobStatus", Query, Customers, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerCreate", Mutation, Customers, true, []),
        entry!("customerUpdate", Mutation, Customers, true, []),
        entry!("customerDelete", Mutation, Customers, true, []),
        entry!("customerRequestDataErasure", Mutation, Customers, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerCancelDataErasure", Mutation, Customers, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerAddressCreate", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddressUpdate", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddressDelete", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerUpdateDefaultAddress", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerEmailMarketingConsentUpdate", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerSmsMarketingConsentUpdate", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddTaxExemptions", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerRemoveTaxExemptions", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerReplaceTaxExemptions", Mutation, Customers, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerSet", Mutation, Customers, true, []),
        entry!("customerGenerateAccountActivationUrl", Mutation, Customers, false, []),
        entry!("customerSendAccountInviteEmail", Mutation, Customers, false, []),
        entry!("storeCreditAccountCredit", Mutation, Customers, true, []),
        entry!("storeCreditAccountDebit", Mutation, Customers, true, []),
        entry!("customerPaymentMethodSendUpdateEmail", Mutation, Customers, false, []),
        entry!("customerMerge", Mutation, Customers, true, []),
        entry!("sellingPlanGroupCreate", Mutation, Products, true, []),
        entry!("sellingPlanGroupUpdate", Mutation, Products, true, []),
        entry!("sellingPlanGroupDelete", Mutation, Products, true, []),
        entry!("sellingPlanGroupAddProducts", Mutation, Products, true, []),
        entry!("sellingPlanGroupRemoveProducts", Mutation, Products, true, []),
        entry!("sellingPlanGroupAddProductVariants", Mutation, Products, true, []),
        entry!("sellingPlanGroupRemoveProductVariants", Mutation, Products, true, []),
        entry!("productJoinSellingPlanGroups", Mutation, Products, true, []),
        entry!("productLeaveSellingPlanGroups", Mutation, Products, true, []),
        entry!("productVariantJoinSellingPlanGroups", Mutation, Products, true, []),
        entry!("productVariantLeaveSellingPlanGroups", Mutation, Products, true, []),
        entry_aliased!("tagsAdd", Mutation, Products, true, ["tagsAdd"], ["tests/graphql_routes.rs"]),
        entry_aliased!("tagsRemove", Mutation, Products, true, ["tagsRemove"], ["tests/graphql_routes.rs"]),
        entry!("bulkProductResourceFeedbackCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("shopResourceFeedbackCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productDuplicate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productSet", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productChangeStatus", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productFeedCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productFeedDelete", Mutation, Products, false, []),
        entry!("productFullSync", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productBundleCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productBundleUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("combinedListingUpdate", Mutation, Products, false, []),
        entry!("publicationCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("publicationUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("publicationDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productPublish", Mutation, Products, true, ["tests/graphql_routes/products_saved_searches.rs"]),
        entry!("productUnpublish", Mutation, Products, true, ["tests/graphql_routes/products_saved_searches.rs"]),
        entry!("locationAdd", Mutation, StoreProperties, true, []),
        entry!("locationEdit", Mutation, StoreProperties, true, []),
        entry!("locationActivate", Mutation, StoreProperties, true, []),
        entry!("locationDeactivate", Mutation, StoreProperties, true, []),
        entry!("locationDelete", Mutation, StoreProperties, true, ["tests/graphql_routes.rs"]),
        entry!("publishablePublish", Mutation, StoreProperties, true, []),
        entry!("publishablePublishToCurrentChannel", Mutation, StoreProperties, true, []),
        entry!("publishableUnpublish", Mutation, StoreProperties, true, []),
        entry!("publishableUnpublishToCurrentChannel", Mutation, StoreProperties, true, []),
        entry!("shopPolicyUpdate", Mutation, StoreProperties, true, ["tests/graphql_routes.rs"]),
        entry!("productSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("collectionSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("customerSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("orderSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("fileSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("codeDiscountSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("automaticDiscountSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("discountRedeemCodeSavedSearches", Query, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("savedSearchCreate", Mutation, SavedSearches, true, ["tests/graphql_routes.rs"]),
        entry!("savedSearchUpdate", Mutation, SavedSearches, true, []),
        entry!("savedSearchDelete", Mutation, SavedSearches, true, []),
        entry!("urlRedirectSavedSearches", Query, OnlineStore, false, []),
        entry!("urlRedirect", Query, OnlineStore, false, []),
        entry!("urlRedirects", Query, OnlineStore, false, []),
        entry!("urlRedirectsCount", Query, OnlineStore, false, []),
        entry!("urlRedirectCreate", Mutation, OnlineStore, false, []),
        entry!("urlRedirectUpdate", Mutation, OnlineStore, false, []),
        entry!("urlRedirectDelete", Mutation, OnlineStore, false, []),
        entry!("urlRedirectBulkDeleteAll", Mutation, OnlineStore, false, []),
        entry!("urlRedirectBulkDeleteByIds", Mutation, OnlineStore, false, []),
        entry!("urlRedirectBulkDeleteBySavedSearch", Mutation, OnlineStore, false, []),
        entry!("urlRedirectBulkDeleteBySearch", Mutation, OnlineStore, false, []),
        entry!("urlRedirectImportCreate", Mutation, OnlineStore, false, []),
        entry!("urlRedirectImportSubmit", Mutation, OnlineStore, false, []),
        entry!("article", Query, OnlineStore, true, []),
        entry!("articleAuthors", Query, OnlineStore, true, []),
        entry!("articles", Query, OnlineStore, true, []),
        entry!("articleTags", Query, OnlineStore, true, []),
        entry!("articleCreate", Mutation, OnlineStore, true, []),
        entry!("articleUpdate", Mutation, OnlineStore, true, []),
        entry!("articleDelete", Mutation, OnlineStore, true, []),
        entry!("blog", Query, OnlineStore, true, []),
        entry!("blogs", Query, OnlineStore, true, []),
        entry!("blogsCount", Query, OnlineStore, true, []),
        entry!("blogCreate", Mutation, OnlineStore, true, []),
        entry!("blogUpdate", Mutation, OnlineStore, true, []),
        entry!("blogDelete", Mutation, OnlineStore, true, []),
        entry!("page", Query, OnlineStore, true, []),
        entry!("pages", Query, OnlineStore, true, []),
        entry!("pagesCount", Query, OnlineStore, true, []),
        entry!("pageCreate", Mutation, OnlineStore, true, []),
        entry!("pageUpdate", Mutation, OnlineStore, true, []),
        entry!("pageDelete", Mutation, OnlineStore, true, []),
        entry!("comment", Query, OnlineStore, true, []),
        entry!("comments", Query, OnlineStore, true, []),
        entry!("commentApprove", Mutation, OnlineStore, true, []),
        entry!("commentSpam", Mutation, OnlineStore, true, []),
        entry!("commentNotSpam", Mutation, OnlineStore, true, []),
        entry!("commentDelete", Mutation, OnlineStore, true, []),
        entry!("menu", Query, OnlineStore, false, []),
        entry!("menus", Query, OnlineStore, false, []),
        entry!("theme", Query, OnlineStore, true, []),
        entry!("themes", Query, OnlineStore, true, []),
        entry!("scriptTag", Query, OnlineStore, true, []),
        entry!("scriptTags", Query, OnlineStore, true, []),
        entry!("webPixel", Query, OnlineStore, true, []),
        entry!("serverPixel", Query, OnlineStore, true, []),
        entry!("mobilePlatformApplication", Query, OnlineStore, true, []),
        entry!("mobilePlatformApplications", Query, OnlineStore, true, []),
        entry!("menuCreate", Mutation, OnlineStore, false, []),
        entry!("menuUpdate", Mutation, OnlineStore, false, []),
        entry!("menuDelete", Mutation, OnlineStore, false, []),
        entry!("themeCreate", Mutation, OnlineStore, true, []),
        entry!("themeUpdate", Mutation, OnlineStore, true, []),
        entry!("themeDelete", Mutation, OnlineStore, true, []),
        entry!("themePublish", Mutation, OnlineStore, true, []),
        entry!("themeFilesCopy", Mutation, OnlineStore, true, []),
        entry!("themeFilesUpsert", Mutation, OnlineStore, true, []),
        entry!("themeFilesDelete", Mutation, OnlineStore, true, []),
        entry!("scriptTagCreate", Mutation, OnlineStore, true, []),
        entry!("scriptTagUpdate", Mutation, OnlineStore, true, []),
        entry!("scriptTagDelete", Mutation, OnlineStore, true, []),
        entry!("webPixelCreate", Mutation, OnlineStore, true, []),
        entry!("webPixelUpdate", Mutation, OnlineStore, true, []),
        entry!("webPixelDelete", Mutation, OnlineStore, false, []),
        entry!("serverPixelCreate", Mutation, OnlineStore, true, []),
        entry!("serverPixelDelete", Mutation, OnlineStore, false, []),
        entry!("eventBridgeServerPixelUpdate", Mutation, OnlineStore, true, []),
        entry!("pubSubServerPixelUpdate", Mutation, OnlineStore, true, []),
        entry!("storefrontAccessTokenCreate", Mutation, OnlineStore, true, []),
        entry!("storefrontAccessTokenDelete", Mutation, OnlineStore, false, []),
        entry!("mobilePlatformApplicationCreate", Mutation, OnlineStore, true, []),
        entry!("mobilePlatformApplicationUpdate", Mutation, OnlineStore, true, []),
        entry!("mobilePlatformApplicationDelete", Mutation, OnlineStore, false, []),
        entry!("privacySettings", Query, Privacy, false, []),
        entry!("consentPolicy", Query, Privacy, false, []),
        entry!("consentPolicyRegions", Query, Privacy, false, []),
        entry!("consentPolicyUpdate", Mutation, Privacy, false, []),
        entry!("privacyFeaturesDisable", Mutation, Privacy, false, []),
        entry!("dataSaleOptOut", Mutation, Privacy, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("bulkOperation", Query, BulkOperations, true, []),
        entry!("bulkOperations", Query, BulkOperations, true, []),
        entry!("currentBulkOperation", Query, BulkOperations, true, []),
        entry!("bulkOperationRunQuery", Mutation, BulkOperations, true, []),
        entry!("bulkOperationRunMutation", Mutation, BulkOperations, true, []),
        entry!("bulkOperationCancel", Mutation, BulkOperations, true, []),
        entry!("productOptionsCreate", Mutation, Products, true, []),
        entry!("productOptionUpdate", Mutation, Products, true, []),
        entry!("productOptionsDelete", Mutation, Products, true, []),
        entry!("productOptionsReorder", Mutation, Products, true, []),
        entry!("productVariantsBulkCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantsBulkUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantsBulkDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantsBulkReorder", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productCreateMedia", Mutation, Products, true, []),
        entry!("productUpdateMedia", Mutation, Products, true, []),
        entry!("productDeleteMedia", Mutation, Products, true, []),
        entry!("productReorderMedia", Mutation, Products, true, []),
        entry!("productVariantAppendMedia", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantDetachMedia", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("productVariantRelationshipBulkUpdate", Mutation, Products, false, []),
        entry!("inventoryItemUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryAdjustQuantities", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventorySetQuantities", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventorySetOnHandQuantities", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryMoveQuantities", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryActivate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryDeactivate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryBulkToggleActivation", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferCreateAsReadyToShip", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferEdit", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferSetItems", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferRemoveItems", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferMarkAsReadyToShip", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferDuplicate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferCancel", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentCreateInTransit", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentAddItems", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentRemoveItems", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentUpdateItemQuantities", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentSetTracking", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentMarkInTransit", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentReceive", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("metafieldsSet", Mutation, Products, true, []),
        entry!("metafieldsDelete", Mutation, Products, true, []),
        entry!("metafieldDelete", Mutation, Products, true, []),
        entry!("metafieldDefinition", Query, Metafields, true, []),
        entry!("metafieldDefinitions", Query, Metafields, true, []),
        entry!("standardMetafieldDefinitionTemplates", Query, Metafields, false, []),
        entry!("metafieldDefinitionCreate", Mutation, Metafields, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionUpdate", Mutation, Metafields, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionDelete", Mutation, Metafields, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionPin", Mutation, Metafields, true, []),
        entry!("metafieldDefinitionUnpin", Mutation, Metafields, true, []),
        entry!("standardMetafieldDefinitionEnable", Mutation, Metafields, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metaobject", Query, Metaobjects, true, []),
        entry!("metaobjectByHandle", Query, Metaobjects, true, []),
        entry!("metaobjects", Query, Metaobjects, true, []),
        entry!("metaobjectDefinition", Query, Metaobjects, true, []),
        entry!("metaobjectDefinitionByType", Query, Metaobjects, true, []),
        entry!("metaobjectDefinitions", Query, Metaobjects, true, []),
        entry!("metaobjectCreate", Mutation, Metaobjects, true, []),
        entry!("metaobjectUpdate", Mutation, Metaobjects, true, []),
        entry!("metaobjectUpsert", Mutation, Metaobjects, true, []),
        entry!("metaobjectDelete", Mutation, Metaobjects, true, []),
        entry!("metaobjectBulkDelete", Mutation, Metaobjects, false, []),
        entry!("metaobjectDefinitionCreate", Mutation, Metaobjects, true, []),
        entry!("metaobjectDefinitionUpdate", Mutation, Metaobjects, true, []),
        entry!("metaobjectDefinitionDelete", Mutation, Metaobjects, true, []),
        entry!("standardMetaobjectDefinitionEnable", Mutation, Metaobjects, false, []),
        entry!("collectionCreate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collectionUpdate", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collectionDelete", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collectionAddProducts", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collectionAddProductsV2", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collectionRemoveProducts", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("collectionReorderProducts", Mutation, Products, true, ["tests/graphql_routes.rs"]),
        entry!("order", Query, Orders, true, []),
        entry!("return", Query, Orders, true, []),
        entry!("orders", Query, Orders, true, []),
        entry!("ordersCount", Query, Orders, true, []),
        entry!("returnCalculate", Query, Orders, false, []),
        entry!("returnableFulfillment", Query, Orders, false, []),
        entry!("returnableFulfillments", Query, Orders, false, []),
        entry!("reverseDelivery", Query, ShippingFulfillments, true, []),
        entry!("reverseFulfillmentOrder", Query, ShippingFulfillments, true, []),
        entry!("abandonedCheckouts", Query, Orders, false, []),
        entry!("abandonedCheckoutsCount", Query, Orders, false, []),
        entry!("abandonment", Query, Orders, true, []),
        entry!("abandonmentByAbandonedCheckoutId", Query, Orders, false, []),
        entry!("orderUpdate", Mutation, Orders, true, []),
        entry!("orderClose", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("orderOpen", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("orderMarkAsPaid", Mutation, Orders, true, []),
        entry!("orderCreateManualPayment", Mutation, Orders, false, []),
        entry!("orderRiskAssessmentCreate", Mutation, Orders, false, []),
        entry!("customerPaymentMethodCreateFromDuplicationData", Mutation, Payments, true, []),
        entry!("customerPaymentMethodCreditCardCreate", Mutation, Payments, true, []),
        entry!("customerPaymentMethodCreditCardUpdate", Mutation, Payments, true, []),
        entry!("customerPaymentMethodGetDuplicationData", Mutation, Payments, true, []),
        entry!("customerPaymentMethodGetUpdateUrl", Mutation, Payments, true, []),
        entry!("customerPaymentMethodPaypalBillingAgreementCreate", Mutation, Payments, true, []),
        entry!("customerPaymentMethodPaypalBillingAgreementUpdate", Mutation, Payments, true, []),
        entry!("customerPaymentMethodRemoteCreate", Mutation, Payments, true, []),
        entry!("customerPaymentMethodRevoke", Mutation, Payments, true, []),
        entry!("orderCapture", Mutation, Payments, true, []),
        entry!("orderCreateMandatePayment", Mutation, Payments, true, []),
        entry!("paymentCustomizationActivation", Mutation, Payments, true, []),
        entry!("paymentCustomizationCreate", Mutation, Payments, true, []),
        entry!("paymentCustomizationDelete", Mutation, Payments, true, []),
        entry!("paymentCustomizationUpdate", Mutation, Payments, true, []),
        entry!("validationCreate", Mutation, Functions, true, []),
        entry!("validationUpdate", Mutation, Functions, true, []),
        entry!("validationDelete", Mutation, Functions, true, []),
        entry!("cartTransformCreate", Mutation, Functions, true, []),
        entry!("cartTransformDelete", Mutation, Functions, true, []),
        entry!("taxAppConfigure", Mutation, Functions, true, []),
        entry!("paymentReminderSend", Mutation, Payments, true, []),
        entry!("paymentTermsCreate", Mutation, Payments, true, []),
        entry!("paymentTermsDelete", Mutation, Payments, true, []),
        entry!("paymentTermsUpdate", Mutation, Payments, true, []),
        entry!("disputeEvidenceUpdate", Mutation, Payments, false, []),
        entry!("shopifyPaymentsPayoutAlternateCurrencyCreate", Mutation, Payments, false, []),
        entry!("transactionVoid", Mutation, Payments, true, []),
        entry!("orderCustomerSet", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("orderCustomerRemove", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("orderInvoiceSend", Mutation, Orders, false, []),
        entry!("taxSummaryCreate", Mutation, Orders, false, []),
        entry!("orderCancel", Mutation, Orders, true, []),
        entry!("fulfillmentCreate", Mutation, Orders, true, []),
        entry!("fulfillmentTrackingInfoUpdate", Mutation, Orders, true, []),
        entry!("fulfillmentCancel", Mutation, Orders, true, []),
        entry!("fulfillment", Query, Orders, true, ["tests/graphql_routes/orders.rs"]),
        entry!("fulfillmentEventCreate", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("assignedFulfillmentOrders", Query, ShippingFulfillments, true, []),
        entry!("fulfillmentOrder", Query, ShippingFulfillments, true, []),
        entry!("fulfillmentOrders", Query, ShippingFulfillments, true, []),
        entry!("manualHoldsFulfillmentOrders", Query, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderAcceptCancellationRequest", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderAcceptFulfillmentRequest", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderCancel", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderClose", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderHold", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderLineItemsPreparedForPickup", Mutation, ShippingFulfillments, false, []),
        entry!("fulfillmentOrderMerge", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderMove", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderOpen", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderRejectCancellationRequest", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderRejectFulfillmentRequest", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderReleaseHold", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderReportProgress", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderReschedule", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrdersReroute", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrdersSetFulfillmentDeadline", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderSplit", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderSubmitCancellationRequest", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentOrderSubmitFulfillmentRequest", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentService", Query, ShippingFulfillments, true, []),
        entry!("fulfillmentServiceCreate", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentServiceDelete", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentServiceUpdate", Mutation, ShippingFulfillments, true, []),
        entry!("availableCarrierServices", Query, ShippingFulfillments, true, []),
        entry!("carrierService", Query, ShippingFulfillments, true, []),
        entry!("carrierServices", Query, ShippingFulfillments, true, []),
        entry!("carrierServiceCreate", Mutation, ShippingFulfillments, true, []),
        entry!("carrierServiceDelete", Mutation, ShippingFulfillments, true, []),
        entry!("carrierServiceUpdate", Mutation, ShippingFulfillments, true, []),
        entry!("giftCard", Query, GiftCards, true, []),
        entry!("giftCards", Query, GiftCards, true, []),
        entry!("giftCardsCount", Query, GiftCards, true, []),
        entry!("giftCardConfiguration", Query, GiftCards, true, []),
        entry!("giftCardCreate", Mutation, GiftCards, true, []),
        entry!("giftCardUpdate", Mutation, GiftCards, true, []),
        entry!("giftCardCredit", Mutation, GiftCards, true, []),
        entry!("giftCardDebit", Mutation, GiftCards, true, []),
        entry!("giftCardDeactivate", Mutation, GiftCards, true, []),
        entry!("giftCardSendNotificationToCustomer", Mutation, GiftCards, true, []),
        entry!("giftCardSendNotificationToRecipient", Mutation, GiftCards, true, []),
        entry!("deliveryCustomization", Query, ShippingFulfillments, false, []),
        entry!("deliveryCustomizations", Query, ShippingFulfillments, false, []),
        entry!("deliveryPromiseParticipants", Query, ShippingFulfillments, false, []),
        entry!("deliveryPromiseProvider", Query, ShippingFulfillments, false, []),
        entry!("deliveryPromiseSettings", Query, ShippingFulfillments, true, []),
        entry!("deliverySettings", Query, ShippingFulfillments, true, []),
        entry!("deliveryProfile", Query, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfiles", Query, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationsAvailableForDeliveryProfilesConnection", Query, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationLocalPickupDisable", Mutation, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationLocalPickupEnable", Mutation, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("shippingPackageDelete", Mutation, ShippingFulfillments, true, []),
        entry!("shippingPackageMakeDefault", Mutation, ShippingFulfillments, true, []),
        entry!("shippingPackageUpdate", Mutation, ShippingFulfillments, true, []),
        entry!("fulfillmentConstraintRules", Query, Functions, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleCreate", Mutation, Functions, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleDelete", Mutation, Functions, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleUpdate", Mutation, Functions, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("deliveryProfileCreate", Mutation, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfileRemove", Mutation, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfileUpdate", Mutation, ShippingFulfillments, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationActivation", Mutation, ShippingFulfillments, false, []),
        entry!("deliveryCustomizationCreate", Mutation, ShippingFulfillments, false, []),
        entry!("deliveryCustomizationDelete", Mutation, ShippingFulfillments, false, []),
        entry!("deliveryCustomizationUpdate", Mutation, ShippingFulfillments, false, []),
        entry!("deliveryPromiseParticipantsUpdate", Mutation, ShippingFulfillments, false, []),
        entry!("deliveryPromiseProviderUpsert", Mutation, ShippingFulfillments, false, []),
        entry!("deliverySettingUpdate", Mutation, ShippingFulfillments, false, []),
        entry!("orderEditAddShippingLine", Mutation, Orders, true, []),
        entry!("orderEditRemoveShippingLine", Mutation, Orders, true, []),
        entry!("orderEditUpdateShippingLine", Mutation, Orders, true, []),
        entry!("orderDelete", Mutation, Orders, true, []),
        entry!("orderEditAddCustomItem", Mutation, Orders, true, []),
        entry!("orderEditAddLineItemDiscount", Mutation, Orders, true, []),
        entry!("orderEditRemoveDiscount", Mutation, Orders, true, []),
        entry!("orderCreate", Mutation, Orders, true, []),
        entry!("abandonmentUpdateActivitiesDeliveryStatuses", Mutation, Orders, true, []),
        entry!("refundCreate", Mutation, Orders, true, []),
        entry!("returnCreate", Mutation, Orders, true, []),
        entry!("returnRequest", Mutation, Orders, true, []),
        entry!("returnApproveRequest", Mutation, Orders, true, []),
        entry!("returnDeclineRequest", Mutation, Orders, true, []),
        entry!("returnCancel", Mutation, Orders, true, []),
        entry!("returnClose", Mutation, Orders, true, []),
        entry!("returnReopen", Mutation, Orders, true, []),
        entry!("removeFromReturn", Mutation, Orders, true, []),
        entry!("returnProcess", Mutation, Orders, true, []),
        entry!("reverseDeliveryCreateWithShipping", Mutation, ShippingFulfillments, true, []),
        entry!("reverseDeliveryShippingUpdate", Mutation, ShippingFulfillments, true, []),
        entry!("reverseFulfillmentOrderDispose", Mutation, ShippingFulfillments, true, []),
        entry!("draftOrder", Query, Orders, true, []),
        entry!("draftOrders", Query, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrdersCount", Query, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderAvailableDeliveryOptions", Query, Orders, false, []),
        entry!("draftOrderTag", Query, Orders, false, []),
        entry!("draftOrderCreate", Mutation, Orders, true, []),
        entry!("draftOrderComplete", Mutation, Orders, true, []),
        entry!("draftOrderUpdate", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderDuplicate", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderBulkAddTags", Mutation, Orders, true, []),
        entry!("draftOrderBulkRemoveTags", Mutation, Orders, true, []),
        entry!("draftOrderBulkDelete", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderDelete", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderCalculate", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderInvoicePreview", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderInvoiceSend", Mutation, Orders, true, []),
        entry!("draftOrderCreateFromOrder", Mutation, Orders, true, ["tests/graphql_routes.rs"]),
        entry!("orderEditBegin", Mutation, Orders, true, []),
        entry!("orderEditAddVariant", Mutation, Orders, true, []),
        entry!("orderEditSetQuantity", Mutation, Orders, true, []),
        entry!("orderEditCommit", Mutation, Orders, true, []),
        entry!("discountNodes", Query, Discounts, true, []),
        entry!("discountNodesCount", Query, Discounts, true, []),
        entry!("discountNode", Query, Discounts, true, []),
        entry!("codeDiscountNodes", Query, Discounts, false, []),
        entry!("codeDiscountNode", Query, Discounts, true, []),
        entry!("codeDiscountNodeByCode", Query, Discounts, true, []),
        entry!("discountRedeemCodeBulkCreation", Query, Discounts, true, []),
        entry!("automaticDiscountNodes", Query, Discounts, true, []),
        entry!("automaticDiscountNode", Query, Discounts, true, []),
        entry!("discountCodeBasicCreate", Mutation, Discounts, true, []),
        entry!("discountCodeBasicUpdate", Mutation, Discounts, true, []),
        entry!("discountCodeBxgyCreate", Mutation, Discounts, true, []),
        entry!("discountCodeBxgyUpdate", Mutation, Discounts, true, []),
        entry!("discountCodeFreeShippingCreate", Mutation, Discounts, true, []),
        entry!("discountCodeFreeShippingUpdate", Mutation, Discounts, true, []),
        entry!("discountCodeActivate", Mutation, Discounts, true, []),
        entry!("discountCodeDeactivate", Mutation, Discounts, true, []),
        entry!("discountCodeDelete", Mutation, Discounts, true, []),
        entry!("discountCodeBulkActivate", Mutation, Discounts, false, []),
        entry!("discountCodeBulkDeactivate", Mutation, Discounts, false, []),
        entry!("discountCodeBulkDelete", Mutation, Discounts, false, []),
        entry!("discountRedeemCodeBulkAdd", Mutation, Discounts, true, []),
        entry_aliased!("discountCodeRedeemCodeBulkDelete", Mutation, Discounts, true, ["discountCodeRedeemCodeBulkDelete", "DiscountCodeRedeemCodeBulkDelete", "discountRedeemCodeBulkDelete", "DiscountRedeemCodeBulkDelete",], []),
        entry!("discountAutomaticBasicCreate", Mutation, Discounts, true, []),
        entry!("discountAutomaticBasicUpdate", Mutation, Discounts, true, []),
        entry!("discountAutomaticBxgyCreate", Mutation, Discounts, true, []),
        entry!("discountAutomaticBxgyUpdate", Mutation, Discounts, true, []),
        entry!("discountAutomaticFreeShippingCreate", Mutation, Discounts, true, []),
        entry!("discountAutomaticFreeShippingUpdate", Mutation, Discounts, true, []),
        entry!("discountAutomaticActivate", Mutation, Discounts, true, []),
        entry!("discountAutomaticDeactivate", Mutation, Discounts, true, []),
        entry!("discountAutomaticDelete", Mutation, Discounts, true, []),
        entry!("discountAutomaticBulkDelete", Mutation, Discounts, false, []),
        entry!("discountCodeAppCreate", Mutation, Discounts, true, []),
        entry!("discountCodeAppUpdate", Mutation, Discounts, true, []),
        entry!("discountAutomaticAppCreate", Mutation, Discounts, true, []),
        entry!("discountAutomaticAppUpdate", Mutation, Discounts, true, []),
        entry!("marketingActivities", Query, Marketing, true, []),
        entry!("marketingActivity", Query, Marketing, true, []),
        entry!("marketingEvent", Query, Marketing, true, []),
        entry!("marketingEvents", Query, Marketing, true, []),
        entry!("marketingActivityCreate", Mutation, Marketing, true, []),
        entry!("marketingActivityUpdate", Mutation, Marketing, true, []),
        entry!("marketingActivityCreateExternal", Mutation, Marketing, true, []),
        entry!("marketingActivityUpdateExternal", Mutation, Marketing, true, []),
        entry!("marketingActivityUpsertExternal", Mutation, Marketing, true, []),
        entry!("marketingActivityDeleteExternal", Mutation, Marketing, true, []),
        entry!("marketingActivitiesDeleteAllExternal", Mutation, Marketing, true, []),
        entry!("marketingEngagementCreate", Mutation, Marketing, true, []),
        entry!("marketingEngagementsDelete", Mutation, Marketing, true, []),
        entry!("webhookSubscription", Query, Webhooks, true, []),
        entry!("webhookSubscriptions", Query, Webhooks, true, []),
        entry!("webhookSubscriptionsCount", Query, Webhooks, true, []),
        entry!("eventBridgeWebhookSubscriptionCreate", Mutation, Webhooks, true, []),
        entry!("eventBridgeWebhookSubscriptionUpdate", Mutation, Webhooks, true, []),
        entry!("pubSubWebhookSubscriptionCreate", Mutation, Webhooks, true, []),
        entry!("pubSubWebhookSubscriptionUpdate", Mutation, Webhooks, true, []),
        entry!("webhookSubscriptionCreate", Mutation, Webhooks, true, []),
        entry!("webhookSubscriptionUpdate", Mutation, Webhooks, true, []),
        entry!("webhookSubscriptionDelete", Mutation, Webhooks, true, []),
        entry!("segment", Query, Segments, true, []),
        entry!("segments", Query, Segments, true, []),
        entry!("segmentsCount", Query, Segments, true, []),
        entry!("segmentFilters", Query, Segments, false, []),
        entry!("segmentFilterSuggestions", Query, Segments, false, []),
        entry!("segmentValueSuggestions", Query, Segments, false, []),
        entry!("segmentMigrations", Query, Segments, false, []),
        entry!("customerSegmentMembers", Query, Segments, false, []),
        entry!("customerSegmentMembersQuery", Query, Segments, true, []),
        entry!("customerSegmentMembership", Query, Segments, false, []),
        entry!("customerSegmentMembersQueryCreate", Mutation, Segments, true, []),
        entry!("segmentCreate", Mutation, Segments, true, []),
        entry!("segmentUpdate", Mutation, Segments, true, []),
        entry!("segmentDelete", Mutation, Segments, true, []),
        entry!("market", Query, Markets, true, []),
        entry!("markets", Query, Markets, true, []),
        entry!("catalog", Query, Markets, true, []),
        entry!("catalogs", Query, Markets, true, []),
        entry!("catalogsCount", Query, Markets, true, []),
        entry!("priceList", Query, Markets, true, []),
        entry!("priceLists", Query, Markets, true, []),
        entry!("priceListCreate", Mutation, Markets, true, []),
        entry!("priceListUpdate", Mutation, Markets, true, []),
        entry!("priceListDelete", Mutation, Markets, true, []),
        entry!("priceListFixedPricesAdd", Mutation, Markets, true, []),
        entry!("priceListFixedPricesUpdate", Mutation, Markets, true, []),
        entry!("priceListFixedPricesDelete", Mutation, Markets, true, []),
        entry!("priceListFixedPricesByProductUpdate", Mutation, Markets, true, []),
        entry!("quantityPricingByVariantUpdate", Mutation, Markets, true, []),
        entry!("quantityRulesAdd", Mutation, Markets, true, []),
        entry!("quantityRulesDelete", Mutation, Markets, true, []),
        entry!("webPresences", Query, Markets, true, []),
        entry!("marketsResolvedValues", Query, Markets, true, []),
        entry!("marketLocalizableResource", Query, Markets, true, []),
        entry!("marketLocalizableResources", Query, Markets, true, []),
        entry!("marketLocalizableResourcesByIds", Query, Markets, false, []),
        entry!("marketCreate", Mutation, Markets, true, []),
        entry!("marketUpdate", Mutation, Markets, true, []),
        entry!("marketDelete", Mutation, Markets, true, []),
        entry!("catalogCreate", Mutation, Markets, true, []),
        entry!("catalogUpdate", Mutation, Markets, true, []),
        entry!("catalogContextUpdate", Mutation, Markets, true, []),
        entry!("catalogDelete", Mutation, Markets, true, []),
        entry!("webPresenceCreate", Mutation, Markets, true, []),
        entry!("webPresenceUpdate", Mutation, Markets, true, []),
        entry!("webPresenceDelete", Mutation, Markets, true, []),
        entry!("marketLocalizationsRegister", Mutation, Markets, true, []),
        entry!("marketLocalizationsRemove", Mutation, Markets, true, []),
        entry!("availableLocales", Query, Localization, true, []),
        entry!("shopLocales", Query, Localization, true, []),
        entry!("translatableResource", Query, Localization, true, []),
        entry!("translatableResources", Query, Localization, true, []),
        entry!("translatableResourcesByIds", Query, Localization, true, []),
        entry!("shopLocaleEnable", Mutation, Localization, true, []),
        entry!("shopLocaleUpdate", Mutation, Localization, true, []),
        entry!("shopLocaleDisable", Mutation, Localization, true, []),
        entry!("translationsRegister", Mutation, Localization, true, []),
        entry!("translationsRemove", Mutation, Localization, true, []),
        entry!("files", Query, Media, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("stagedUploadsCreate", Mutation, Media, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileAcknowledgeUpdateFailed", Mutation, Media, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileCreate", Mutation, Media, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileUpdate", Mutation, Media, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileDelete", Mutation, Media, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
    ]
}

fn registry_entry(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    implemented: bool,
    runtime_tests: &[&str],
) -> OperationRegistryEntry {
    registry_entry_with_match_names(
        name,
        operation_type,
        domain,
        implemented,
        default_match_names(name),
        runtime_tests,
    )
}

fn registry_entry_aliased(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    implemented: bool,
    match_names: &[&str],
    runtime_tests: &[&str],
) -> OperationRegistryEntry {
    registry_entry_with_match_names(
        name,
        operation_type,
        domain,
        implemented,
        strings(match_names),
        runtime_tests,
    )
}

fn registry_entry_with_match_names(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    implemented: bool,
    match_names: Vec<String>,
    runtime_tests: &[&str],
) -> OperationRegistryEntry {
    OperationRegistryEntry {
        name: name.to_string(),
        operation_type,
        domain,
        implemented,
        match_names,
        runtime_tests: strings(runtime_tests),
    }
}

fn default_match_names(name: &str) -> Vec<String> {
    let mut chars = name.chars();
    let mut capitalized = String::with_capacity(name.len());
    if let Some(first) = chars.next() {
        capitalized.extend(first.to_uppercase());
        capitalized.push_str(chars.as_str());
    }
    vec![name.to_string(), capitalized]
}

fn strings(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_string()).collect()
}
