use crate::graphql::OperationType;
use crate::operation_registry::{
    ApiSurface, CapabilityDomain, CommitIdInputOrder, CommitIdMappingSpec, OperationRegistryEntry,
};
use crate::proxy::DraftProxy;
use crate::resolver_registry::{ExecutableRootRegistration, NativeResolverHandler};

macro_rules! entry {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $handler:path,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            Some($handler),
            &[$($runtime_test),*],
        )
    };
}

macro_rules! unimplemented_entry {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            None,
            &[$($runtime_test),*],
        )
    };
}

#[rustfmt::skip]
pub(crate) fn default_registry_bindings() -> Vec<ExecutableRootRegistration> {
    vec![
        entry!("product", Query, Products, DraftProxy::product_root_outcome, ["tests/graphql_routes.rs"]),
        entry!("productByIdentifier", Query, Products, DraftProxy::product_by_identifier_root_outcome, ["tests/graphql_routes.rs"]),
        entry!("products", Query, Products, DraftProxy::products_root_outcome, ["tests/graphql_routes.rs"]),
        entry!("productsCount", Query, Products, DraftProxy::products_count_outcome, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("productVariants", Query, Products, []),
        unimplemented_entry!("productVariantsCount", Query, Products, []),
        unimplemented_entry!("productTags", Query, Products, []),
        unimplemented_entry!("productTypes", Query, Products, []),
        unimplemented_entry!("productVendors", Query, Products, []),
        entry!("productOperation", Query, Products, DraftProxy::product_operation_root, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("productDuplicateJob", Query, Products, []),
        unimplemented_entry!("productResourceFeedback", Query, Products, []),
        entry!("productFeed", Query, Products, DraftProxy::product_feed_root, ["tests/graphql_routes.rs"]),
        entry!("productFeeds", Query, Products, DraftProxy::product_feeds_root, ["tests/graphql_routes.rs"]),
        entry!("sellingPlanGroup", Query, Products, DraftProxy::selling_plan_group_root, []),
        entry!("sellingPlanGroups", Query, Products, DraftProxy::selling_plan_groups_root, []),
        unimplemented_entry!("publicApiVersions", Query, AdminPlatform, []),
        entry!("node", Query, AdminPlatform, DraftProxy::admin_node_query_root, []),
        entry!("nodes", Query, AdminPlatform, DraftProxy::admin_node_query_root, []),
        entry!("job", Query, AdminPlatform, DraftProxy::job_query_root, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("taxonomy", Query, AdminPlatform, []),
        entry!("domain", Query, AdminPlatform, DraftProxy::domain_query_root, ["tests/graphql_routes.rs"]),
        entry!("backupRegion", Query, AdminPlatform, DraftProxy::backup_region_query_root, []),
        entry!("backupRegionUpdate", Mutation, AdminPlatform, DraftProxy::backup_region_update_root, []),
        unimplemented_entry!("staffMember", Query, AdminPlatform, []),
        unimplemented_entry!("staffMembers", Query, AdminPlatform, []),
        entry!("flowGenerateSignature", Mutation, AdminPlatform, DraftProxy::flow_utility_mutation_root, []),
        entry!("flowTriggerReceive", Mutation, AdminPlatform, DraftProxy::flow_utility_mutation_root, []),
        unimplemented_entry!("app", Query, Apps, []),
        unimplemented_entry!("appByHandle", Query, Apps, []),
        unimplemented_entry!("appByKey", Query, Apps, []),
        unimplemented_entry!("appInstallation", Query, Apps, []),
        unimplemented_entry!("appInstallations", Query, Apps, []),
        entry!("currentAppInstallation", Query, Apps, DraftProxy::current_app_installation_root, []),
        entry!("appPurchaseOneTimeCreate", Mutation, Apps, DraftProxy::app_purchase_one_time_create, []),
        entry!("appSubscriptionCreate", Mutation, Apps, DraftProxy::app_subscription_create, []),
        entry!("appSubscriptionCancel", Mutation, Apps, DraftProxy::app_subscription_cancel, []),
        entry!("appSubscriptionLineItemUpdate", Mutation, Apps, DraftProxy::app_subscription_line_item_update, []),
        entry!("appSubscriptionTrialExtend", Mutation, Apps, DraftProxy::app_subscription_trial_extend, []),
        entry!("appUsageRecordCreate", Mutation, Apps, DraftProxy::app_usage_record_create, []),
        entry!("appRevokeAccessScopes", Mutation, Apps, DraftProxy::app_revoke_access_scopes, []),
        entry!("appUninstall", Mutation, Apps, DraftProxy::app_uninstall, []),
        entry!("delegateAccessTokenCreate", Mutation, Apps, DraftProxy::delegate_access_token_create, []),
        entry!("delegateAccessTokenDestroy", Mutation, Apps, DraftProxy::delegate_access_token_destroy, []),
        entry!("productVariant", Query, Products, DraftProxy::product_variant_root_outcome, ["tests/graphql_routes/products_saved_searches.rs"]),
        unimplemented_entry!("productVariantByIdentifier", Query, Products, []),
        entry!("inventoryItem", Query, Products, DraftProxy::inventory_item_root, ["tests/graphql_routes.rs"]),
        entry!("inventoryItems", Query, Products, DraftProxy::inventory_items_root, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipment", Query, Products, DraftProxy::inventory_shipment_root, ["tests/graphql_routes.rs"]),
        entry!("inventoryLevel", Query, Products, DraftProxy::inventory_level_root, ["tests/graphql_routes.rs"]),
        entry!("inventoryProperties", Query, Products, DraftProxy::inventory_properties_root, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransfer", Query, Products, DraftProxy::inventory_transfer_root, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransfers", Query, Products, DraftProxy::inventory_transfers_root, ["tests/graphql_routes.rs"]),
        entry!("collection", Query, Products, DraftProxy::collection_root, []),
        entry!("collectionByIdentifier", Query, Products, DraftProxy::collection_by_identifier_root, ["tests/graphql_routes.rs"]),
        entry!("collectionByHandle", Query, Products, DraftProxy::collection_by_handle_root, ["tests/graphql_routes.rs"]),
        entry!("collections", Query, Products, DraftProxy::collections_root, []),
        entry!("collectionsCount", Query, Products, DraftProxy::collections_count_root, []),
        entry!("locations", Query, StoreProperties, DraftProxy::store_properties_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("locationsCount", Query, StoreProperties, DraftProxy::store_properties_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("shop", Query, StoreProperties, DraftProxy::store_properties_query_root, ["tests/graphql_routes.rs"]),
        entry!("location", Query, StoreProperties, DraftProxy::store_properties_query_root, []),
        entry!("locationByIdentifier", Query, StoreProperties, DraftProxy::store_properties_query_root, []),
        unimplemented_entry!("businessEntities", Query, StoreProperties, []),
        unimplemented_entry!("businessEntity", Query, StoreProperties, []),
        entry!("companies", Query, B2b, DraftProxy::b2b_query_root, []),
        entry!("companiesCount", Query, B2b, DraftProxy::b2b_query_root, ["tests/graphql_routes.rs"]),
        entry!("company", Query, B2b, DraftProxy::b2b_query_root, ["tests/graphql_routes.rs"]),
        entry!("companyContact", Query, B2b, DraftProxy::b2b_query_root, []),
        unimplemented_entry!("companyContactRole", Query, B2b, []),
        entry!("companyLocation", Query, B2b, DraftProxy::b2b_query_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocations", Query, B2b, DraftProxy::b2b_query_root, ["tests/graphql_routes.rs"]),
        entry!("companiesDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyAddressDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyAssignCustomerAsContact", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyAssignMainContact", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactAssignRole", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactAssignRoles", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactCreate", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactRemoveFromCompany", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactRevokeRole", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactRevokeRoles", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyContactsDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        unimplemented_entry!("companyContactSendWelcomeEmail", Mutation, B2b, []),
        entry!("companyContactUpdate", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyCreate", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyLocationAssignAddress", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationAssignRoles", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationAssignStaffMembers", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationCreate", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationRemoveStaffMembers", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationRevokeRoles", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationsDelete", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationTaxSettingsUpdate", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyLocationUpdate", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("companyRevokeMainContact", Mutation, B2b, DraftProxy::b2b_mutation_root, []),
        entry!("companyUpdate", Mutation, B2b, DraftProxy::b2b_mutation_root, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("cashManagementLocationSummary", Query, StoreProperties, []),
        entry!("cashTrackingSession", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("cashTrackingSessions", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("customerPaymentMethod", Query, Payments, DraftProxy::customer_payment_method_root, []),
        unimplemented_entry!("orderPaymentStatus", Query, Payments, []),
        entry!("paymentCustomization", Query, Payments, DraftProxy::payment_customization_query_root, []),
        entry!("paymentCustomizations", Query, Payments, DraftProxy::payment_customization_query_root, []),
        entry!("validation", Query, Functions, DraftProxy::functions_query_root, []),
        entry!("validations", Query, Functions, DraftProxy::functions_query_root, []),
        entry!("cartTransforms", Query, Functions, DraftProxy::functions_query_root, []),
        entry!("shopifyFunction", Query, Functions, DraftProxy::functions_query_root, []),
        entry!("shopifyFunctions", Query, Functions, DraftProxy::functions_query_root, []),
        entry!("paymentTermsTemplates", Query, Payments, DraftProxy::payment_terms_templates_root, ["tests/graphql_routes/orders.rs"]),
        unimplemented_entry!("financeAppAccessPolicy", Query, Payments, []),
        unimplemented_entry!("financeKycInformation", Query, Payments, []),
        entry!("pointOfSaleDevice", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("dispute", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("disputes", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        unimplemented_entry!("disputeEvidence", Query, Payments, []),
        entry!("shopPayPaymentRequestReceipt", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        entry!("shopPayPaymentRequestReceipts", Query, Payments, DraftProxy::finance_query_root, ["tests/graphql_routes/platform.rs"]),
        unimplemented_entry!("shopifyPaymentsAccount", Query, Payments, []),
        unimplemented_entry!("tenderTransactions", Query, Payments, []),
        entry!("channel", Query, Products, DraftProxy::channel_root, []),
        entry!("channels", Query, Products, DraftProxy::channels_root, []),
        entry!("publication", Query, Products, DraftProxy::publication_root, []),
        unimplemented_entry!("publications", Query, Products, []),
        entry!("publicationsCount", Query, Products, DraftProxy::publications_count_root, []),
        entry!("publishedProductsCount", Query, Products, DraftProxy::published_products_count_root, []),
        entry!("storeCreditAccount", Query, Customers, DraftProxy::customer_query_root, []),
        entry!("customer", Query, Customers, DraftProxy::customer_query_root, []),
        unimplemented_entry!("customerAccountPage", Query, Customers, []),
        entry!("event", Query, Events, DraftProxy::event_query_root, ["tests/graphql_routes.rs"]),
        entry!("events", Query, Events, DraftProxy::event_query_root, ["tests/graphql_routes.rs"]),
        entry!("eventsCount", Query, Events, DraftProxy::event_query_root, ["tests/graphql_routes.rs"]),
        entry!("customers", Query, Customers, DraftProxy::customer_query_root, []),
        unimplemented_entry!("customerAccountPages", Query, Customers, []),
        entry!("customersCount", Query, Customers, DraftProxy::customer_query_root, []),
        entry!("customerByIdentifier", Query, Customers, DraftProxy::customer_query_root, []),
        unimplemented_entry!("customerMergePreview", Query, Customers, []),
        entry!("customerMergeJobStatus", Query, Customers, DraftProxy::customer_query_root, ["tests/graphql_routes/customers.rs"]),
        entry!("customerCreate", Mutation, Customers, DraftProxy::customer_lifecycle_mutation_root, []),
        entry!("customerUpdate", Mutation, Customers, DraftProxy::customer_lifecycle_mutation_root, []),
        entry!("customerDelete", Mutation, Customers, DraftProxy::customer_lifecycle_mutation_root, []),
        entry!("customerRequestDataErasure", Mutation, Customers, DraftProxy::customer_data_erasure_root, ["tests/graphql_routes/customers.rs"]),
        entry!("customerCancelDataErasure", Mutation, Customers, DraftProxy::customer_data_erasure_root, ["tests/graphql_routes/customers.rs"]),
        entry!("customerAddressCreate", Mutation, Customers, DraftProxy::customer_address_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddressUpdate", Mutation, Customers, DraftProxy::customer_address_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddressDelete", Mutation, Customers, DraftProxy::customer_address_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerUpdateDefaultAddress", Mutation, Customers, DraftProxy::customer_address_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerEmailMarketingConsentUpdate", Mutation, Customers, DraftProxy::customer_marketing_consent_update_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerSmsMarketingConsentUpdate", Mutation, Customers, DraftProxy::customer_marketing_consent_update_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddTaxExemptions", Mutation, Customers, DraftProxy::customer_tax_exemptions_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerRemoveTaxExemptions", Mutation, Customers, DraftProxy::customer_tax_exemptions_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerReplaceTaxExemptions", Mutation, Customers, DraftProxy::customer_tax_exemptions_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerSet", Mutation, Customers, DraftProxy::customer_lifecycle_mutation_root, []),
        entry!("customerGenerateAccountActivationUrl", Mutation, Customers, DraftProxy::customer_outbound_lifecycle_root, ["tests/graphql_routes/customers.rs"]),
        entry!("customerSendAccountInviteEmail", Mutation, Customers, DraftProxy::customer_outbound_lifecycle_root, ["tests/graphql_routes/customers.rs"]),
        entry!("storeCreditAccountCredit", Mutation, Customers, DraftProxy::store_credit_account_mutation_root, []),
        entry!("storeCreditAccountDebit", Mutation, Customers, DraftProxy::store_credit_account_mutation_root, []),
        unimplemented_entry!("customerPaymentMethodSendUpdateEmail", Mutation, Customers, []),
        entry!("customerMerge", Mutation, Customers, DraftProxy::customer_merge_root, []),
        entry!("sellingPlanGroupCreate", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("sellingPlanGroupUpdate", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("sellingPlanGroupDelete", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("sellingPlanGroupAddProducts", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("sellingPlanGroupRemoveProducts", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("sellingPlanGroupAddProductVariants", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("sellingPlanGroupRemoveProductVariants", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("productJoinSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("productLeaveSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("productVariantJoinSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("productVariantLeaveSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, []),
        entry!("tagsAdd", Mutation, Products, DraftProxy::product_tags_outcome, ["tests/graphql_routes.rs"]),
        entry!("tagsRemove", Mutation, Products, DraftProxy::product_tags_outcome, ["tests/graphql_routes.rs"]),
        entry!("bulkProductResourceFeedbackCreate", Mutation, Products, DraftProxy::resource_feedback_outcome, ["tests/graphql_routes.rs"]),
        entry!("shopResourceFeedbackCreate", Mutation, Products, DraftProxy::resource_feedback_outcome, ["tests/graphql_routes.rs"]),
        entry!("productCreate", Mutation, Products, DraftProxy::product_create_outcome, ["tests/graphql_routes.rs"]),
        entry!("productUpdate", Mutation, Products, DraftProxy::product_update_outcome, ["tests/graphql_routes.rs"]),
        entry!("productDelete", Mutation, Products, DraftProxy::product_delete_outcome, ["tests/graphql_routes.rs"]),
        entry!("productDuplicate", Mutation, Products, DraftProxy::product_duplicate_outcome, ["tests/graphql_routes.rs"]),
        entry!("productSet", Mutation, Products, DraftProxy::product_set_outcome, ["tests/graphql_routes.rs"]),
        entry!("productChangeStatus", Mutation, Products, DraftProxy::product_change_status_outcome, ["tests/graphql_routes.rs"]),
        entry!("productFeedCreate", Mutation, Products, DraftProxy::product_feed_create_outcome, ["tests/graphql_routes.rs"]),
        entry!("productFeedDelete", Mutation, Products, DraftProxy::product_feed_delete_outcome, ["tests/graphql_routes.rs"]),
        entry!("productFullSync", Mutation, Products, DraftProxy::product_full_sync_outcome, ["tests/graphql_routes.rs"]),
        entry!("productBundleCreate", Mutation, Products, DraftProxy::product_bundle_outcome, ["tests/graphql_routes.rs"]),
        entry!("productBundleUpdate", Mutation, Products, DraftProxy::product_bundle_outcome, ["tests/graphql_routes.rs"]),
        entry!("combinedListingUpdate", Mutation, Products, DraftProxy::product_relationship_outcome, ["tests/graphql_routes.rs"]),
        entry!("publicationCreate", Mutation, Products, DraftProxy::publication_mutation_outcome, ["tests/graphql_routes.rs"]),
        entry!("publicationUpdate", Mutation, Products, DraftProxy::publication_mutation_outcome, ["tests/graphql_routes.rs"]),
        entry!("publicationDelete", Mutation, Products, DraftProxy::publication_mutation_outcome, ["tests/graphql_routes.rs"]),
        entry!("productPublish", Mutation, Products, DraftProxy::product_publication_outcome, ["tests/graphql_routes/products_saved_searches.rs"]),
        entry!("productUnpublish", Mutation, Products, DraftProxy::product_publication_outcome, ["tests/graphql_routes/products_saved_searches.rs"]),
        entry!("locationAdd", Mutation, StoreProperties, DraftProxy::location_mutation, []),
        entry!("locationEdit", Mutation, StoreProperties, DraftProxy::location_mutation, []),
        entry!("locationActivate", Mutation, StoreProperties, DraftProxy::location_mutation, []),
        entry!("locationDeactivate", Mutation, StoreProperties, DraftProxy::location_mutation, []),
        entry!("locationDelete", Mutation, StoreProperties, DraftProxy::location_mutation, ["tests/graphql_routes.rs"]),
        entry!("publishablePublish", Mutation, StoreProperties, DraftProxy::product_publishable_mutation, []),
        entry!("publishablePublishToCurrentChannel", Mutation, StoreProperties, DraftProxy::product_publishable_mutation, []),
        entry!("publishableUnpublish", Mutation, StoreProperties, DraftProxy::product_publishable_mutation, []),
        entry!("publishableUnpublishToCurrentChannel", Mutation, StoreProperties, DraftProxy::product_publishable_mutation, []),
        entry!("shopPolicyUpdate", Mutation, StoreProperties, DraftProxy::shop_policy_update_root, ["tests/graphql_routes.rs"]),
        entry!("productSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("collectionSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("customerSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("orderSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("fileSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("codeDiscountSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("automaticDiscountSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("discountRedeemCodeSavedSearches", Query, SavedSearches, DraftProxy::saved_search_query_root, ["tests/graphql_routes.rs"]),
        entry!("savedSearchCreate", Mutation, SavedSearches, DraftProxy::saved_search_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("savedSearchUpdate", Mutation, SavedSearches, DraftProxy::saved_search_mutation_root, []),
        entry!("savedSearchDelete", Mutation, SavedSearches, DraftProxy::saved_search_mutation_root, []),
        unimplemented_entry!("urlRedirectSavedSearches", Query, OnlineStore, []),
        entry!("urlRedirect", Query, OnlineStore, DraftProxy::url_redirect_query_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("urlRedirects", Query, OnlineStore, DraftProxy::url_redirect_query_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("urlRedirectsCount", Query, OnlineStore, DraftProxy::url_redirect_query_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        unimplemented_entry!("urlRedirectCreate", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectUpdate", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectDelete", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectBulkDeleteAll", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectBulkDeleteByIds", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectBulkDeleteBySavedSearch", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectBulkDeleteBySearch", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectImportCreate", Mutation, OnlineStore, []),
        unimplemented_entry!("urlRedirectImportSubmit", Mutation, OnlineStore, []),
        entry!("article", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("articleAuthors", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("articles", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("articleTags", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("articleCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("articleUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("articleDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("blog", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("blogs", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("blogsCount", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("blogCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("blogUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("blogDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("page", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("pages", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("pagesCount", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("pageCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("pageUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("pageDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("comment", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("comments", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("commentApprove", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("commentSpam", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("commentNotSpam", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("commentDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        unimplemented_entry!("menu", Query, OnlineStore, []),
        unimplemented_entry!("menus", Query, OnlineStore, []),
        entry!("theme", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("themes", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("scriptTag", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("scriptTags", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("webPixel", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("serverPixel", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("mobilePlatformApplication", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        entry!("mobilePlatformApplications", Query, OnlineStore, DraftProxy::online_store_query_root, []),
        unimplemented_entry!("menuCreate", Mutation, OnlineStore, []),
        unimplemented_entry!("menuUpdate", Mutation, OnlineStore, []),
        unimplemented_entry!("menuDelete", Mutation, OnlineStore, []),
        entry!("themeCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("themeUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("themeDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("themePublish", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("themeFilesCopy", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("themeFilesUpsert", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("themeFilesDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("scriptTagCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("scriptTagUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("scriptTagDelete", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("webPixelCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("webPixelUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        unimplemented_entry!("webPixelDelete", Mutation, OnlineStore, []),
        entry!("serverPixelCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        unimplemented_entry!("serverPixelDelete", Mutation, OnlineStore, []),
        entry!("eventBridgeServerPixelUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("pubSubServerPixelUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("storefrontAccessTokenCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        unimplemented_entry!("storefrontAccessTokenDelete", Mutation, OnlineStore, []),
        entry!("mobilePlatformApplicationCreate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        entry!("mobilePlatformApplicationUpdate", Mutation, OnlineStore, DraftProxy::online_store_mutation_root, []),
        unimplemented_entry!("mobilePlatformApplicationDelete", Mutation, OnlineStore, []),
        unimplemented_entry!("privacySettings", Query, Privacy, []),
        unimplemented_entry!("consentPolicy", Query, Privacy, []),
        unimplemented_entry!("consentPolicyRegions", Query, Privacy, []),
        unimplemented_entry!("consentPolicyUpdate", Mutation, Privacy, []),
        unimplemented_entry!("privacyFeaturesDisable", Mutation, Privacy, []),
        entry!("dataSaleOptOut", Mutation, Privacy, DraftProxy::data_sale_opt_out_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("bulkOperation", Query, BulkOperations, DraftProxy::bulk_operation_query_root, []),
        entry!("bulkOperations", Query, BulkOperations, DraftProxy::bulk_operation_query_root, []),
        entry!("currentBulkOperation", Query, BulkOperations, DraftProxy::bulk_operation_query_root, []),
        entry!("bulkOperationRunQuery", Mutation, BulkOperations, DraftProxy::bulk_operation_mutation_root, []),
        entry!("bulkOperationRunMutation", Mutation, BulkOperations, DraftProxy::bulk_operation_mutation_root, []),
        entry!("bulkOperationCancel", Mutation, BulkOperations, DraftProxy::bulk_operation_mutation_root, []),
        entry!("productOptionsCreate", Mutation, Products, DraftProxy::product_option_outcome, []),
        entry!("productOptionUpdate", Mutation, Products, DraftProxy::product_option_outcome, []),
        entry!("productOptionsDelete", Mutation, Products, DraftProxy::product_option_outcome, []),
        entry!("productOptionsReorder", Mutation, Products, DraftProxy::product_option_outcome, []),
        entry!("productVariantsBulkCreate", Mutation, Products, DraftProxy::product_variant_outcome, ["tests/graphql_routes.rs"]),
        entry!("productVariantsBulkUpdate", Mutation, Products, DraftProxy::product_variant_outcome, ["tests/graphql_routes.rs"]),
        entry!("productVariantsBulkDelete", Mutation, Products, DraftProxy::product_variant_outcome, ["tests/graphql_routes.rs"]),
        entry!("productVariantsBulkReorder", Mutation, Products, DraftProxy::product_variant_outcome, ["tests/graphql_routes.rs"]),
        // Historical parity metadata still names these removed compatibility
        // roots. Keep them explicitly declared as unsupported so discovery can
        // distinguish a retired root from an unregistered operation. The
        // captured versioned schemas remain authoritative and reject them.
        unimplemented_entry!("productVariantCreate", Mutation, Products, []),
        unimplemented_entry!("productVariantUpdate", Mutation, Products, []),
        unimplemented_entry!("productVariantDelete", Mutation, Products, []),
        entry!("productCreateMedia", Mutation, Products, DraftProxy::product_media_outcome, []),
        entry!("productUpdateMedia", Mutation, Products, DraftProxy::product_media_outcome, []),
        entry!("productDeleteMedia", Mutation, Products, DraftProxy::product_media_outcome, []),
        entry!("productReorderMedia", Mutation, Products, DraftProxy::product_media_outcome, []),
        entry!("productVariantAppendMedia", Mutation, Products, DraftProxy::product_variant_outcome, ["tests/graphql_routes.rs"]),
        entry!("productVariantDetachMedia", Mutation, Products, DraftProxy::product_variant_outcome, ["tests/graphql_routes.rs"]),
        entry!("productVariantRelationshipBulkUpdate", Mutation, Products, DraftProxy::product_relationship_outcome, ["tests/graphql_routes.rs"]),
        entry!("inventoryItemUpdate", Mutation, Products, DraftProxy::inventory_item_update, ["tests/graphql_routes.rs"]),
        entry!("inventoryAdjustQuantities", Mutation, Products, DraftProxy::inventory_adjust_quantities, ["tests/graphql_routes.rs"]),
        entry!("inventorySetQuantities", Mutation, Products, DraftProxy::inventory_set_quantities, ["tests/graphql_routes.rs"]),
        entry!("inventorySetOnHandQuantities", Mutation, Products, DraftProxy::inventory_set_on_hand_quantities, ["tests/graphql_routes.rs"]),
        entry!("inventoryMoveQuantities", Mutation, Products, DraftProxy::inventory_move_quantities, ["tests/graphql_routes.rs"]),
        entry!("inventoryActivate", Mutation, Products, DraftProxy::inventory_activate, ["tests/graphql_routes.rs"]),
        entry!("inventoryDeactivate", Mutation, Products, DraftProxy::inventory_deactivate, ["tests/graphql_routes.rs"]),
        entry!("inventoryBulkToggleActivation", Mutation, Products, DraftProxy::inventory_bulk_toggle_activation, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferCreate", Mutation, Products, DraftProxy::inventory_transfer_create, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferCreateAsReadyToShip", Mutation, Products, DraftProxy::inventory_transfer_create, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferEdit", Mutation, Products, DraftProxy::inventory_transfer_edit, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferSetItems", Mutation, Products, DraftProxy::inventory_transfer_set_items, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferRemoveItems", Mutation, Products, DraftProxy::inventory_transfer_remove_items, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferMarkAsReadyToShip", Mutation, Products, DraftProxy::inventory_transfer_mark_ready, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferDuplicate", Mutation, Products, DraftProxy::inventory_transfer_duplicate, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferCancel", Mutation, Products, DraftProxy::inventory_transfer_cancel, ["tests/graphql_routes.rs"]),
        entry!("inventoryTransferDelete", Mutation, Products, DraftProxy::inventory_transfer_delete, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentCreate", Mutation, Products, DraftProxy::inventory_shipment_create, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentCreateInTransit", Mutation, Products, DraftProxy::inventory_shipment_create, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentAddItems", Mutation, Products, DraftProxy::inventory_shipment_add_items, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentRemoveItems", Mutation, Products, DraftProxy::inventory_shipment_remove_items, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentUpdateItemQuantities", Mutation, Products, DraftProxy::inventory_shipment_update_item_quantities, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentSetTracking", Mutation, Products, DraftProxy::inventory_shipment_set_tracking, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentMarkInTransit", Mutation, Products, DraftProxy::inventory_shipment_mark_in_transit, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentReceive", Mutation, Products, DraftProxy::inventory_shipment_receive, ["tests/graphql_routes.rs"]),
        entry!("inventoryShipmentDelete", Mutation, Products, DraftProxy::inventory_shipment_delete, ["tests/graphql_routes.rs"]),
        entry!("metafieldsSet", Mutation, Products, DraftProxy::owner_metafields_set, []),
        entry!("metafieldsDelete", Mutation, Products, DraftProxy::owner_metafields_delete, []),
        entry!("metafieldDefinition", Query, Metafields, DraftProxy::metafield_definition_query_root, []),
        entry!("metafieldDefinitions", Query, Metafields, DraftProxy::metafield_definition_query_root, []),
        unimplemented_entry!("standardMetafieldDefinitionTemplates", Query, Metafields, []),
        entry!("metafieldDefinitionCreate", Mutation, Metafields, DraftProxy::metafield_definition_mutation_root, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionUpdate", Mutation, Metafields, DraftProxy::metafield_definition_mutation_root, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionDelete", Mutation, Metafields, DraftProxy::metafield_definition_mutation_root, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionPin", Mutation, Metafields, DraftProxy::metafield_definition_mutation_root, []),
        entry!("metafieldDefinitionUnpin", Mutation, Metafields, DraftProxy::metafield_definition_mutation_root, []),
        entry!("standardMetafieldDefinitionEnable", Mutation, Metafields, DraftProxy::metafield_definition_mutation_root, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metaobject", Query, Metaobjects, DraftProxy::metaobject_query_root, []),
        entry!("metaobjectByHandle", Query, Metaobjects, DraftProxy::metaobject_query_root, []),
        entry!("metaobjects", Query, Metaobjects, DraftProxy::metaobject_query_root, []),
        entry!("metaobjectDefinition", Query, Metaobjects, DraftProxy::metaobject_query_root, []),
        entry!("metaobjectDefinitionByType", Query, Metaobjects, DraftProxy::metaobject_query_root, []),
        entry!("metaobjectDefinitions", Query, Metaobjects, DraftProxy::metaobject_query_root, []),
        entry!("metaobjectCreate", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("metaobjectUpdate", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("metaobjectUpsert", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("metaobjectDelete", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("metaobjectBulkDelete", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("metaobjectDefinitionCreate", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("metaobjectDefinitionUpdate", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("metaobjectDefinitionDelete", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, []),
        entry!("standardMetaobjectDefinitionEnable", Mutation, Metaobjects, DraftProxy::metaobject_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("collectionCreate", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("collectionUpdate", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("collectionDelete", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("collectionAddProducts", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("collectionAddProductsV2", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("collectionRemoveProducts", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("collectionReorderProducts", Mutation, Products, DraftProxy::collection_outcome, ["tests/graphql_routes.rs"]),
        entry!("order", Query, Orders, DraftProxy::orders_query_root, []),
        entry!("return", Query, Orders, DraftProxy::orders_query_root, []),
        entry!("orders", Query, Orders, DraftProxy::orders_query_root, []),
        entry!("ordersCount", Query, Orders, DraftProxy::orders_query_root, []),
        entry!("returnCalculate", Query, Orders, DraftProxy::orders_query_root, ["tests/graphql_routes/orders.rs"]),
        unimplemented_entry!("returnableFulfillment", Query, Orders, []),
        entry!("returnableFulfillments", Query, Orders, DraftProxy::orders_query_root, ["tests/graphql_routes/orders.rs"]),
        entry!("reverseDelivery", Query, ShippingFulfillments, DraftProxy::reverse_logistics_query_root, []),
        entry!("reverseFulfillmentOrder", Query, ShippingFulfillments, DraftProxy::reverse_logistics_query_root, []),
        unimplemented_entry!("abandonedCheckouts", Query, Orders, []),
        unimplemented_entry!("abandonedCheckoutsCount", Query, Orders, []),
        entry!("abandonment", Query, Orders, DraftProxy::abandonment_query_root, []),
        unimplemented_entry!("abandonmentByAbandonedCheckoutId", Query, Orders, []),
        entry!("orderUpdate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderClose", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("orderOpen", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("orderMarkAsPaid", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!(
            "orderCreateManualPayment",
            Mutation,
            Orders,
            DraftProxy::orders_mutation_root,
            ["tests/graphql_routes/orders.rs"]
        ),
        unimplemented_entry!("orderRiskAssessmentCreate", Mutation, Orders, []),
        entry!("customerPaymentMethodCreateFromDuplicationData", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodCreditCardCreate", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodCreditCardUpdate", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodGetDuplicationData", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodGetUpdateUrl", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodPaypalBillingAgreementCreate", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodPaypalBillingAgreementUpdate", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodRemoteCreate", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("customerPaymentMethodRevoke", Mutation, Payments, DraftProxy::customer_payment_method_mutation_root, []),
        entry!("orderCapture", Mutation, Payments, DraftProxy::payment_transaction_mutation_root, []),
        entry!("orderCreateMandatePayment", Mutation, Payments, DraftProxy::payment_transaction_mutation_root, []),
        entry!("paymentCustomizationActivation", Mutation, Payments, DraftProxy::payment_customization_mutation_root, []),
        entry!("paymentCustomizationCreate", Mutation, Payments, DraftProxy::payment_customization_mutation_root, []),
        entry!("paymentCustomizationDelete", Mutation, Payments, DraftProxy::payment_customization_mutation_root, []),
        entry!("paymentCustomizationUpdate", Mutation, Payments, DraftProxy::payment_customization_mutation_root, []),
        entry!("validationCreate", Mutation, Functions, DraftProxy::functions_mutation_root, []),
        entry!("validationUpdate", Mutation, Functions, DraftProxy::functions_mutation_root, []),
        entry!("validationDelete", Mutation, Functions, DraftProxy::functions_mutation_root, []),
        entry!("cartTransformCreate", Mutation, Functions, DraftProxy::functions_mutation_root, []),
        entry!("cartTransformDelete", Mutation, Functions, DraftProxy::functions_mutation_root, []),
        entry!("taxAppConfigure", Mutation, Functions, DraftProxy::functions_mutation_root, []),
        entry!("paymentReminderSend", Mutation, Payments, DraftProxy::payment_reminder_root, []),
        entry!("paymentTermsCreate", Mutation, Payments, DraftProxy::payment_terms_mutation_root, []),
        entry!("paymentTermsDelete", Mutation, Payments, DraftProxy::payment_terms_mutation_root, []),
        entry!("paymentTermsUpdate", Mutation, Payments, DraftProxy::payment_terms_mutation_root, []),
        unimplemented_entry!("disputeEvidenceUpdate", Mutation, Payments, []),
        unimplemented_entry!("shopifyPaymentsPayoutAlternateCurrencyCreate", Mutation, Payments, []),
        entry!("transactionVoid", Mutation, Payments, DraftProxy::payment_transaction_mutation_root, []),
        entry!("orderCustomerSet", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("orderCustomerRemove", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!(
            "orderInvoiceSend",
            Mutation,
            Orders,
            DraftProxy::orders_mutation_root,
            ["tests/graphql_routes/orders.rs"]
        ),
        unimplemented_entry!("taxSummaryCreate", Mutation, Orders, []),
        entry!("orderCancel", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("fulfillmentCreate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("fulfillmentCreateV2", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes/orders.rs"]),
        entry!("fulfillmentTrackingInfoUpdate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!(
            "fulfillmentTrackingInfoUpdateV2",
            Mutation,
            Orders,
            DraftProxy::orders_mutation_root,
            ["tests/graphql_routes/orders.rs"]
        ),
        entry!("fulfillmentCancel", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("fulfillment", Query, Orders, DraftProxy::orders_query_root, ["tests/graphql_routes/orders.rs"]),
        entry!("fulfillmentEventCreate", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("assignedFulfillmentOrders", Query, ShippingFulfillments, DraftProxy::fulfillment_order_query_root, []),
        entry!("fulfillmentOrder", Query, ShippingFulfillments, DraftProxy::fulfillment_order_query_root, []),
        entry!("fulfillmentOrders", Query, ShippingFulfillments, DraftProxy::fulfillment_order_query_root, []),
        entry!("manualHoldsFulfillmentOrders", Query, ShippingFulfillments, DraftProxy::fulfillment_order_query_root, []),
        entry!("fulfillmentOrderAcceptCancellationRequest", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderAcceptFulfillmentRequest", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderCancel", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderClose", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderHold", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!(
            "fulfillmentOrderLineItemsPreparedForPickup",
            Mutation,
            ShippingFulfillments,
            DraftProxy::fulfillment_order_mutation_root,
            ["tests/graphql_routes/platform.rs"]
        ),
        entry!("fulfillmentOrderMerge", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderMove", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderOpen", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderRejectCancellationRequest", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderRejectFulfillmentRequest", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderReleaseHold", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderReportProgress", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderReschedule", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrdersReroute", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrdersSetFulfillmentDeadline", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderSplit", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderSubmitCancellationRequest", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentOrderSubmitFulfillmentRequest", Mutation, ShippingFulfillments, DraftProxy::fulfillment_order_mutation_root, []),
        entry!("fulfillmentService", Query, ShippingFulfillments, DraftProxy::fulfillment_service_query_root, []),
        entry!("fulfillmentServiceCreate", Mutation, ShippingFulfillments, DraftProxy::fulfillment_service_mutation_root, []),
        entry!("fulfillmentServiceDelete", Mutation, ShippingFulfillments, DraftProxy::fulfillment_service_mutation_root, []),
        entry!("fulfillmentServiceUpdate", Mutation, ShippingFulfillments, DraftProxy::fulfillment_service_mutation_root, []),
        entry!("availableCarrierServices", Query, ShippingFulfillments, DraftProxy::shipping_settings_query_root, []),
        entry!("carrierService", Query, ShippingFulfillments, DraftProxy::carrier_service_query_root, []),
        entry!("carrierServices", Query, ShippingFulfillments, DraftProxy::carrier_service_query_root, []),
        entry!("carrierServiceCreate", Mutation, ShippingFulfillments, DraftProxy::carrier_service_mutation_root, []),
        entry!("carrierServiceDelete", Mutation, ShippingFulfillments, DraftProxy::carrier_service_mutation_root, []),
        entry!("carrierServiceUpdate", Mutation, ShippingFulfillments, DraftProxy::carrier_service_mutation_root, []),
        entry!("giftCard", Query, GiftCards, DraftProxy::gift_card_query_root, []),
        entry!("giftCards", Query, GiftCards, DraftProxy::gift_card_query_root, []),
        entry!("giftCardsCount", Query, GiftCards, DraftProxy::gift_card_query_root, []),
        entry!("giftCardConfiguration", Query, GiftCards, DraftProxy::gift_card_query_root, []),
        entry!("giftCardCreate", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("giftCardUpdate", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("giftCardCredit", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("giftCardDebit", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("giftCardDeactivate", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("giftCardSendNotificationToCustomer", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("giftCardSendNotificationToRecipient", Mutation, GiftCards, DraftProxy::gift_card_mutation_root, []),
        entry!("deliveryCustomization", Query, ShippingFulfillments, DraftProxy::delivery_customization_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizations", Query, ShippingFulfillments, DraftProxy::delivery_customization_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseParticipants", Query, ShippingFulfillments, DraftProxy::delivery_promise_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseProvider", Query, ShippingFulfillments, DraftProxy::delivery_promise_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseSettings", Query, ShippingFulfillments, DraftProxy::delivery_settings_query_root, []),
        entry!("deliverySettings", Query, ShippingFulfillments, DraftProxy::delivery_settings_query_root, []),
        entry!("deliveryProfile", Query, ShippingFulfillments, DraftProxy::delivery_profile_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfiles", Query, ShippingFulfillments, DraftProxy::delivery_profile_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationsAvailableForDeliveryProfilesConnection", Query, ShippingFulfillments, DraftProxy::delivery_profile_locations_query_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationLocalPickupDisable", Mutation, ShippingFulfillments, DraftProxy::location_local_pickup_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationLocalPickupEnable", Mutation, ShippingFulfillments, DraftProxy::location_local_pickup_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("shippingPackageDelete", Mutation, ShippingFulfillments, DraftProxy::shipping_package_mutation_root, []),
        entry!("shippingPackageMakeDefault", Mutation, ShippingFulfillments, DraftProxy::shipping_package_mutation_root, []),
        entry!("shippingPackageUpdate", Mutation, ShippingFulfillments, DraftProxy::shipping_package_mutation_root, []),
        entry!("fulfillmentConstraintRules", Query, Functions, DraftProxy::functions_query_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleCreate", Mutation, Functions, DraftProxy::functions_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleDelete", Mutation, Functions, DraftProxy::functions_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleUpdate", Mutation, Functions, DraftProxy::functions_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("deliveryProfileCreate", Mutation, ShippingFulfillments, DraftProxy::delivery_profile_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfileRemove", Mutation, ShippingFulfillments, DraftProxy::delivery_profile_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfileUpdate", Mutation, ShippingFulfillments, DraftProxy::delivery_profile_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationActivation", Mutation, ShippingFulfillments, DraftProxy::delivery_customization_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationCreate", Mutation, ShippingFulfillments, DraftProxy::delivery_customization_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationDelete", Mutation, ShippingFulfillments, DraftProxy::delivery_customization_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationUpdate", Mutation, ShippingFulfillments, DraftProxy::delivery_customization_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseParticipantsUpdate", Mutation, ShippingFulfillments, DraftProxy::delivery_promise_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseProviderUpsert", Mutation, ShippingFulfillments, DraftProxy::delivery_promise_mutation_root, ["tests/graphql_routes/admin_app_shipping.rs"]),
        unimplemented_entry!("deliverySettingUpdate", Mutation, ShippingFulfillments, []),
        entry!("orderEditAddShippingLine", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditRemoveShippingLine", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditUpdateShippingLine", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderDelete", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditAddCustomItem", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditAddLineItemDiscount", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditRemoveDiscount", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderCreate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("abandonmentUpdateActivitiesDeliveryStatuses", Mutation, Orders, DraftProxy::abandonment_delivery_status_mutation_root, []),
        entry!("refundCreate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnCreate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnRequest", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnApproveRequest", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnDeclineRequest", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnCancel", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnClose", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnReopen", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("removeFromReturn", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("returnProcess", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("reverseDeliveryCreateWithShipping", Mutation, ShippingFulfillments, DraftProxy::reverse_logistics_mutation_root, []),
        entry!("reverseDeliveryShippingUpdate", Mutation, ShippingFulfillments, DraftProxy::reverse_logistics_mutation_root, []),
        entry!("reverseFulfillmentOrderDispose", Mutation, ShippingFulfillments, DraftProxy::reverse_logistics_mutation_root, []),
        entry!("draftOrder", Query, Orders, DraftProxy::orders_query_root, []),
        entry!("draftOrders", Query, Orders, DraftProxy::orders_query_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrdersCount", Query, Orders, DraftProxy::orders_query_root, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("draftOrderAvailableDeliveryOptions", Query, Orders, []),
        unimplemented_entry!("draftOrderTag", Query, Orders, []),
        entry!("draftOrderCreate", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("draftOrderComplete", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("draftOrderUpdate", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderDuplicate", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderBulkAddTags", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("draftOrderBulkRemoveTags", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("draftOrderBulkDelete", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderDelete", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderCalculate", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderInvoicePreview", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("draftOrderInvoiceSend", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("draftOrderCreateFromOrder", Mutation, Orders, DraftProxy::orders_mutation_root, ["tests/graphql_routes.rs"]),
        entry!("orderEditBegin", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditAddVariant", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditSetQuantity", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("orderEditCommit", Mutation, Orders, DraftProxy::orders_mutation_root, []),
        entry!("discountNodes", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("discountNodesCount", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("discountNode", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("codeDiscountNodes", Query, Discounts, DraftProxy::discount_query_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("codeDiscountNode", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("codeDiscountNodeByCode", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("discountRedeemCodeBulkCreation", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("automaticDiscountNodes", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("automaticDiscountNode", Query, Discounts, DraftProxy::discount_query_root, []),
        entry!("discountCodeBasicCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeBasicUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeBxgyCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeBxgyUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeFreeShippingCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeFreeShippingUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeActivate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeDeactivate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeDelete", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeBulkActivate", Mutation, Discounts, DraftProxy::discount_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountCodeBulkDeactivate", Mutation, Discounts, DraftProxy::discount_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountCodeBulkDelete", Mutation, Discounts, DraftProxy::discount_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountRedeemCodeBulkAdd", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeRedeemCodeBulkDelete", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticBasicCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticBasicUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticBxgyCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticBxgyUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticFreeShippingCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticFreeShippingUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticActivate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticDeactivate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticDelete", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticBulkDelete", Mutation, Discounts, DraftProxy::discount_mutation_root, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountCodeAppCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountCodeAppUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticAppCreate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("discountAutomaticAppUpdate", Mutation, Discounts, DraftProxy::discount_mutation_root, []),
        entry!("marketingActivities", Query, Marketing, DraftProxy::marketing_query_root, []),
        entry!("marketingActivity", Query, Marketing, DraftProxy::marketing_query_root, []),
        entry!("marketingEvent", Query, Marketing, DraftProxy::marketing_query_root, []),
        entry!("marketingEvents", Query, Marketing, DraftProxy::marketing_query_root, []),
        entry!("marketingActivityCreate", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingActivityUpdate", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingActivityCreateExternal", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingActivityUpdateExternal", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingActivityUpsertExternal", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingActivityDeleteExternal", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingActivitiesDeleteAllExternal", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingEngagementCreate", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("marketingEngagementsDelete", Mutation, Marketing, DraftProxy::marketing_mutation_root, []),
        entry!("webhookSubscription", Query, Webhooks, DraftProxy::webhook_query_root, []),
        entry!("webhookSubscriptions", Query, Webhooks, DraftProxy::webhook_query_root, []),
        entry!("webhookSubscriptionsCount", Query, Webhooks, DraftProxy::webhook_query_root, []),
        entry!("eventBridgeWebhookSubscriptionCreate", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("eventBridgeWebhookSubscriptionUpdate", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("pubSubWebhookSubscriptionCreate", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("pubSubWebhookSubscriptionUpdate", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("webhookSubscriptionCreate", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("webhookSubscriptionUpdate", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("webhookSubscriptionDelete", Mutation, Webhooks, DraftProxy::webhook_mutation_root, []),
        entry!("segment", Query, Segments, DraftProxy::segment_query_root, []),
        entry!("segments", Query, Segments, DraftProxy::segment_query_root, []),
        entry!("segmentsCount", Query, Segments, DraftProxy::segment_query_root, []),
        unimplemented_entry!("segmentFilters", Query, Segments, []),
        unimplemented_entry!("segmentFilterSuggestions", Query, Segments, []),
        unimplemented_entry!("segmentValueSuggestions", Query, Segments, []),
        unimplemented_entry!("segmentMigrations", Query, Segments, []),
        unimplemented_entry!("customerSegmentMembers", Query, Segments, []),
        entry!("customerSegmentMembersQuery", Query, Segments, DraftProxy::customer_segment_members_query_root, []),
        unimplemented_entry!("customerSegmentMembership", Query, Segments, []),
        entry!("customerSegmentMembersQueryCreate", Mutation, Segments, DraftProxy::customer_segment_members_query_create_root, []),
        entry!("segmentCreate", Mutation, Segments, DraftProxy::segment_mutation_root, []),
        entry!("segmentUpdate", Mutation, Segments, DraftProxy::segment_mutation_root, []),
        entry!("segmentDelete", Mutation, Segments, DraftProxy::segment_mutation_root, []),
        entry!("market", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("markets", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("catalog", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("catalogs", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("catalogsCount", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("priceList", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("priceLists", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("priceListCreate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("priceListUpdate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("priceListDelete", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("priceListFixedPricesAdd", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("priceListFixedPricesUpdate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("priceListFixedPricesDelete", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("priceListFixedPricesByProductUpdate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("quantityPricingByVariantUpdate", Mutation, Markets, DraftProxy::quantity_pricing_by_variant_update_root, []),
        entry!("quantityRulesAdd", Mutation, Markets, DraftProxy::quantity_rules_mutation_root, []),
        entry!("quantityRulesDelete", Mutation, Markets, DraftProxy::quantity_rules_mutation_root, []),
        entry!("webPresences", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("marketsResolvedValues", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("marketLocalizableResource", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("marketLocalizableResources", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("marketLocalizableResourcesByIds", Query, Markets, DraftProxy::markets_query_root, []),
        entry!("marketCreate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("marketUpdate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("marketDelete", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("catalogCreate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("catalogUpdate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("catalogContextUpdate", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("catalogDelete", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("webPresenceCreate", Mutation, Markets, DraftProxy::web_presence_mutation_root, []),
        entry!("webPresenceUpdate", Mutation, Markets, DraftProxy::web_presence_mutation_root, []),
        entry!("webPresenceDelete", Mutation, Markets, DraftProxy::web_presence_mutation_root, []),
        entry!("marketLocalizationsRegister", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("marketLocalizationsRemove", Mutation, Markets, DraftProxy::markets_mutation_root, []),
        entry!("availableLocales", Query, Localization, DraftProxy::localization_query_root, []),
        entry!("shopLocales", Query, Localization, DraftProxy::localization_query_root, []),
        entry!("translatableResource", Query, Localization, DraftProxy::localization_query_root, []),
        entry!("translatableResources", Query, Localization, DraftProxy::localization_query_root, []),
        entry!("translatableResourcesByIds", Query, Localization, DraftProxy::localization_query_root, []),
        entry!("shopLocaleEnable", Mutation, Localization, DraftProxy::localization_mutation_root, []),
        entry!("shopLocaleUpdate", Mutation, Localization, DraftProxy::localization_mutation_root, []),
        entry!("shopLocaleDisable", Mutation, Localization, DraftProxy::localization_mutation_root, []),
        entry!("translationsRegister", Mutation, Localization, DraftProxy::localization_mutation_root, []),
        entry!("translationsRemove", Mutation, Localization, DraftProxy::localization_mutation_root, []),
        entry!("files", Query, Media, DraftProxy::media_query_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("stagedUploadsCreate", Mutation, Media, DraftProxy::media_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileAcknowledgeUpdateFailed", Mutation, Media, DraftProxy::media_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileCreate", Mutation, Media, DraftProxy::media_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileUpdate", Mutation, Media, DraftProxy::media_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileDelete", Mutation, Media, DraftProxy::media_mutation_root, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
    ]
}

fn registry_entry(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    handler: Option<NativeResolverHandler>,
    runtime_tests: &[&str],
) -> ExecutableRootRegistration {
    let implemented = handler.is_some();
    ExecutableRootRegistration {
        entry: OperationRegistryEntry {
            api_surface: ApiSurface::Admin,
            name: name.to_string(),
            operation_type,
            domain,
            implemented,
            runtime_tests: strings(runtime_tests),
            commit_id_mappings: commit_id_mappings(name),
        },
        handler,
    }
}

fn commit_id_mappings(name: &str) -> Vec<CommitIdMappingSpec> {
    match name {
        "productSet" => vec![single_commit_id_mapping(&["Product"], &["product", "id"])],
        "productDuplicate" => vec![single_commit_id_mapping(
            &["Product"],
            &["newProduct", "id"],
        )],
        "productBundleCreate" => vec![single_commit_id_mapping(
            &["Product"],
            &["productBundleOperation", "product", "id"],
        )],
        "productCreate" => vec![
            single_commit_id_mapping(&["Product"], &["product", "id"]),
            single_commit_id_mapping(&["ProductVariant"], &["product", "variants", "nodes", "id"]),
            argument_list_commit_id_mapping(
                &["ExternalVideo", "MediaImage", "Model3d", "Video"],
                &["product", "media", "nodes", "id"],
                &["media"],
            ),
        ],
        "productVariantsBulkCreate" => vec![argument_list_commit_id_mapping(
            &["ProductVariant"],
            &["productVariants", "id"],
            &["variants"],
        )],
        "productCreateMedia" => vec![argument_list_commit_id_mapping(
            &["ExternalVideo", "MediaImage", "Model3d", "Video"],
            &["media", "id"],
            &["media"],
        )],
        "fileCreate" => vec![argument_list_commit_id_mapping(
            &[
                "ExternalVideo",
                "GenericFile",
                "MediaImage",
                "Model3d",
                "Video",
            ],
            &["files", "id"],
            &["files"],
        )],
        "productOptionsCreate" => vec![argument_list_commit_id_mapping(
            &["ProductOption"],
            &["product", "options", "id"],
            &["options"],
        )],
        "appPurchaseOneTimeCreate" => vec![single_commit_id_mapping(
            &["AppPurchaseOneTime"],
            &["appPurchaseOneTime", "id"],
        )],
        "appSubscriptionCreate" => vec![single_commit_id_mapping(
            &["AppSubscription"],
            &["appSubscription", "id"],
        )],
        "appUsageRecordCreate" => vec![single_commit_id_mapping(
            &["AppUsageRecord"],
            &["appUsageRecord", "id"],
        )],
        "companyContactCreate" => vec![single_commit_id_mapping(
            &["CompanyContact"],
            &["companyContact", "id"],
        )],
        "companyCreate" => vec![single_commit_id_mapping(&["Company"], &["company", "id"])],
        "companyLocationCreate" => vec![single_commit_id_mapping(
            &["CompanyLocation"],
            &["companyLocation", "id"],
        )],
        "customerCreate" | "customerSet" => {
            vec![single_commit_id_mapping(&["Customer"], &["customer", "id"])]
        }
        "customerAddressCreate" => vec![single_commit_id_mapping(
            &["MailingAddress"],
            &["address", "id"],
        )],
        "sellingPlanGroupCreate" => vec![single_commit_id_mapping(
            &["SellingPlanGroup"],
            &["sellingPlanGroup", "id"],
        )],
        "productFeedCreate" => vec![single_commit_id_mapping(
            &["ProductFeed"],
            &["productFeed", "id"],
        )],
        "publicationCreate" => vec![single_commit_id_mapping(
            &["Publication"],
            &["publication", "id"],
        )],
        "locationAdd" => vec![single_commit_id_mapping(&["Location"], &["location", "id"])],
        "savedSearchCreate" => vec![single_commit_id_mapping(
            &["SavedSearch"],
            &["savedSearch", "id"],
        )],
        "articleCreate" => vec![single_commit_id_mapping(&["Article"], &["article", "id"])],
        "blogCreate" => vec![single_commit_id_mapping(&["Blog"], &["blog", "id"])],
        "pageCreate" => vec![single_commit_id_mapping(&["Page"], &["page", "id"])],
        "themeCreate" => vec![single_commit_id_mapping(
            &["OnlineStoreTheme"],
            &["theme", "id"],
        )],
        "scriptTagCreate" => vec![single_commit_id_mapping(
            &["ScriptTag"],
            &["scriptTag", "id"],
        )],
        "webPixelCreate" => vec![single_commit_id_mapping(&["WebPixel"], &["webPixel", "id"])],
        "serverPixelCreate" => vec![single_commit_id_mapping(
            &["ServerPixel"],
            &["serverPixel", "id"],
        )],
        "mobilePlatformApplicationCreate" => vec![single_commit_id_mapping(
            &["MobilePlatformApplication"],
            &["mobilePlatformApplication", "id"],
        )],
        "storefrontAccessTokenCreate" => vec![single_commit_id_mapping(
            &["StorefrontAccessToken"],
            &["storefrontAccessToken", "id"],
        )],
        "inventoryTransferCreate"
        | "inventoryTransferCreateAsReadyToShip"
        | "inventoryTransferDuplicate" => {
            vec![single_commit_id_mapping(
                &["InventoryTransfer"],
                &["inventoryTransfer", "id"],
            )]
        }
        "inventoryShipmentCreate" | "inventoryShipmentCreateInTransit" => {
            vec![single_commit_id_mapping(
                &["InventoryShipment"],
                &["inventoryShipment", "id"],
            )]
        }
        "metafieldDefinitionCreate" | "standardMetafieldDefinitionEnable" => {
            vec![single_commit_id_mapping(
                &["MetafieldDefinition"],
                &["createdDefinition", "id"],
            )]
        }
        "metaobjectCreate" | "metaobjectUpsert" => vec![single_commit_id_mapping(
            &["Metaobject"],
            &["metaobject", "id"],
        )],
        "metaobjectDefinitionCreate" | "standardMetaobjectDefinitionEnable" => {
            vec![single_commit_id_mapping(
                &["MetaobjectDefinition"],
                &["metaobjectDefinition", "id"],
            )]
        }
        "collectionCreate" => vec![single_commit_id_mapping(
            &["Collection"],
            &["collection", "id"],
        )],
        "customerPaymentMethodCreateFromDuplicationData"
        | "customerPaymentMethodCreditCardCreate"
        | "customerPaymentMethodPaypalBillingAgreementCreate"
        | "customerPaymentMethodRemoteCreate" => vec![single_commit_id_mapping(
            &["CustomerPaymentMethod"],
            &["customerPaymentMethod", "id"],
        )],
        "paymentCustomizationCreate" => vec![single_commit_id_mapping(
            &["PaymentCustomization"],
            &["paymentCustomization", "id"],
        )],
        "validationCreate" => vec![single_commit_id_mapping(
            &["Validation"],
            &["validation", "id"],
        )],
        "cartTransformCreate" => vec![single_commit_id_mapping(
            &["CartTransform"],
            &["cartTransform", "id"],
        )],
        "paymentTermsCreate" => vec![single_commit_id_mapping(
            &["PaymentTerms"],
            &["paymentTerms", "id"],
        )],
        "fulfillmentCreate" | "fulfillmentCreateV2" => vec![single_commit_id_mapping(
            &["Fulfillment"],
            &["fulfillment", "id"],
        )],
        "fulfillmentEventCreate" => vec![single_commit_id_mapping(
            &["FulfillmentEvent"],
            &["fulfillmentEvent", "id"],
        )],
        "fulfillmentServiceCreate" => vec![single_commit_id_mapping(
            &["FulfillmentService"],
            &["fulfillmentService", "id"],
        )],
        "carrierServiceCreate" => vec![single_commit_id_mapping(
            &["DeliveryCarrierService"],
            &["carrierService", "id"],
        )],
        "giftCardCreate" => vec![single_commit_id_mapping(&["GiftCard"], &["giftCard", "id"])],
        "fulfillmentConstraintRuleCreate" => vec![single_commit_id_mapping(
            &["FulfillmentConstraintRule"],
            &["fulfillmentConstraintRule", "id"],
        )],
        "deliveryProfileCreate" => vec![single_commit_id_mapping(
            &["DeliveryProfile"],
            &["profile", "id"],
        )],
        "deliveryCustomizationCreate" => vec![single_commit_id_mapping(
            &["DeliveryCustomization"],
            &["deliveryCustomization", "id"],
        )],
        "deliveryPromiseProviderUpsert" => vec![single_commit_id_mapping(
            &["DeliveryPromiseProvider"],
            &["deliveryPromiseProvider", "id"],
        )],
        "orderCreate" => vec![single_commit_id_mapping(&["Order"], &["order", "id"])],
        "refundCreate" => vec![single_commit_id_mapping(&["Refund"], &["refund", "id"])],
        "returnCreate" => vec![single_commit_id_mapping(&["Return"], &["return", "id"])],
        "reverseDeliveryCreateWithShipping" => vec![single_commit_id_mapping(
            &["ReverseDelivery"],
            &["reverseDelivery", "id"],
        )],
        "draftOrderCreate" | "draftOrderCreateFromOrder" | "draftOrderDuplicate" => {
            vec![single_commit_id_mapping(
                &["DraftOrder"],
                &["draftOrder", "id"],
            )]
        }
        "discountCodeBasicCreate" | "discountCodeBxgyCreate" | "discountCodeFreeShippingCreate" => {
            vec![single_commit_id_mapping(&[], &["codeDiscountNode", "id"])]
        }
        "discountAutomaticBasicCreate"
        | "discountAutomaticBxgyCreate"
        | "discountAutomaticFreeShippingCreate" => vec![single_commit_id_mapping(
            &[],
            &["automaticDiscountNode", "id"],
        )],
        "discountCodeAppCreate" => vec![single_commit_id_mapping(&[], &["codeAppDiscount", "id"])],
        "discountAutomaticAppCreate" => vec![single_commit_id_mapping(
            &[],
            &["automaticAppDiscount", "id"],
        )],
        "discountRedeemCodeBulkAdd" => vec![single_commit_id_mapping(
            &["DiscountRedeemCodeBulkCreation"],
            &["bulkCreation", "id"],
        )],
        "marketingActivityCreate" | "marketingActivityCreateExternal" => {
            vec![single_commit_id_mapping(
                &["MarketingActivity"],
                &["marketingActivity", "id"],
            )]
        }
        "marketingEngagementCreate" => vec![single_commit_id_mapping(
            &["MarketingEngagement"],
            &["marketingEngagement", "id"],
        )],
        "eventBridgeWebhookSubscriptionCreate"
        | "pubSubWebhookSubscriptionCreate"
        | "webhookSubscriptionCreate" => vec![single_commit_id_mapping(
            &["WebhookSubscription"],
            &["webhookSubscription", "id"],
        )],
        "customerSegmentMembersQueryCreate" => vec![single_commit_id_mapping(
            &["CustomerSegmentMembersQuery"],
            &["customerSegmentMembersQuery", "id"],
        )],
        "segmentCreate" => vec![single_commit_id_mapping(&["Segment"], &["segment", "id"])],
        "priceListCreate" => vec![single_commit_id_mapping(
            &["PriceList"],
            &["priceList", "id"],
        )],
        "marketCreate" => vec![single_commit_id_mapping(&["Market"], &["market", "id"])],
        "catalogCreate" => vec![single_commit_id_mapping(&[], &["catalog", "id"])],
        "webPresenceCreate" => vec![single_commit_id_mapping(
            &["MarketWebPresence"],
            &["webPresence", "id"],
        )],
        _ => Vec::new(),
    }
}

fn single_commit_id_mapping(
    resource_types: &[&str],
    response_path: &[&str],
) -> CommitIdMappingSpec {
    CommitIdMappingSpec {
        resource_types: strings(resource_types),
        response_path: strings(response_path),
        input_order: CommitIdInputOrder::Single,
    }
}

fn argument_list_commit_id_mapping(
    resource_types: &[&str],
    response_path: &[&str],
    argument_path: &[&str],
) -> CommitIdMappingSpec {
    CommitIdMappingSpec {
        resource_types: strings(resource_types),
        response_path: strings(response_path),
        input_order: CommitIdInputOrder::ArgumentList {
            path: strings(argument_path),
        },
    }
}

fn strings(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_string()).collect()
}
