use crate::graphql::OperationType;
use crate::operation_registry::{ApiSurface, CapabilityDomain, OperationRegistryEntry};
use crate::proxy::DraftProxy;
use crate::resolver_registry::{ExecutableRootRegistration, NativeResolverHandler};

macro_rules! entry {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $handler:path,
        true,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            Some($handler),
            true,
            &[$($runtime_test),*],
        )
    };
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $handler:path,
        false,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            None,
            false,
            &[$($runtime_test),*],
        )
    };
}

macro_rules! canonical_entry {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $handler:path,
        $implemented:tt,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        entry!($name, $operation_type, $domain, $handler, $implemented, [$($runtime_test),*])
    };
}

macro_rules! unimplemented_entry {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            None,
            false,
            &[$($runtime_test),*],
        )
    };
}

macro_rules! entry_aliased {
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $handler:path,
        true,
        [$($match_name:literal),* $(,)?],
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry_aliased(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            Some($handler),
            true,
            &[$($match_name),*],
            &[$($runtime_test),*],
        )
    };
    (
        $name:literal,
        $operation_type:ident,
        $domain:ident,
        $handler:path,
        false,
        [$($match_name:literal),* $(,)?],
        [$($runtime_test:literal),* $(,)?]
    ) => {
        registry_entry_aliased(
            $name,
            OperationType::$operation_type,
            CapabilityDomain::$domain,
            None,
            false,
            &[$($match_name),*],
            &[$($runtime_test),*],
        )
    };
}

#[rustfmt::skip]
pub(crate) fn default_registry_bindings() -> Vec<ExecutableRootRegistration> {
    vec![
        canonical_entry!("product", Query, Products, DraftProxy::product_root_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productByIdentifier", Query, Products, DraftProxy::product_by_identifier_root_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("products", Query, Products, DraftProxy::products_root_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productsCount", Query, Products, DraftProxy::products_count_outcome, true, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("productVariants", Query, Products, []),
        unimplemented_entry!("productVariantsCount", Query, Products, []),
        unimplemented_entry!("productTags", Query, Products, []),
        unimplemented_entry!("productTypes", Query, Products, []),
        unimplemented_entry!("productVendors", Query, Products, []),
        canonical_entry!("productOperation", Query, Products, DraftProxy::product_operation_root, true, ["tests/graphql_routes.rs"]),
        unimplemented_entry!("productDuplicateJob", Query, Products, []),
        unimplemented_entry!("productResourceFeedback", Query, Products, []),
        canonical_entry!("productFeed", Query, Products, DraftProxy::product_feed_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productFeeds", Query, Products, DraftProxy::product_feeds_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("sellingPlanGroup", Query, Products, DraftProxy::selling_plan_group_root, true, []),
        canonical_entry!("sellingPlanGroups", Query, Products, DraftProxy::selling_plan_groups_root, true, []),
        entry!("publicApiVersions", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, false, []),
        entry!("node", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, []),
        entry!("nodes", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, []),
        entry!("job", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("taxonomy", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, false, []),
        entry!("domain", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("backupRegion", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, []),
        entry!("backupRegionUpdate", Mutation, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, []),
        entry!("staffMember", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, false, []),
        entry!("staffMembers", Query, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, false, []),
        entry!("flowGenerateSignature", Mutation, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, []),
        entry!("flowTriggerReceive", Mutation, AdminPlatform, DraftProxy::resolve_admin_platform_graphql, true, []),
        entry!("app", Query, Apps, DraftProxy::resolve_apps_graphql, false, []),
        entry!("appByHandle", Query, Apps, DraftProxy::resolve_apps_graphql, false, []),
        entry!("appByKey", Query, Apps, DraftProxy::resolve_apps_graphql, false, []),
        entry!("appInstallation", Query, Apps, DraftProxy::resolve_apps_graphql, false, []),
        entry!("appInstallations", Query, Apps, DraftProxy::resolve_apps_graphql, false, []),
        entry!("currentAppInstallation", Query, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appPurchaseOneTimeCreate", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appSubscriptionCreate", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appSubscriptionCancel", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appSubscriptionLineItemUpdate", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appSubscriptionTrialExtend", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appUsageRecordCreate", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appRevokeAccessScopes", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("appUninstall", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("delegateAccessTokenCreate", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        entry!("delegateAccessTokenDestroy", Mutation, Apps, DraftProxy::resolve_apps_graphql, true, []),
        canonical_entry!("productVariant", Query, Products, DraftProxy::product_variant_root_outcome, true, ["tests/graphql_routes/products_saved_searches.rs"]),
        unimplemented_entry!("productVariantByIdentifier", Query, Products, []),
        canonical_entry!("inventoryItem", Query, Products, DraftProxy::inventory_item_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryItems", Query, Products, DraftProxy::inventory_items_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipment", Query, Products, DraftProxy::inventory_shipment_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryLevel", Query, Products, DraftProxy::inventory_level_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryProperties", Query, Products, DraftProxy::inventory_properties_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransfer", Query, Products, DraftProxy::inventory_transfer_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransfers", Query, Products, DraftProxy::inventory_transfers_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collection", Query, Products, DraftProxy::collection_root, true, []),
        canonical_entry!("collectionByIdentifier", Query, Products, DraftProxy::collection_by_identifier_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionByHandle", Query, Products, DraftProxy::collection_by_handle_root, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collections", Query, Products, DraftProxy::collections_root, true, []),
        canonical_entry!("collectionsCount", Query, Products, DraftProxy::collections_count_root, true, []),
        entry!("locations", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, ["tests/graphql_routes/platform.rs"]),
        entry!("locationsCount", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, ["tests/graphql_routes/platform.rs"]),
        entry!("shop", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("location", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("locationByIdentifier", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("businessEntities", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, false, []),
        entry!("businessEntity", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, false, []),
        entry!("companies", Query, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companiesCount", Query, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("company", Query, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyContact", Query, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactRole", Query, B2b, DraftProxy::resolve_b2b_graphql, false, []),
        entry!("companyLocation", Query, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocations", Query, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companiesDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyAddressDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyAssignCustomerAsContact", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyAssignMainContact", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactAssignRole", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactAssignRoles", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactCreate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactRemoveFromCompany", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactRevokeRole", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactRevokeRoles", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactsDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyContactSendWelcomeEmail", Mutation, B2b, DraftProxy::resolve_b2b_graphql, false, []),
        entry!("companyContactUpdate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyCreate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyLocationAssignAddress", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationAssignRoles", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationAssignStaffMembers", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationCreate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationRemoveStaffMembers", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationRevokeRoles", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationsDelete", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationTaxSettingsUpdate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyLocationUpdate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("companyRevokeMainContact", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, []),
        entry!("companyUpdate", Mutation, B2b, DraftProxy::resolve_b2b_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("cashManagementLocationSummary", Query, StoreProperties, DraftProxy::resolve_store_properties_graphql, false, []),
        entry!("cashTrackingSession", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("cashTrackingSessions", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethod", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("orderPaymentStatus", Query, Payments, DraftProxy::resolve_payments_graphql, false, []),
        entry!("paymentCustomization", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentCustomizations", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("validation", Query, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("validations", Query, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("cartTransforms", Query, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("shopifyFunction", Query, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("shopifyFunctions", Query, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("paymentTermsTemplates", Query, Payments, DraftProxy::resolve_payments_graphql, true, ["tests/graphql_routes/orders.rs"]),
        entry!("financeAppAccessPolicy", Query, Payments, DraftProxy::resolve_payments_graphql, false, []),
        entry!("financeKycInformation", Query, Payments, DraftProxy::resolve_payments_graphql, false, []),
        entry!("pointOfSaleDevice", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("dispute", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("disputes", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("disputeEvidence", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("shopPayPaymentRequestReceipt", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("shopPayPaymentRequestReceipts", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("shopifyPaymentsAccount", Query, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("tenderTransactions", Query, Payments, DraftProxy::resolve_payments_graphql, false, []),
        canonical_entry!("channel", Query, Products, DraftProxy::channel_root, true, []),
        canonical_entry!("channels", Query, Products, DraftProxy::channels_root, true, []),
        canonical_entry!("publication", Query, Products, DraftProxy::publication_root, true, []),
        unimplemented_entry!("publications", Query, Products, []),
        canonical_entry!("publicationsCount", Query, Products, DraftProxy::publications_count_root, true, []),
        canonical_entry!("publishedProductsCount", Query, Products, DraftProxy::published_products_count_root, true, []),
        entry!("storeCreditAccount", Query, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customer", Query, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerAccountPage", Query, Customers, DraftProxy::resolve_customers_graphql, false, []),
        canonical_entry!("event", Query, Events, DraftProxy::resolve_events_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("events", Query, Events, DraftProxy::resolve_events_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("eventsCount", Query, Events, DraftProxy::resolve_events_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("customers", Query, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerAccountPages", Query, Customers, DraftProxy::resolve_customers_graphql, false, []),
        entry!("customersCount", Query, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerByIdentifier", Query, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerMergePreview", Query, Customers, DraftProxy::resolve_customers_graphql, false, []),
        entry!("customerMergeJobStatus", Query, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerCreate", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerUpdate", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerDelete", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerRequestDataErasure", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerCancelDataErasure", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerAddressCreate", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddressUpdate", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddressDelete", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerUpdateDefaultAddress", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerEmailMarketingConsentUpdate", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerSmsMarketingConsentUpdate", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerAddTaxExemptions", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerRemoveTaxExemptions", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerReplaceTaxExemptions", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("customerSet", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerGenerateAccountActivationUrl", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/customers.rs"]),
        entry!("customerSendAccountInviteEmail", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, ["tests/graphql_routes/customers.rs"]),
        entry!("storeCreditAccountCredit", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("storeCreditAccountDebit", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        entry!("customerPaymentMethodSendUpdateEmail", Mutation, Customers, DraftProxy::resolve_customers_graphql, false, []),
        entry!("customerMerge", Mutation, Customers, DraftProxy::resolve_customers_graphql, true, []),
        canonical_entry!("sellingPlanGroupCreate", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("sellingPlanGroupUpdate", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("sellingPlanGroupDelete", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("sellingPlanGroupAddProducts", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("sellingPlanGroupRemoveProducts", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("sellingPlanGroupAddProductVariants", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("sellingPlanGroupRemoveProductVariants", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("productJoinSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("productLeaveSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("productVariantJoinSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        canonical_entry!("productVariantLeaveSellingPlanGroups", Mutation, Products, DraftProxy::selling_plan_outcome, true, []),
        entry_aliased!("tagsAdd", Mutation, Products, DraftProxy::product_tags_outcome, true, ["tagsAdd"], ["tests/graphql_routes.rs"]),
        entry_aliased!("tagsRemove", Mutation, Products, DraftProxy::product_tags_outcome, true, ["tagsRemove"], ["tests/graphql_routes.rs"]),
        canonical_entry!("bulkProductResourceFeedbackCreate", Mutation, Products, DraftProxy::resource_feedback_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("shopResourceFeedbackCreate", Mutation, Products, DraftProxy::resource_feedback_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productCreate", Mutation, Products, DraftProxy::product_create_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productUpdate", Mutation, Products, DraftProxy::product_update_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productDelete", Mutation, Products, DraftProxy::product_delete_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productDuplicate", Mutation, Products, DraftProxy::product_duplicate_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productSet", Mutation, Products, DraftProxy::product_set_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productChangeStatus", Mutation, Products, DraftProxy::product_change_status_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productFeedCreate", Mutation, Products, DraftProxy::product_feed_create_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productFeedDelete", Mutation, Products, DraftProxy::product_feed_delete_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productFullSync", Mutation, Products, DraftProxy::product_full_sync_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productBundleCreate", Mutation, Products, DraftProxy::product_bundle_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productBundleUpdate", Mutation, Products, DraftProxy::product_bundle_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("combinedListingUpdate", Mutation, Products, DraftProxy::product_relationship_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("publicationCreate", Mutation, Products, DraftProxy::publication_mutation_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("publicationUpdate", Mutation, Products, DraftProxy::publication_mutation_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("publicationDelete", Mutation, Products, DraftProxy::publication_mutation_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productPublish", Mutation, Products, DraftProxy::product_publication_outcome, true, ["tests/graphql_routes/products_saved_searches.rs"]),
        canonical_entry!("productUnpublish", Mutation, Products, DraftProxy::product_publication_outcome, true, ["tests/graphql_routes/products_saved_searches.rs"]),
        entry!("locationAdd", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("locationEdit", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("locationActivate", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("locationDeactivate", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("locationDelete", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("publishablePublish", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("publishablePublishToCurrentChannel", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("publishableUnpublish", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("publishableUnpublishToCurrentChannel", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, []),
        entry!("shopPolicyUpdate", Mutation, StoreProperties, DraftProxy::resolve_store_properties_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("customerSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("orderSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("draftOrderSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("fileSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("codeDiscountSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("automaticDiscountSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("discountRedeemCodeSavedSearches", Query, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("savedSearchCreate", Mutation, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("savedSearchUpdate", Mutation, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, []),
        canonical_entry!("savedSearchDelete", Mutation, SavedSearches, DraftProxy::resolve_saved_searches_graphql, true, []),
        entry!("urlRedirectSavedSearches", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirect", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirects", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectsCount", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectBulkDeleteAll", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectBulkDeleteByIds", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectBulkDeleteBySavedSearch", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectBulkDeleteBySearch", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectImportCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("urlRedirectImportSubmit", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("article", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("articleAuthors", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("articles", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("articleTags", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("articleCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("articleUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("articleDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("blog", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("blogs", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("blogsCount", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("blogCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("blogUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("blogDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("page", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("pages", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("pagesCount", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("pageCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("pageUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("pageDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("comment", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("comments", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("commentApprove", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("commentSpam", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("commentNotSpam", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("commentDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("menu", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("menus", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("theme", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themes", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("scriptTag", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("scriptTags", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("webPixel", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("serverPixel", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("mobilePlatformApplication", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("mobilePlatformApplications", Query, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("menuCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("menuUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("menuDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("themeCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themeUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themeDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themePublish", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themeFilesCopy", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themeFilesUpsert", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("themeFilesDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("scriptTagCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("scriptTagUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("scriptTagDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("webPixelCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("webPixelUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("webPixelDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("serverPixelCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("serverPixelDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("eventBridgeServerPixelUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("pubSubServerPixelUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("storefrontAccessTokenCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("storefrontAccessTokenDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        entry!("mobilePlatformApplicationCreate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("mobilePlatformApplicationUpdate", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, true, []),
        entry!("mobilePlatformApplicationDelete", Mutation, OnlineStore, DraftProxy::resolve_online_store_graphql, false, []),
        canonical_entry!("privacySettings", Query, Privacy, DraftProxy::resolve_privacy_graphql, false, []),
        canonical_entry!("consentPolicy", Query, Privacy, DraftProxy::resolve_privacy_graphql, false, []),
        canonical_entry!("consentPolicyRegions", Query, Privacy, DraftProxy::resolve_privacy_graphql, false, []),
        canonical_entry!("consentPolicyUpdate", Mutation, Privacy, DraftProxy::resolve_privacy_graphql, false, []),
        canonical_entry!("privacyFeaturesDisable", Mutation, Privacy, DraftProxy::resolve_privacy_graphql, false, []),
        canonical_entry!("dataSaleOptOut", Mutation, Privacy, DraftProxy::resolve_privacy_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("bulkOperation", Query, BulkOperations, DraftProxy::resolve_bulk_operations_graphql, true, []),
        entry!("bulkOperations", Query, BulkOperations, DraftProxy::resolve_bulk_operations_graphql, true, []),
        entry!("currentBulkOperation", Query, BulkOperations, DraftProxy::resolve_bulk_operations_graphql, true, []),
        entry!("bulkOperationRunQuery", Mutation, BulkOperations, DraftProxy::resolve_bulk_operations_graphql, true, []),
        entry!("bulkOperationRunMutation", Mutation, BulkOperations, DraftProxy::resolve_bulk_operations_graphql, true, []),
        entry!("bulkOperationCancel", Mutation, BulkOperations, DraftProxy::resolve_bulk_operations_graphql, true, []),
        canonical_entry!("productOptionsCreate", Mutation, Products, DraftProxy::product_option_outcome, true, []),
        canonical_entry!("productOptionUpdate", Mutation, Products, DraftProxy::product_option_outcome, true, []),
        canonical_entry!("productOptionsDelete", Mutation, Products, DraftProxy::product_option_outcome, true, []),
        canonical_entry!("productOptionsReorder", Mutation, Products, DraftProxy::product_option_outcome, true, []),
        canonical_entry!("productVariantsBulkCreate", Mutation, Products, DraftProxy::product_variant_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productVariantsBulkUpdate", Mutation, Products, DraftProxy::product_variant_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productVariantsBulkDelete", Mutation, Products, DraftProxy::product_variant_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productVariantsBulkReorder", Mutation, Products, DraftProxy::product_variant_outcome, true, ["tests/graphql_routes.rs"]),
        // Historical parity metadata still names these removed compatibility
        // roots. Keep them explicitly declared as unsupported so discovery can
        // distinguish a retired root from an unregistered operation. The
        // captured versioned schemas remain authoritative and reject them.
        unimplemented_entry!("productVariantCreate", Mutation, Products, []),
        unimplemented_entry!("productVariantUpdate", Mutation, Products, []),
        unimplemented_entry!("productVariantDelete", Mutation, Products, []),
        canonical_entry!("productCreateMedia", Mutation, Products, DraftProxy::product_media_outcome, true, []),
        canonical_entry!("productUpdateMedia", Mutation, Products, DraftProxy::product_media_outcome, true, []),
        canonical_entry!("productDeleteMedia", Mutation, Products, DraftProxy::product_media_outcome, true, []),
        canonical_entry!("productReorderMedia", Mutation, Products, DraftProxy::product_media_outcome, true, []),
        canonical_entry!("productVariantAppendMedia", Mutation, Products, DraftProxy::product_variant_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productVariantDetachMedia", Mutation, Products, DraftProxy::product_variant_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("productVariantRelationshipBulkUpdate", Mutation, Products, DraftProxy::product_relationship_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryItemUpdate", Mutation, Products, DraftProxy::inventory_item_update, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryAdjustQuantities", Mutation, Products, DraftProxy::inventory_adjust_quantities, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventorySetQuantities", Mutation, Products, DraftProxy::inventory_set_quantities, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventorySetOnHandQuantities", Mutation, Products, DraftProxy::inventory_set_on_hand_quantities, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryMoveQuantities", Mutation, Products, DraftProxy::inventory_move_quantities, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryActivate", Mutation, Products, DraftProxy::inventory_activate, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryDeactivate", Mutation, Products, DraftProxy::inventory_deactivate, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryBulkToggleActivation", Mutation, Products, DraftProxy::inventory_bulk_toggle_activation, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferCreate", Mutation, Products, DraftProxy::inventory_transfer_create, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferCreateAsReadyToShip", Mutation, Products, DraftProxy::inventory_transfer_create, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferEdit", Mutation, Products, DraftProxy::inventory_transfer_edit, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferSetItems", Mutation, Products, DraftProxy::inventory_transfer_set_items, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferRemoveItems", Mutation, Products, DraftProxy::inventory_transfer_remove_items, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferMarkAsReadyToShip", Mutation, Products, DraftProxy::inventory_transfer_mark_ready, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferDuplicate", Mutation, Products, DraftProxy::inventory_transfer_duplicate, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferCancel", Mutation, Products, DraftProxy::inventory_transfer_cancel, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryTransferDelete", Mutation, Products, DraftProxy::inventory_transfer_delete, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentCreate", Mutation, Products, DraftProxy::inventory_shipment_create, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentCreateInTransit", Mutation, Products, DraftProxy::inventory_shipment_create, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentAddItems", Mutation, Products, DraftProxy::inventory_shipment_add_items, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentRemoveItems", Mutation, Products, DraftProxy::inventory_shipment_remove_items, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentUpdateItemQuantities", Mutation, Products, DraftProxy::inventory_shipment_update_item_quantities, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentSetTracking", Mutation, Products, DraftProxy::inventory_shipment_set_tracking, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentMarkInTransit", Mutation, Products, DraftProxy::inventory_shipment_mark_in_transit, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentReceive", Mutation, Products, DraftProxy::inventory_shipment_receive, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("inventoryShipmentDelete", Mutation, Products, DraftProxy::inventory_shipment_delete, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("metafieldsSet", Mutation, Products, DraftProxy::owner_metafields_set, true, []),
        canonical_entry!("metafieldsDelete", Mutation, Products, DraftProxy::owner_metafields_delete, true, []),
        entry!("metafieldDefinition", Query, Metafields, DraftProxy::resolve_metafields_graphql, true, []),
        entry!("metafieldDefinitions", Query, Metafields, DraftProxy::resolve_metafields_graphql, true, []),
        entry!("standardMetafieldDefinitionTemplates", Query, Metafields, DraftProxy::resolve_metafields_graphql, false, []),
        entry!("metafieldDefinitionCreate", Mutation, Metafields, DraftProxy::resolve_metafields_graphql, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionUpdate", Mutation, Metafields, DraftProxy::resolve_metafields_graphql, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionDelete", Mutation, Metafields, DraftProxy::resolve_metafields_graphql, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metafieldDefinitionPin", Mutation, Metafields, DraftProxy::resolve_metafields_graphql, true, []),
        entry!("metafieldDefinitionUnpin", Mutation, Metafields, DraftProxy::resolve_metafields_graphql, true, []),
        entry!("standardMetafieldDefinitionEnable", Mutation, Metafields, DraftProxy::resolve_metafields_graphql, true, ["tests/graphql_routes/metafields_markets_products_tail.rs"]),
        entry!("metaobject", Query, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectByHandle", Query, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjects", Query, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectDefinition", Query, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectDefinitionByType", Query, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectDefinitions", Query, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectCreate", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectUpdate", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectUpsert", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectDelete", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectBulkDelete", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("metaobjectDefinitionCreate", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectDefinitionUpdate", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("metaobjectDefinitionDelete", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, []),
        entry!("standardMetaobjectDefinitionEnable", Mutation, Metaobjects, DraftProxy::resolve_metaobjects_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        canonical_entry!("collectionCreate", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionUpdate", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionDelete", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionAddProducts", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionAddProductsV2", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionRemoveProducts", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        canonical_entry!("collectionReorderProducts", Mutation, Products, DraftProxy::collection_outcome, true, ["tests/graphql_routes.rs"]),
        entry!("order", Query, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("return", Query, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orders", Query, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("ordersCount", Query, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnCalculate", Query, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes/orders.rs"]),
        entry!("returnableFulfillment", Query, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("returnableFulfillments", Query, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes/orders.rs"]),
        entry!("reverseDelivery", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("reverseFulfillmentOrder", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("abandonedCheckouts", Query, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("abandonedCheckoutsCount", Query, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("abandonment", Query, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("abandonmentByAbandonedCheckoutId", Query, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("orderUpdate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderClose", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("orderOpen", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("orderMarkAsPaid", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!(
            "orderCreateManualPayment",
            Mutation,
            Orders,
            DraftProxy::resolve_orders_graphql,
            true,
            ["tests/graphql_routes/orders.rs"]
        ),
        entry!("orderRiskAssessmentCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("customerPaymentMethodCreateFromDuplicationData", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodCreditCardCreate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodCreditCardUpdate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodGetDuplicationData", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodGetUpdateUrl", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodPaypalBillingAgreementCreate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodPaypalBillingAgreementUpdate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodRemoteCreate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("customerPaymentMethodRevoke", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("orderCapture", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("orderCreateMandatePayment", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentCustomizationActivation", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentCustomizationCreate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentCustomizationDelete", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentCustomizationUpdate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("validationCreate", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("validationUpdate", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("validationDelete", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("cartTransformCreate", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("cartTransformDelete", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("taxAppConfigure", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, []),
        entry!("paymentReminderSend", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentTermsCreate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentTermsDelete", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("paymentTermsUpdate", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("disputeEvidenceUpdate", Mutation, Payments, DraftProxy::resolve_payments_graphql, false, []),
        entry!("shopifyPaymentsPayoutAlternateCurrencyCreate", Mutation, Payments, DraftProxy::resolve_payments_graphql, false, []),
        entry!("transactionVoid", Mutation, Payments, DraftProxy::resolve_payments_graphql, true, []),
        entry!("orderCustomerSet", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("orderCustomerRemove", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!(
            "orderInvoiceSend",
            Mutation,
            Orders,
            DraftProxy::resolve_orders_graphql,
            true,
            ["tests/graphql_routes/orders.rs"]
        ),
        entry!("taxSummaryCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("orderCancel", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("fulfillmentCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("fulfillmentCreateV2", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes/orders.rs"]),
        entry!("fulfillmentTrackingInfoUpdate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!(
            "fulfillmentTrackingInfoUpdateV2",
            Mutation,
            Orders,
            DraftProxy::resolve_orders_graphql,
            true,
            ["tests/graphql_routes/orders.rs"]
        ),
        entry!("fulfillmentCancel", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("fulfillment", Query, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes/orders.rs"]),
        entry!("fulfillmentEventCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("assignedFulfillmentOrders", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrder", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrders", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("manualHoldsFulfillmentOrders", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderAcceptCancellationRequest", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderAcceptFulfillmentRequest", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderCancel", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderClose", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderHold", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!(
            "fulfillmentOrderLineItemsPreparedForPickup",
            Mutation,
            ShippingFulfillments,
            DraftProxy::resolve_shipping_fulfillments_graphql,
            true,
            ["tests/graphql_routes/platform.rs"]
        ),
        entry!("fulfillmentOrderMerge", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderMove", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderOpen", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderRejectCancellationRequest", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderRejectFulfillmentRequest", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderReleaseHold", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderReportProgress", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderReschedule", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrdersReroute", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrdersSetFulfillmentDeadline", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderSplit", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderSubmitCancellationRequest", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentOrderSubmitFulfillmentRequest", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentService", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentServiceCreate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentServiceDelete", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentServiceUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("availableCarrierServices", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("carrierService", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("carrierServices", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("carrierServiceCreate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("carrierServiceDelete", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("carrierServiceUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("giftCard", Query, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCards", Query, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardsCount", Query, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardConfiguration", Query, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardCreate", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardUpdate", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardCredit", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardDebit", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardDeactivate", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardSendNotificationToCustomer", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("giftCardSendNotificationToRecipient", Mutation, GiftCards, DraftProxy::resolve_gift_cards_graphql, true, []),
        entry!("deliveryCustomization", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizations", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseParticipants", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseProvider", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseSettings", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("deliverySettings", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("deliveryProfile", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfiles", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationsAvailableForDeliveryProfilesConnection", Query, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationLocalPickupDisable", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("locationLocalPickupEnable", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("shippingPackageDelete", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("shippingPackageMakeDefault", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("shippingPackageUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("fulfillmentConstraintRules", Query, Functions, DraftProxy::resolve_functions_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleCreate", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleDelete", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("fulfillmentConstraintRuleUpdate", Mutation, Functions, DraftProxy::resolve_functions_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("deliveryProfileCreate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfileRemove", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryProfileUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationActivation", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationCreate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationDelete", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryCustomizationUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseParticipantsUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliveryPromiseProviderUpsert", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, ["tests/graphql_routes/admin_app_shipping.rs"]),
        entry!("deliverySettingUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, false, []),
        entry!("orderEditAddShippingLine", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditRemoveShippingLine", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditUpdateShippingLine", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderDelete", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditAddCustomItem", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditAddLineItemDiscount", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditRemoveDiscount", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("abandonmentUpdateActivitiesDeliveryStatuses", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("refundCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnRequest", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnApproveRequest", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnDeclineRequest", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnCancel", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnClose", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnReopen", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("removeFromReturn", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("returnProcess", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("reverseDeliveryCreateWithShipping", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("reverseDeliveryShippingUpdate", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("reverseFulfillmentOrderDispose", Mutation, ShippingFulfillments, DraftProxy::resolve_shipping_fulfillments_graphql, true, []),
        entry!("draftOrder", Query, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("draftOrders", Query, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrdersCount", Query, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderAvailableDeliveryOptions", Query, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("draftOrderTag", Query, Orders, DraftProxy::resolve_orders_graphql, false, []),
        entry!("draftOrderCreate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("draftOrderComplete", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("draftOrderUpdate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderDuplicate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderBulkAddTags", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("draftOrderBulkRemoveTags", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("draftOrderBulkDelete", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderDelete", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderCalculate", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderInvoicePreview", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("draftOrderInvoiceSend", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("draftOrderCreateFromOrder", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, ["tests/graphql_routes.rs"]),
        entry!("orderEditBegin", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditAddVariant", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditSetQuantity", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("orderEditCommit", Mutation, Orders, DraftProxy::resolve_orders_graphql, true, []),
        entry!("discountNodes", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountNodesCount", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountNode", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("codeDiscountNodes", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("codeDiscountNode", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("codeDiscountNodeByCode", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountRedeemCodeBulkCreation", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("automaticDiscountNodes", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("automaticDiscountNode", Query, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeBasicCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeBasicUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeBxgyCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeBxgyUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeFreeShippingCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeFreeShippingUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeActivate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeDeactivate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeDelete", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeBulkActivate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountCodeBulkDeactivate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountCodeBulkDelete", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountRedeemCodeBulkAdd", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry_aliased!("discountCodeRedeemCodeBulkDelete", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, ["discountCodeRedeemCodeBulkDelete", "DiscountCodeRedeemCodeBulkDelete", "discountRedeemCodeBulkDelete", "DiscountRedeemCodeBulkDelete",], []),
        entry!("discountAutomaticBasicCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticBasicUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticBxgyCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticBxgyUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticFreeShippingCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticFreeShippingUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticActivate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticDeactivate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticDelete", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticBulkDelete", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, ["tests/graphql_routes/discounts_gift_cards_functions_localization.rs"]),
        entry!("discountCodeAppCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountCodeAppUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticAppCreate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("discountAutomaticAppUpdate", Mutation, Discounts, DraftProxy::resolve_discounts_graphql, true, []),
        entry!("marketingActivities", Query, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivity", Query, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingEvent", Query, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingEvents", Query, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivityCreate", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivityUpdate", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivityCreateExternal", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivityUpdateExternal", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivityUpsertExternal", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivityDeleteExternal", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingActivitiesDeleteAllExternal", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingEngagementCreate", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("marketingEngagementsDelete", Mutation, Marketing, DraftProxy::resolve_marketing_graphql, true, []),
        entry!("webhookSubscription", Query, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("webhookSubscriptions", Query, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("webhookSubscriptionsCount", Query, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("eventBridgeWebhookSubscriptionCreate", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("eventBridgeWebhookSubscriptionUpdate", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("pubSubWebhookSubscriptionCreate", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("pubSubWebhookSubscriptionUpdate", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("webhookSubscriptionCreate", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("webhookSubscriptionUpdate", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("webhookSubscriptionDelete", Mutation, Webhooks, DraftProxy::resolve_webhooks_graphql, true, []),
        entry!("segment", Query, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("segments", Query, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("segmentsCount", Query, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("segmentFilters", Query, Segments, DraftProxy::resolve_segments_graphql, false, []),
        entry!("segmentFilterSuggestions", Query, Segments, DraftProxy::resolve_segments_graphql, false, []),
        entry!("segmentValueSuggestions", Query, Segments, DraftProxy::resolve_segments_graphql, false, []),
        entry!("segmentMigrations", Query, Segments, DraftProxy::resolve_segments_graphql, false, []),
        entry!("customerSegmentMembers", Query, Segments, DraftProxy::resolve_segments_graphql, false, []),
        entry!("customerSegmentMembersQuery", Query, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("customerSegmentMembership", Query, Segments, DraftProxy::resolve_segments_graphql, false, []),
        entry!("customerSegmentMembersQueryCreate", Mutation, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("segmentCreate", Mutation, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("segmentUpdate", Mutation, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("segmentDelete", Mutation, Segments, DraftProxy::resolve_segments_graphql, true, []),
        entry!("market", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("markets", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalog", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalogs", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalogsCount", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceList", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceLists", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListCreate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListDelete", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListFixedPricesAdd", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListFixedPricesUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListFixedPricesDelete", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("priceListFixedPricesByProductUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("quantityPricingByVariantUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("quantityRulesAdd", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("quantityRulesDelete", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("webPresences", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketsResolvedValues", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketLocalizableResource", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketLocalizableResources", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketLocalizableResourcesByIds", Query, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketCreate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketDelete", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalogCreate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalogUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalogContextUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("catalogDelete", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("webPresenceCreate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("webPresenceUpdate", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("webPresenceDelete", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketLocalizationsRegister", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("marketLocalizationsRemove", Mutation, Markets, DraftProxy::resolve_markets_graphql, true, []),
        entry!("availableLocales", Query, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("shopLocales", Query, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("translatableResource", Query, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("translatableResources", Query, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("translatableResourcesByIds", Query, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("shopLocaleEnable", Mutation, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("shopLocaleUpdate", Mutation, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("shopLocaleDisable", Mutation, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("translationsRegister", Mutation, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("translationsRemove", Mutation, Localization, DraftProxy::resolve_localization_graphql, true, []),
        entry!("files", Query, Media, DraftProxy::resolve_media_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("stagedUploadsCreate", Mutation, Media, DraftProxy::resolve_media_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileAcknowledgeUpdateFailed", Mutation, Media, DraftProxy::resolve_media_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileCreate", Mutation, Media, DraftProxy::resolve_media_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileUpdate", Mutation, Media, DraftProxy::resolve_media_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
        entry!("fileDelete", Mutation, Media, DraftProxy::resolve_media_graphql, true, ["tests/graphql_routes/marketing_inventory_online_store.rs"]),
    ]
}

fn registry_entry(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    handler: Option<NativeResolverHandler>,
    implemented: bool,
    runtime_tests: &[&str],
) -> ExecutableRootRegistration {
    registry_entry_with_match_names(
        name,
        operation_type,
        domain,
        handler,
        implemented,
        default_match_names(name),
        runtime_tests,
    )
}

fn registry_entry_aliased(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    handler: Option<NativeResolverHandler>,
    implemented: bool,
    match_names: &[&str],
    runtime_tests: &[&str],
) -> ExecutableRootRegistration {
    registry_entry_with_match_names(
        name,
        operation_type,
        domain,
        handler,
        implemented,
        strings(match_names),
        runtime_tests,
    )
}

fn registry_entry_with_match_names(
    name: &str,
    operation_type: OperationType,
    domain: CapabilityDomain,
    handler: Option<NativeResolverHandler>,
    implemented: bool,
    match_names: Vec<String>,
    runtime_tests: &[&str],
) -> ExecutableRootRegistration {
    ExecutableRootRegistration {
        entry: OperationRegistryEntry {
            api_surface: ApiSurface::Admin,
            name: name.to_string(),
            operation_type,
            domain,
            implemented,
            match_names,
            runtime_tests: strings(runtime_tests),
        },
        handler,
    }
}

fn default_match_names(name: &str) -> Vec<String> {
    let mut chars = name.chars();
    let mut capitalized = String::with_capacity(name.len());
    if let Some(first) = chars.next() {
        capitalized.extend(first.to_uppercase());
        capitalized.push_str(chars.as_str());
    }
    vec![name.to_string(), capitalized]
}

fn strings(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_string()).collect()
}
